cxWidgets: /home/erico/projects/cxWidgets/examples/centipede/main.cpp File Reference
main.cpp File Reference
#include "../../src/cxBase.h"
#include "CentipedeGame.h"
Functions
int main ()
Function Documentation
main()
int main ()
References cxBase::cleanup(), cxBase::init(), CentipedeGame::run(), and cxWindow::show().