cxWidgets: cx::cxWidgetsException Class Reference
cx::cxWidgetsException Class Reference
Represents an exception in cxWidgets.
#include <cxWidgetsException.h>
Public Member Functions
cxWidgetsException (const std::string &pErrorMsg="")
Default constructor.
virtual ~cxWidgetsException ()
const std::string & getErrorMsg () const
Returns the error message.
virtual std::string cxTypeStr () const
Returns the name of the cxWidgets class. This can be used to.
Detailed Description
Represents an exception in cxWidgets.
with an error string. If something goes wrong in cxWidgets, one of these exceptions will be thrown. At the very least, your main program should include its code in a try/catch and should catch a const cxWidgetsException&. The error message can be retreived via the getErrorMsg() method.
Constructor & Destructor Documentation
cxWidgetsException()
cx::cxWidgetsException::cxWidgetsException (const std::string & pErrorMsg = "") explicit
Default constructor.
Parameters
pErrorMsg A string describing an error
~cxWidgetsException()
cx::cxWidgetsException::~cxWidgetsException () virtual
Member Function Documentation
cxTypeStr()
string cx::cxWidgetsException::cxTypeStr () const virtual
Returns the name of the cxWidgets class. This can be used to.
determine the type of cxWidgets object that deriving classes
derive from in applications.
Returns
The name of the cxWidgets class.
getErrorMsg()
const string & cx::cxWidgetsException::getErrorMsg () const
Returns the error message.
Returns
The error message
Referenced by cxFormAppendComboBoxPair(), cxFormAppendPair(), and cxWindowSizeTest().
The documentation for this class was generated from the following files:
/home/erico/projects/cxWidgets/src/cxWidgetsException.h
/home/erico/projects/cxWidgets/src/cxWidgetsException.cpp