cxWidgets: cxDate Class Reference
cxDate Class Reference
Enables easy management of dates. C++14-compatible.
#include <cxDate.h>
Public Member Functions
cxDate (eDateFormats pDateFormat=YYYY_MM_DD, char pSepChar='-')
cxDate (int pYear, int pMonth, int pDay, eDateFormats pDateFormat=YYYY_MM_DD, char pSepChar='-') noexcept
cxDate (const std::string &pDateStr, eDateFormats pDateFormat=YYYY_MM_DD, char pSepChar='-')
cxDate (const std::string &pDateStr, char pSepChar)
cxDate (long pJulianDate, eDateFormats pDateFormat=YYYY_MM_DD, char pSepChar='-') noexcept
virtual ~cxDate ()=default
cxDate (const cxDate &)=default
cxDate & operator= (const cxDate &)=default
int getYear () const noexcept
int getMonth () const noexcept
int getDay () const noexcept
eDateFormats getDateFormat () const noexcept
char getSepChar () const noexcept
bool getDisplayLong () const noexcept
void setYear (int pYear) noexcept
void setMonth (int pMonth) noexcept
void setDay (int pDay) noexcept
void setDateFormat (eDateFormats pDateFormat) noexcept
void setSepChar (char pSepChar) noexcept
void setDisplayLong (bool pDisplay) noexcept
bool setDate (int pYear, int pMonth, int pDay) noexcept
void addYears (int pNumYears) noexcept
void subtractYears (int pNumYears) noexcept
void addMonths (int pNumMonths) noexcept
void subtractMonths (int pNumMonths) noexcept
void addDays (int pNumDays) noexcept
void subtractDays (int pNumDays) noexcept
void operator+= (int pNumDays) noexcept
void operator-= (int pNumDays) noexcept
bool operator== (const cxDate &pThat) const noexcept
bool operator!= (const cxDate &pThat) const noexcept
bool operator> (const cxDate &pThat) const noexcept
bool operator>= (const cxDate &pThat) const noexcept
bool operator< (const cxDate &pThat) const noexcept
bool operator<= (const cxDate &pThat) const noexcept
cxDate operator++ (int) noexcept
cxDate & operator++ () noexcept
cxDate operator-- (int) noexcept
cxDate & operator-- () noexcept
cxDate operator+ (int pNumDays) const noexcept
cxDate operator- (int pNumDays) const noexcept
int operator- (const cxDate &pThat) const noexcept
std::string toString () const
bool fromString (const std::string &pDateStr)
int numMonthDays () const noexcept
bool isLeapYear () const noexcept
eWeekDays dayOfWeek () const noexcept
std::string dayOfWeekStr () const
long toJulian () const noexcept
void fromJulian (long pJulianDate) noexcept
Static Public Member Functions
static int numMonthDays (int pMonth, int pYear) noexcept
static bool isLeapYear (int pYear) noexcept
static eWeekDays dayOfWeek (int pYear, int pMonth, int pDay) noexcept
static std::string dayOfWeekStr (eWeekDays pWeekDay)
static std::string dayOfWeekStr (int pYear, int pMonth, int pDay)
static std::string monthName (int pMonth, bool pAbbreviated=false)
static std::string getToday (bool pLong=false)
static int getCurrentYear () noexcept
static cxDate today () noexcept
static bool tryParse (const std::string &pDateStr, cxDate &outDate, eDateFormats pDateFormat=YYYY_MM_DD, char pSepChar='-')
static long toJulian (int pYear, int pMonth, int pDay) noexcept
static void fromJulian (long pJulianDate, int &pYear, int &pMonth, int &pDay) noexcept
static eDateFormats getDateFormat (const std::string &pDateStr)
static std::string getDateFormatStr (eDateFormats pDateFormat)
static void monthCalendar (int pYear, int pMonth, std::ostream &pOutStream=std::cout, int pTrailingEndlines=2)
static void yearCalendar (int pYear, std::ostream &pOutStream=std::cout, int pTrailingEndlines=2)
Friends
std::ostream & operator<< (std::ostream &pOS, const cxDate &pDate)
std::istream & operator>> (std::istream &pIS, cxDate &pDate)
Detailed Description
Enables easy management of dates. C++14-compatible.
Note: Months and days are 1-based (months 1-12, days 1-31). Julian date calculations assume noon for time of day, so Julian dates are whole numbers.
Constructor & Destructor Documentation
cxDate() [1/6]
cxDate::cxDate (eDateFormats pDateFormat = YYYY_MM_DD, char pSepChar = '-') explicit
Default constructor - initializes to today's date.
cxDate() [2/6]
cxDate::cxDate (int pYear, int pMonth, int pDay, eDateFormats pDateFormat = YYYY_MM_DD, char pSepChar = '-') noexcept
Constructor with explicit year, month, day.
cxDate() [3/6]
cxDate::cxDate (const std::string & pDateStr, eDateFormats pDateFormat = YYYY_MM_DD, char pSepChar = '-')
Constructor from a date string (e.g. "2026-03-16").
References fromString().
cxDate() [4/6]
cxDate::cxDate (const std::string & pDateStr, char pSepChar)
Constructor from a date string with auto-detected format.
References fromString(), getDateFormat(), and UNKNOWN.
cxDate() [5/6]
cxDate::cxDate (long pJulianDate, eDateFormats pDateFormat = YYYY_MM_DD, char pSepChar = '-') noexcept
Constructor from a Julian date number.
~cxDate()
virtual cxDate::~cxDate () virtual default
cxDate() [6/6]
cxDate::cxDate (const cxDate &) default
Member Function Documentation
addDays()
void cxDate::addDays (int pNumDays) noexcept
Adds pNumDays days to the date.
References CXDATE_END_MONTH, CXDATE_START_DAY, and CXDATE_START_MONTH.
Referenced by operator+(), operator++(), and test_Arithmetic().
addMonths()
void cxDate::addMonths (int pNumMonths) noexcept
Adds pNumMonths months to the date, adjusting the year as needed.
References CXDATE_END_MONTH, CXDATE_MONTHS_IN_YEAR, and CXDATE_START_MONTH.
Referenced by test_Arithmetic().
addYears()
void cxDate::addYears (int pNumYears) noexcept
Adds pNumYears years to the date.
dayOfWeek() [1/2]
eWeekDays cxDate::dayOfWeek () const noexcept
Returns
The day of the week for this date.
References dayOfWeek().
Referenced by dayOfWeek(), dayOfWeekStr(), dayOfWeekStr(), and monthCalendar().
dayOfWeek() [2/2]
eWeekDays cxDate::dayOfWeek (int pYear, int pMonth, int pDay) static noexcept
Returns
The day of the week for the given year/month/day.
dayOfWeekStr() [1/3]
string cxDate::dayOfWeekStr () const
Returns
The day-of-week name as a string (e.g. "Monday").
References dayOfWeek(), and dayOfWeekStr().
Referenced by dayOfWeekStr(), dayOfWeekStr(), and operator<<().
dayOfWeekStr() [2/3]
string cxDate::dayOfWeekStr (eWeekDays pWeekDay) static
Returns
The name of pWeekDay as a string (e.g. "Monday").
References eFRIDAY, eMONDAY, eSATURDAY, eSUNDAY, eTHURSDAY, eTUESDAY, and eWEDNESDAY.
dayOfWeekStr() [3/3]
string cxDate::dayOfWeekStr (int pYear, int pMonth, int pDay) static
Returns
The day-of-week name for the given year/month/day.
References dayOfWeek(), and dayOfWeekStr().
fromJulian() [1/2]
void cxDate::fromJulian (long pJulianDate) noexcept
Sets this date from a Julian day number.
fromJulian() [2/2]
void cxDate::fromJulian (long pJulianDate, int & pYear, int & pMonth, int & pDay) static noexcept
Converts pJulianDate to year/month/day components.
fromString()
bool cxDate::fromString (const std::string & pDateStr)
Parses pDateStr and updates this date.
Returns
True on success; false if the string could not be parsed.
References CXDATE_DEFAULT_YEAR, CXDATE_YEAR_2DIGIT_LAST_CENT, DD_MM_YY, DD_MM_YYYY, DDMMYY, DDMMYYYY, MM_DD_YY, MM_DD_YYYY, MMDDYY, MMDDYYYY, YY_MM_DD, YYMMDD, YYYY_MM_DD, and YYYYMMDD.
Referenced by cxDate(), cxDate(), operator>>(), and tryParse().
getCurrentYear()
int cxDate::getCurrentYear () static noexcept
Returns
The current 4-digit year.
getDateFormat() [1/2]
eDateFormats cxDate::getDateFormat () const inline noexcept
Returns
The date format used by toString() and stream output.
Referenced by cxDate().
getDateFormat() [2/2]
eDateFormats cxDate::getDateFormat (const std::string & pDateStr) static
Returns
The date format detected from pDateStr, or UNKNOWN.
References DD_MM_YY, DD_MM_YYYY, DDMMYY, MM_DD_YY, MMDDYY, UNKNOWN, YYYY_MM_DD, and YYYYMMDD.
getDateFormatStr()
string cxDate::getDateFormatStr (eDateFormats pDateFormat) static
Returns
A human-readable string name for pDateFormat.
References DD_MM_YY, DD_MM_YYYY, DDMMYY, DDMMYYYY, MM_DD_YY, MM_DD_YYYY, MMDDYY, MMDDYYYY, YY_MM_DD, YYMMDD, YYYY_MM_DD, and YYYYMMDD.
getDay()
int cxDate::getDay () const inline noexcept
Returns
The day-of-month component of the date (1–31).
Referenced by cxDatePicker::cxDatePicker(), cxDatePicker::setDate(), test_Arithmetic(), and test_Constructors().
getDisplayLong()
bool cxDate::getDisplayLong () const inline noexcept
Returns
True if the date is formatted in long human-readable form.
getMonth()
int cxDate::getMonth () const inline noexcept
Returns
The month component of the date (1–12).
Referenced by cxDatePicker::setDate(), cxDatePicker::showModal(), test_Arithmetic(), and test_Constructors().
getSepChar()
char cxDate::getSepChar () const inline noexcept
Returns
The separator character used in formatted date strings (e.g. '-').
getToday()
string cxDate::getToday (bool pLong = false) static
Returns today's date as "YYYY-MM-DD", or in long format if pLong=true.
References setDisplayLong(), and toString().
getYear()
int cxDate::getYear () const inline noexcept
Returns
The 4-digit year component of the date.
Referenced by cxDatePicker::showModal(), test_Arithmetic(), and test_Constructors().
isLeapYear() [1/2]
bool cxDate::isLeapYear () const noexcept
Returns
True if the current year is a leap year.
References isLeapYear().
Referenced by isLeapYear().
isLeapYear() [2/2]
bool cxDate::isLeapYear (int pYear) static noexcept
Returns
True if pYear is a leap year.
monthCalendar()
void cxDate::monthCalendar (int pYear, int pMonth, std::ostream & pOutStream = std::cout, int pTrailingEndlines = 2) static
Prints a one-month calendar to pOutStream.
Parameters
pTrailingEndlines Number of blank lines printed after the calendar.
References dayOfWeek(), monthName(), and numMonthDays().
Referenced by yearCalendar().
monthName()
string cxDate::monthName (int pMonth, bool pAbbreviated = false) static
Returns
The full or abbreviated name of pMonth (1–12).
Parameters
pAbbreviated If true, returns a 3-letter abbreviation.
Referenced by monthCalendar(), cxDatePicker::setDate(), and cxDatePicker::showModal().
numMonthDays() [1/2]
int cxDate::numMonthDays () const noexcept
Returns
The number of days in the current month.
References numMonthDays().
Referenced by monthCalendar(), and numMonthDays().
numMonthDays() [2/2]
int cxDate::numMonthDays (int pMonth, int pYear) static noexcept
Returns
The number of days in pMonth of pYear, accounting for leap years.
References CXDATE_DEFAULT_YEAR, and CXDATE_YEAR_2DIGIT_LAST_CENT.
operator!=()
bool cxDate::operator!= (const cxDate & pThat) const noexcept
Returns
True if this date differs from pThat.
operator+()
cxDate cxDate::operator+ (int pNumDays) const noexcept
Returns
A new date that is pNumDays days after this date.
References addDays().
operator++() [1/2]
cxDate & cxDate::operator++ () noexcept
References addDays().
operator++() [2/2]
cxDate cxDate::operator++ (int) noexcept
operator+=()
void cxDate::operator+= (int pNumDays) noexcept
Adds pNumDays days in-place.
operator-() [1/2]
int cxDate::operator- (const cxDate & pThat) const noexcept
Returns
The signed number of days between this date and pThat.
operator-() [2/2]
cxDate cxDate::operator- (int pNumDays) const noexcept
Returns
A new date that is pNumDays days before this date.
References subtractDays().
operator--() [1/2]
cxDate & cxDate::operator-- () noexcept
References subtractDays().
operator--() [2/2]
cxDate cxDate::operator-- (int) noexcept
operator-=()
void cxDate::operator-= (int pNumDays) noexcept
Subtracts pNumDays days in-place.
operator<()
bool cxDate::operator< (const cxDate & pThat) const noexcept
Returns
True if this date is earlier than pThat.
operator<=()
bool cxDate::operator<= (const cxDate & pThat) const noexcept
Returns
True if this date is earlier than or equal to pThat.
operator=()
cxDate & cxDate::operator= (const cxDate &) default
operator==()
bool cxDate::operator== (const cxDate & pThat) const noexcept
Returns
True if this date equals pThat.
operator>()
bool cxDate::operator> (const cxDate & pThat) const noexcept
Returns
True if this date is later than pThat.
operator>=()
bool cxDate::operator>= (const cxDate & pThat) const noexcept
Returns
True if this date is later than or equal to pThat.
setDate()
bool cxDate::setDate (int pYear, int pMonth, int pDay) noexcept
Sets year, month, and day simultaneously.
Returns
true if the date is valid; false if values were out of range.
Referenced by cxDatePicker::cxDatePicker().
setDateFormat()
void cxDate::setDateFormat (eDateFormats pDateFormat) noexcept
Sets the date format used by toString() and stream output.
References UNKNOWN.
setDay()
void cxDate::setDay (int pDay) noexcept
Sets the day-of-month component, clamped to the valid range for the current month.
setDisplayLong()
void cxDate::setDisplayLong (bool pDisplay) inline noexcept
Enables or disables long human-readable date output.
Referenced by getToday().
setMonth()
void cxDate::setMonth (int pMonth) noexcept
Sets the month component, clamped to [1, 12].
setSepChar()
void cxDate::setSepChar (char pSepChar) inline noexcept
Sets the separator character used in formatted date strings.
setYear()
void cxDate::setYear (int pYear) noexcept
Sets the year component, clamped to [CXDATE_YEAR_MIN, CXDATE_YEAR_MAX].
subtractDays()
void cxDate::subtractDays (int pNumDays) noexcept
Subtracts pNumDays days from the date.
Referenced by operator-(), operator--(), and test_Arithmetic().
subtractMonths()
void cxDate::subtractMonths (int pNumMonths) noexcept
Subtracts pNumMonths months from the date, adjusting the year as needed.
subtractYears()
void cxDate::subtractYears (int pNumYears) noexcept
Subtracts pNumYears years from the date.
today()
cxDate cxDate::today () static noexcept
Returns today's date as a cxDate object.
Referenced by cxDatePicker::cxDatePicker().
toJulian() [1/2]
long cxDate::toJulian () const noexcept
Returns
This date as a Julian day number.
References toJulian().
Referenced by toJulian().
toJulian() [2/2]
long cxDate::toJulian (int pYear, int pMonth, int pDay) static noexcept
Returns
The Julian day number for the given year/month/day.
toString()
string cxDate::toString () const
Returns
The date as a formatted string (format determined by mDateFormat).
Referenced by cxDatePickerTest(), and getToday().
tryParse()
bool cxDate::tryParse (const std::string & pDateStr, cxDate & outDate, eDateFormats pDateFormat = YYYY_MM_DD, char pSepChar = '-') static
Tries to parse a date string into outDate.
Returns
True if parsing succeeded; false otherwise.
References fromString().
yearCalendar()
void cxDate::yearCalendar (int pYear, std::ostream & pOutStream = std::cout, int pTrailingEndlines = 2) static
Prints a full-year calendar to pOutStream.
Parameters
pTrailingEndlines Number of blank lines printed after the calendar.
References monthCalendar().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & pOS, const cxDate & pDate) friend
Writes the formatted date to pOS.
operator>>
std::istream & operator>> (std::istream & pIS, cxDate & pDate) friend
Reads a formatted date from pIS.
The documentation for this class was generated from the following files:
/home/erico/projects/cxWidgets/src/cxDate.h
/home/erico/projects/cxWidgets/src/cxDate.cpp