cxWidgets: SpreadsheetApp Class Reference
SpreadsheetApp Class Reference
#include <SpreadsheetApp.h>
Public Member Functions
SpreadsheetApp ()
void run ()
Constructor & Destructor Documentation
SpreadsheetApp()
SpreadsheetApp::SpreadsheetApp ()
Member Function Documentation
run()
void SpreadsheetApp::run ()
References cx::cxMenuBar::addMenu(), cx::cxWindow::addQuitKey(), cx::cxMenu::append(), cx::cleanup(), CTRL_D, CTRL_O, CTRL_S, CTRL_X, cx::cxID_CANCEL, cx::cxID_QUIT, cx::cxITEM_NORMAL, cx::eBLACK_WHITE, cx::eBS_NOBORDER, ESC, cx::eWHITE_BLUE, cx::cxGrid::getCell(), cx::cxGrid::getFocusCol(), cx::cxGrid::getFocusRow(), cx::cxWindow::getLastKey(), cx::cxMenuBar::getLastMenuReturnCode(), cx::cxWindow::getLastMouseEvtCoords(), cx::getTermDimensions(), cx::cxMenuBar::hide(), cx::init(), MENU_FILE_CLOSE, MENU_FILE_EXIT, MENU_FILE_OPEN, MENU_FILE_SAVE, MENU_FILE_SAVE_AS, MENU_HELP_ABOUT, MENU_HELP_HELP, cx::promptYesNo(), cx::cxMenuBar::setBarColor(), cx::cxMenuBar::setHighlightColor(), cx::cxGrid::show(), cx::cxMenuBar::show(), cx::cxGrid::showColHeaders(), cx::cxGrid::showModal(), cx::cxMenuBar::showModal(), cx::cxMenuBar::showModalWithClick(), and cx::cxGrid::showRowHeaders().
Referenced by main().
The documentation for this class was generated from the following files:
/home/erico/projects/cxWidgets/examples/spreadsheet/SpreadsheetApp.h
/home/erico/projects/cxWidgets/examples/spreadsheet/SpreadsheetApp.cpp