cxWidgets: cx::cxSearchPanel Class Reference
cx::cxSearchPanel Class Reference
This class is based on cxPanel, and it contains a cxForm at the top.
#include <cxSearchPanel.h>
Public Member Functions
cxSearchPanel (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pFormTitle="", const std::string &pMenuTitle="", eBorderStyle pFormBorderStyle=eBS_SINGLE_LINE, eBorderStyle pMenuBorderStyle=eBS_SINGLE_LINE)
Default constructor.
cxSearchPanel (const cxSearchPanel &pPanel)
Copy constructor.
virtual ~cxSearchPanel ()
const std::shared_ptr< cxForm > & getForm () const
Returns a pointer to the cxForm on the panel.
const std::shared_ptr< cxMenu > & getMenu () const
Returns a pointer to the cxMenu on the panel.
virtual std::shared_ptr< cxMultiLineInput > appendToForm (int pRow, int pCol, int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputKind=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue=nullptr)
Adds an input to the form and returns a pointer to the new.
virtual std::shared_ptr< cxComboBox > appendComboBoxToForm (int pRow, int pCol, int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputKind=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue=nullptr)
Adds a combo box to the form. Returns a pointer to the new input.
virtual void appendToMenu (const std::string &pDisplayText, long pReturnCode, const std::string &pHelpString="", const std::string &pItemText="", cxMenuItemType pType=cxITEM_NORMAL)
Adds a string item to the end of the menu.
virtual void appendToMenu (const std::string &pDisplayText, const std::string &pHelpString="", const std::string &pItemText="", cxMenuItemType pType=cxITEM_NORMAL)
Adds a string item to the end of the menu, defaulting the.
virtual void clearFormInputs (bool pRefresh=false, bool pOnlyEditable=false)
Clears the inputs on the form.
virtual void clearMenu (bool pRefresh=false)
Removes the menu items.
void setFormOnFocusFunction (funcPtr4 pFuncPtr, void *p1, void *p2, void *p3, void *p4, bool pUseVal=false, bool pExitAfterRun=false)
Sets the onFocus funtion for the form.
void setFormOnFocusFunction (funcPtr2 pFuncPtr, void *p1, void *p2, bool pUseVal=false, bool pExitAfterRun=false)
Sets the onFocus funtion for the form.
void setFormOnFocusFunction (funcPtr0 pFuncPtr, bool pUseVal=false, bool pExitAfterRun=false)
Sets the onFocus funtion for the form.
void setFormOnLeaveFunction (funcPtr4 pFuncPtr, void *p1, void *p2, void *p3, void *p4)
Sets the onLeave function for the form.
void setFormOnLeaveFunction (funcPtr2 pFuncPtr, void *p1, void *p2)
Sets the onLeave function for the form.
void setFormOnLeaveFunction (funcPtr0 pFuncPtr)
Sets the onLeave function for the form.
virtual void setMenuOnFocusFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal=false, bool pExitAfterRun=false)
Sets the onFocus function for the menu.
virtual void setMenuOnFocusFunction (funcPtr2 pFunction, void *p1, void *p2, bool pUseVal=false, bool pExitAfterRun=false)
Sets the onFocus function for the menu.
virtual void setMenuOnFocusFunction (funcPtr0 pFunction, bool pUseVal=false, bool pExitAfterRun=false)
Sets the onFocus function for the menu.
virtual void setMenuOnLeaveFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets the onLeave function for the menu.
virtual void setMenuOnLeaveFunction (funcPtr2 pFunction, void *p1, void *p2)
Sets the onLeave function for the menu.
virtual void setMenuOnLeaveFunction (funcPtr0 pFunction)
Sets the onLeave function for the menu.
virtual void resize (int pNewHeight, int pNewWidth, bool pRefresh=true) override
Changes the width and height, and re-sizes the form and menu.
virtual void setFormHeight (int pNewHeight, bool pRefresh=true)
Sets the form's height. The menu will also be re-sized accordingly.
virtual void setMenuHeight (int pNewHeight, bool pRefresh=true)
Sets the menu's height. The form will also be re-sized accordingly.
virtual std::string cxTypeStr () const override
Returns the name of the cxWidgets class ("cxSearchPanel").
virtual bool setFormOnEnterFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets a function to be called when the enter key is pressed on.
virtual bool setFormOnEnterFunction (funcPtr2 pFunction, void *p1, void *p2)
Sets a function to be called when the enter key is pressed on.
virtual bool setFormOnEnterFunction (funcPtr0 pFunction)
Sets a function to be called when the enter key is pressed on.
virtual void clearFormOnEnterFunction ()
Removes the onEnter function from the form.
virtual bool setFormKeyFunction (int pFunctionKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Adds a function to the form to call when the user presses some.
virtual bool setFormKeyFunction (int pFunctionKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Adds a function to the form to call when the user presses some.
virtual bool setFormKeyFunction (int pFunctionKey, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Adds a function to the form to call when the user presses some.
virtual void clearFormKeyFunction (int pFunctionKey)
Removes a hotkey from the form so that it will not.
virtual void clearFormKeyFunctions ()
Clears the form's list of external functions fired by hotkeys.
virtual bool formHasKeyFunction (int pFunctionKey) const
Returns whether the form has a function hotkey set up to.
virtual bool setMenuKeyFunction (int pFunctionKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Adds a function to the menu to call when the user presses some.
virtual bool setMenuKeyFunction (int pFunctionKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Adds a function to the menu to call when the user presses some.
virtual bool setMenuKeyFunction (int pFunctionKey, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Adds a function to the menu to call when the user presses some.
virtual void clearMenuKeyFunction (int pFunctionKey)
Removes a hotkey from the menu so that it will not.
virtual void clearMenuKeyFunctions ()
Clears the menu's list of external functions fired by hotkeys.
virtual bool menuHasKeyFunction (int pFunctionKey) const
Returns whether the menu has a function hotkey set up to.
virtual bool setMenuOnSelectItemFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pExitAfterRun, bool pRunOnLeaveFunction)
Sets a function to run when the user selects an item from the.
virtual bool setMenuOnSelectItemFunction (funcPtr2 pFunction, void *p1, void *p2, bool pExitAfterRun, bool pRunOnLeaveFunction)
Sets a function to run when the user selects an item from the.
virtual bool setMenuOnSelectItemFunction (funcPtr0 pFunction, bool pExitAfterRun, bool pRunOnLeaveFunction)
Sets a function to run when the user selects an item from the.
virtual bool itemWasSelected () const
Returns whether or not an item was selected from the menu.
virtual std::string getSelectedItem (bool pDisplayText=true) const
Returns text of the item selected from the menu, if there was.
virtual bool setFormCurrent ()
Makes the form be the current window.
virtual bool setMenuCurrent ()
Makes the menu be the current window.
Public Member Functions inherited from cx::cxPanel
cxPanel (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", const std::string &pMessage="", const std::string &pStatus="", eBorderStyle pBorderStyle=eBS_NOBORDER, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pMessageUnderlines=false)
Default constructor.
virtual ~cxPanel ()
virtual long showModal (bool pShowSelf=true, bool pBringToTop=true, bool pShowSubwindows=true) override
Shows the panel and all of its subwindows and.
virtual bool getExitOnLeaveLast () const
Returns whether or not the panel will exit focus.
virtual void setExitOnLeaveLast (bool pExitOnLeaveLast)
Sets whether the panel should exit focus.
virtual bool getExitOnLeaveFirst () const
Returns whether the panel will exit focus.
virtual void setExitOnLeaveFirst (bool pExitOnLeaveFirst)
Sets whether the panel should exit focus.
virtual unsigned int numWindows () const
Returns the number of windows that are contained.
virtual std::shared_ptr< cxWindow > getWindow (unsigned pIndex) const
Gets a pointer to one of the subwindows (by index).
virtual bool append (const std::shared_ptr< cxWindow > &pWindow)
Adds a window to the panel. Note: The cxWindow.
virtual bool append (const std::shared_ptr< cxWindow > &pWindow, int pRow, int pCol, bool pRefresh=false)
Adds a window to the panel with relative coordinates.
virtual void delWindow (unsigned pIndex)
Removes a window from the panel (by index) and frees the memory.
virtual void delWindow (const std::shared_ptr< cxWindow > &pWindow)
Removes a window from the panel (by pointer), and frees the.
virtual void delAllWindows ()
Removes all windows from the panel. Also frees the memory used.
virtual std::shared_ptr< cxWindow > removeWindow (unsigned int pIndex)
Removes a window from the panel, without freeing its memory.
virtual void removeWindow (const std::shared_ptr< cxWindow > &pWindow)
Removes a window from the panel, without freeing its memory.
virtual void removeWindow (cxWindow *pWindow)
virtual bool windowIsInPanel (const std::shared_ptr< cxWindow > &pWindow) const
Returns whether a cxWindow object is contained.
virtual bool windowIsInPanel (cxWindow *pWindow) const
virtual bool move (int pNewRow, int pNewCol, bool pRefresh=true) override
Changes the panel's position, based on a new upper-left corner.
virtual bool setCurrentWindow (unsigned pIndex)
Sets which window will get focus in the next.
virtual bool setCurrentWindow (const std::string &pID, bool pIsTitle=true)
Sets which window will get focus in the next.
virtual bool setCurrentWindowByPtr (const std::shared_ptr< cxWindow > &pWindow)
Sets which window will get focus in the next.
virtual bool setCurrentWindowByPtr (cxWindow *pWindow)
virtual bool setKeyFunction (int pKey, const std::shared_ptr< cxFunction > &pFunction) override
Sets a function to be called when a key is pressed.
virtual void clearKeyFunction (int pKey) override
Removes a function pointer for a keypress for the panel so that it will no.
virtual bool setKeyFunction (int pKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
Sets a function to be called when a key is pressed. Note that.
virtual bool setKeyFunction (int pKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
Sets a function to be called when a key is pressed. Note that.
virtual bool setKeyFunction (int pKey, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
Sets a function to be called when a key is pressed. Note that.
virtual int getCurrentWindowIndex () const
Returns the index of the current window.
virtual int getWindowIndex (const std::shared_ptr< cxWindow > &pWindow) const
Given a cxWindow pointer, this function will return the index.
virtual int getWindowIndex (cxWindow *pWindow) const
virtual const std::shared_ptr< cxWindow > & getCurrentWindowPtr () const
Returns a pointer to the current window.
virtual long show (bool pBringToTop=false, bool pShowSubwindows=true) override
Shows the panel. If setShowPanelWindow(false) has been.
virtual void hide (bool pHideSubwindows=true) override
Hides the panel, along with the windows in the panel.
virtual void unhide (bool pUnhideSubwindows=true) override
Un-hides the panel, along with the windows in the panel.
virtual bool getShowPanelWindow () const
Returns whether or not the panel window will be.
virtual void setShowPanelWindow (bool pShowPanelWindow)
Sets whether or not the panel window should be shown.
virtual bool getAllowExit () const
Returns whether the user is allowed to exit out.
virtual void setAllowExit (bool pAllowExit)
Sets whether the user is allowed to exit out of.
virtual bool getAllowQuit () const
Returns whether the user is allowed to quit out.
virtual void setAllowQuit (bool pAllowQuit)
Sets whether the user is allowed to quit out of.
virtual bool windowIsEnabled (unsigned pIndex) const
Returns whether or not one of the windows in the panel.
virtual void enableWindow (unsigned pIndex, bool pEnabled=true)
Enables/disables one of the windows in the panel (by index).
virtual void clear (bool pRefresh=false) override
Clears all the window in the panel.
virtual bool addQuitKey (int pKey, bool pRunOnLeaveFunction=true, bool pOverride=false) override
Adds a key that will cause the window to quit its input loop.
virtual void removeQuitKey (int pKey) override
Removes a quit key.
virtual bool addExitKey (int pKey, bool pRunOnLeaveFunction=true, bool pOverride=false) override
Adds a key that will cause the window to quit its input loop.
virtual void removeExitKey (int pKey) override
Removes an exit key.
virtual void setEnabled (bool pEnabled) override
Enables or disables the panel. Disabling/enabling a cxPanel.
virtual void setEnabled (unsigned pIndex, bool pEnabled)
Enables or disables a window in the panel (by index).
virtual void setEnabled (const std::string &pID, bool pEnabled, bool pIsTitle=true)
Enables or disables a window in the panel (by title/name).
virtual bool swap (int pWindow1Index, int pWindow2Index)
Swaps the order of 2 subwindows (by index). If both indexes.
virtual bool swap (cxWindow *pWindow1, cxWindow *pWindow2)
Swaps the order of 2 subwindows (by pointer). If both pointers.
virtual bool swap (const std::shared_ptr< cxWindow > &pWindow1, const std::shared_ptr< cxWindow > &pWindow2)
virtual void setColor (e_WidgetItems pItem, e_cxColors pColor) override
Sets the color of one of the window items.
virtual void quitNow () override
This causes the panel to stop its input loop with a code of.
virtual void exitNow () override
This causes the panel to stop its input loop with a code of.
const std::shared_ptr< cxWindow > & getLastWindow () const
Returns a pointer to the last window in the panel that was.
virtual void setName (unsigned pIndex, const std::string &pName)
Sets the name of one of the windows in the panel (by index).
virtual void setName (const std::string &pID, const std::string &pName, bool pIsTitle=true)
Sets the name of one of the windows in the panel (by title/name).
virtual void setName (const std::string &pName) override
Sets the name of the panel. The name is an alternative means.
virtual int top () const override
Returns the top row of the window.
virtual int bottom () const override
Returns the bottom row of the window.
Public Member Functions inherited from cx::cxWindow
cxWindow (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", const std::string &pMessage="", const std::string &pStatus="", eBorderStyle pBorderStyle=eBS_SINGLE_LINE, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Default constructor.
cxWindow (cxWindow *pParentWindow, int pRow, int pCol, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor.
cxWindow (cxWindow *pParentWindow, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, int pHeight, int pWidth, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, const std::string &pStatus, int pHeight, int pWidth, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, eHPosition pHPosition, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Lets you specify the horizontal position.
cxWindow (const cxWindow &pThatWindow)
Copy constructor.
virtual ~cxWindow ()
virtual void centerHoriz (bool pRefresh=true)
Centers the window horizontally on the screen.
virtual void alignHoriz (eHPosition pPosition, bool pRefresh=true)
Aligns the window horizontally on the screen.
virtual void centerVert (bool pRefresh=true)
Centers the window vertically on the screen.
virtual void alignVert (eVPosition pPosition, bool pRefresh=true)
Aligns the window vertically on the screen.
virtual void center (bool pRefresh=true)
Centers the window on the screen.
virtual std::string getTitle () const
Accessor for title text - Returns the first string in the.
virtual void setTitle (const std::string &pTitle, bool pRefreshTitle=true)
Setter for the title text - This sets the first string in the.
std::string getStatus () const
Accessor for the status line text.
virtual void setStatus (const std::string &pStatus, bool pRefreshStatus=true)
Mutator for the status line text.
std::string getMessage () const
Returns the message that appears in the window, concatenating all message lines together.
virtual void setMessage (const std::string &pMessage)
Sets the text that appears within the window.
virtual void addMessageLineBelow (const std::string &pLine)
Adds a line to the message to be displayed in the window,.
virtual void addMessageLinesBelow (const std::vector< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLinesBelow (const std::list< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLinesBelow (const std::deque< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLineAbove (const std::string &pLine)
Adds a line to the message to be displayed in the window,.
virtual void addMessageLinesAbove (const std::vector< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void addMessageLinesAbove (const std::list< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void addMessageLinesAbove (const std::deque< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void setMessageLines (const std::vector< std::string > &pLines)
Sets the message lines in the window.
virtual void setMessageLines (const std::list< std::string > &pLines)
Sets the message lines in the window.
virtual void setMessageLines (const std::deque< std::string > &pLines)
Sets the message lines in the window.
virtual void removeMessageLine (unsigned pIndex)
Removes a line from the text inside the window (by index).
virtual void setMessageLine (unsigned pIndex, const std::string &pLine)
Modifies one of the lines displayed in the window.
void setHorizTitleAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the title text.
eHPosition getHorizTitleAlignment () const
Accessor for the title text alignment.
void setHorizMessageAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the message text.
eHPosition getHorizMessageAlignment () const
Accessor for the horizontal message text alignment.
void setHorizStatusAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the status text.
eHPosition getHorizStatusAlignment () const
Accessor for the horizontal status text alignment.
void setVerticalMessageAlignment (eVPosition pVAlignment)
Sets the vertical alignment of the message text.
eVPosition getVerticalMessageAlignment () const
Accessor for the vertical message text alignment.
void setExtTitleWindow (cxWindow *pWindow, bool pRefreshTitle=true)
Sets an external cxWindow object to be used for the title, rather.
cxWindow * getExtTitleWindow () const
Accessor for the external title window pointer.
void setExtStatusWindow (cxWindow *pWindow, bool pRefreshStatus=true)
Sets an external cxWindow object to be used for status, rather.
cxWindow * getExtStatusWindow () const
Accessor for the external status window pointer.
bool isHidden () const
Returns whether or not the window is hidden.
virtual bool modalGetsKeypress () const
Returns whether or not a call to showModal() will wait for a.
virtual long setFocus (bool pShowSelf=true, bool pBringToTop=true, bool pShowSubwindows=true)
Alias for showModal()
virtual void setFocusColors ()
Turns on the ncurses attribute A_REVERSE for the window to.
virtual void setFocusColors (attr_t pAttr)
Turns on the ncurses attribute pAttr for the window to.
virtual void unSetFocusColors ()
Disables focus for this window and unhighlights the message.
virtual void unSetFocusColors (attr_t pAttr)
Disables focus for this window and un-highlights the message (using pAttr)
virtual void erase (bool pEraseSubwindows=true)
Erases the window.
virtual void bringToTop (bool pRefresh=true)
Brings the window to the top.
virtual void bringToBottom (bool pRefresh=false)
Puts the window on the bottom of all other windows.
virtual bool isOnTop () const
Returns whether the window is on top of all other windows.
virtual bool isOnBottom () const
Returns whether the window is on the bottom of all other windows.
virtual bool isAbove (const cxWindow &pThatWindow) const
Returns whether the window is above another window.
virtual bool isBelow (const cxWindow &pThatWindow) const
Returns whether a window is below another window.
void touchWindow ()
Marks the window's entire content as dirty so that the next.
virtual void drawBorder (int pRow, int pCol, int pHeight, int pWidth, bool pTop=true, bool pBottom=true, bool pLeft=true, bool pRight=true)
Draws the border (based on the border style)
virtual void drawBorder (int pHeight, int pWidth)
Draws a box in the window.
virtual void drawBorder ()
Draws a box for the window border.
virtual int centerRow () const
Returns the center row of the window.
virtual int left () const
Returns the left column of the window.
virtual int centerCol () const
Returns the center column of the window.
virtual int right () const
Returns the right column of the window.
virtual int width (int pWidth)
Changes the width of the window.
virtual int width () const
Returns the width of the window.
virtual int height (int pHeight)
Changes the height of the window.
virtual int height () const
Returns the height of the window.
virtual void getRect (int &pTop, int &pLeft, int &pBottom, int &pRight)
Returns the coordinates of the rectangle defining the window.
virtual bool pointIsInWindow (int pY, int pX) const
Returns whether a screen location is in the window (including.
virtual bool pointIsInTitle (int pY, int pX) const
Returns whether a screen location is in the title of the window.
virtual void getSize (int &pHeight, int &pWidth)
Returns the height & width of the window.
virtual void addAttr (e_WidgetItems pItem, attr_t pAttr)
Adds an ncurses attribute to use for one of the items in the.
virtual void setAttr (e_WidgetItems pItem, attr_t pAttr)
Sets the ncurses attribute to use for one of the items in the.
virtual void removeAttr (e_WidgetItems pItem, attr_t pAttr)
Removes an ncurses attribute from one of the item lists.
virtual void removeAttrs (e_WidgetItems pItem)
Removes all attributes for a given window item.
virtual void getAttrs (e_WidgetItems pItem, std::set< attr_t > &pAttrs) const
Returns the set of ncurses attributes for a given item.
virtual bool moveRelative (int pVerticalOffset, int pHorizOffset, bool pRefresh=true)
Changes the window's position via vertical & horizontal offsets.
unsigned numSubWindows ()
Returns the number of subwindows in this window.
void setSubWinMessage (unsigned pIndex, const std::string &pMessage)
Sets the message of one of the subwindows (by index).
void setSubWinMessage (const std::string &pTitle, const std::string &pMessage)
Sets the message of one of the subwindows (by title).
virtual bool hasFocus () const
Returns true if window has focus, false otherwise.
virtual void setBorderStyle (eBorderStyle pBorderStyle)
Sets the border style.
eBorderStyle getBorderStyle () const
Returns the border style.
bool hasBorder () const
Does this window have a border?
virtual cxWindow * getParent () const
Returns a pointer to the parent window.
void setParent (cxWindow *pNewParent)
Changes the pointer to the parent window; changes the parent window.
virtual void dump (std::string &pResult)
Returns a string containing all the characters.
virtual void showSubwindows (bool pBringToTop=true, bool pShowSubwindows=true)
Shows the subwindows for the window.
cxWindow & operator= (const cxWindow &pThatWindow)
Assignment operator.
virtual void writeText (int pRow, int pCol, const std::string &pText, bool pRefresh=true)
Writes text on the window. Note that the text is not permanant, so.
virtual void setHotkeyHighlighting (bool pHotkeyHighlighting)
Enables/disables the use of hotkey attributes when writing the message.
bool getHotkeyHighlighting () const
Returns whether hotkey attributes are used when writing the message.
virtual bool isEnabled () const
Returns whether or not the window is enabled.
virtual void setDisableCursorOnShow (bool pDisableCursorOnShow)
Sets whether the window should disable the cursor.
virtual bool getDisableCursorOnShow () const
Returns whether or not the window will disable.
virtual bool getExitOnMouseOutside () const
Returns whether the window exits its modal input loop when.
virtual void setExitOnMouseOutside (bool pExitOnMouseOutside)
Sets whether the window should exit its modal input loop.
virtual int getLastKey () const
Returns the last key pressed by the user (for showModal(), etc.)
virtual void setLastKey (int pLastKey)
Sets the last keypress.
virtual bool lastKeyWasMouseEvt () const
Returns whether or not the last keypress was a mouse event.
virtual void getLastMouseEvtCoords (int &pY, int &pX)
Returns the coordinates of the last mouse event in the window.
virtual bool getChangeColorsOnFocus () const
Returns whether the window will change.
virtual void setChangeColorsOnFocus (bool pChangeColorsOnFocus)
Sets whether colors should change when focus.
virtual void setOnFocusFunction (const std::shared_ptr< cxFunction > &pFunction)
Sets the window's "on focus" function.
virtual void setOnFocusFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal=false, bool pExitAfterRun=false)
Sets the "on focus" function pointer.
virtual void setOnFocusFunction (funcPtr2 pFunction, void *p1, void *p2, bool pUseVal=false, bool pExitAfterRun=false)
Sets the "on focus" function pointer.
virtual void setOnFocusFunction (funcPtr0 pFunction, bool pUseVal=false, bool pExitAfterRun=false)
Sets the "on focus" function pointer.
virtual void setOnLeaveFunction (const std::shared_ptr< cxFunction > &pFunction)
Sets the window's "on leave" function.
virtual void setOnLeaveFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets the "on leave" function pointer.
virtual void setOnLeaveFunction (funcPtr2 pFunction, void *p1, void *p2)
Sets the "on focus" function pointer.
virtual void setOnLeaveFunction (funcPtr0 pFunction)
Sets the "on focus" function pointer.
virtual bool runOnFocusFunction (std::string *pFunctionRetval=nullptr)
Runs the onFocus function, if it's set.
virtual bool runOnLeaveFunction (std::string *pFunctionRetval=nullptr)
Runs the onLeave function, if it's set. However, if the last.
virtual void toggleOnFocusFunction (bool pRunOnFocus)
Sets whether or not the onFocus function should run.
virtual void toggleOnLeaveFunction (bool pRunOnLeave)
Sets whether or not the onLeave function should run.
virtual bool onFocusFunctionEnabled () const
Returns whether or not the onFocus function is set to run.
virtual bool onLeaveFunctionEnabled () const
Returns whether or not the onLeave function is set to run.
virtual const std::shared_ptr< cxFunction > & getOnFocusFunction () const
Accessor for the onFocus function.
virtual const std::shared_ptr< cxFunction > & getOnLeaveFunction () const
Accessor for the onLeave function.
virtual bool isModal () const
Returns whether or not the window is currently.
virtual void clearKeyFunctionByPtr (funcPtr4 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctionByPtr (funcPtr2 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctionByPtr (funcPtr0 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctions ()
Clears the list of external functions fired by hotkeys.
virtual bool hasKeyFunction (int pKey) const
Returns whether an external function exists for a keypress.
virtual bool setMouseFunction (int pMouseState, const std::shared_ptr< cxFunction > &pFunction)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state. This.
virtual void clearMouseFunction (int pMouseState)
Removes a function pointer for a mouse event so that it will.
virtual void clearMouseFunctions ()
Clears the list of external functions fired by mouse events.
virtual bool hasMouseFunction (int pMouseState) const
Returns whether an external function exists for a mouse event.
std::map< int, std::shared_ptr< cxFunction > >::iterator keyFunctions_begin ()
Returns a begin iterator to the map of cxFunction pointers.
std::map< int, std::shared_ptr< cxFunction > >::iterator keyFunctions_end ()
Returns an end iterator to the map of cxFunction pointers.
virtual void getFunctionKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual void getFunctionKeys (std::vector< int > &pKeys) const
Populates a collection with integers representing the keys.
virtual void setShowSubwinsForward (bool pShowSubwinsForward)
Toggles the order in which subwindows will be shown.
virtual bool getShowSubwinsForward () const
Returns whether or not the subwindows will be shown.
virtual void setShowSelfBeforeSubwins (bool pShowSelfBeforeSubwins)
Sets whether the window will show itself before.
virtual bool getShowSelfBeforeSubwins () const
Returns whether or not the window will show itself before.
virtual long getReturnCode () const
Returns the return code set by the last call to.
virtual bool addTitleString (int pHPos, const std::string &pStr, bool pRefreshTitle=false)
Adds/sets a string to appear in the title at.
virtual std::string getTitleString (int pHPos) const
Returns the title string set at a given horizontal position.
virtual std::map< int, std::string > getTitleStrings () const
Returns the map of title strings for the window.
virtual void getTitleStrings (std::map< int, std::string > &pTitleStrings) const
Returns the map of title strings for the window (using an.
virtual void setTitleStrings (const std::map< int, std::string > &pTitleStrings)
Sets all the title strings via a map of horizontal.
virtual void removeTitleString (int pHPos)
Removes a title string at a given horizontal position.
virtual void removeTitleStrings ()
Removes all title strings.
virtual bool addStatusString (int pHPos, const std::string &pStr, bool pRefreshStatus=false)
Adds/sets a string to appear in the status line at.
virtual std::string getStatusString (int pHPos) const
Returns the status string set at a given horizontal position.
virtual std::map< int, std::string > getStatusStrings () const
Returns the map of status strings for the window.
virtual void getStatusStrings (std::map< int, std::string > &pStatusStrings) const
Returns the map of status strings for the window (using an.
virtual void setStatusStrings (const std::map< int, std::string > &pStatusStrings)
Sets all the status strings via a map of horizontal.
virtual void removeStatusString (int pHPos)
Removes a status string at a given horizontal position.
virtual void removeStatusStrings ()
Removes all status strings.
virtual void removeQuitKeys ()
Removes all quit keys.
virtual void removeExitKeys ()
Removes all exit keys.
virtual bool hasExitKey (int pKey) const
Returns whether or not a key exists in the.
virtual bool hasQuitKey (int pKey) const
Returns whether or not a key exists in the.
virtual void getQuitKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual std::string getQuitKeyListString () const
Returns a string containing a comma-separated list of the.
virtual void getExitKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual std::string getExitKeyListString () const
Returns a string containing a comma-separated list of the.
virtual std::map< int, bool > getQuitKeys () const
Returns the keys that will make the window quit its input.
virtual std::map< int, bool > getExitKeys () const
Returns the keys that will make the window exit is input.
void toggleMessage (bool pDrawMessage)
Sets whether or not to draw the message area (the area within.
void toggleTitle (bool pDrawTitle)
Sets whether or not to draw the title.
void toggleStatus (bool pDrawStatus)
Sets whether or not to draw the status line.
bool messageWillDraw () const
Returns whether the message will draw or not.
bool titleWillDraw () const
Returns whether the title will draw or not.
bool statusWillDraw () const
Returns whether the status line will draw or not.
void toggleSpecialChars (bool pDrawSpecialChars)
Sets whether or not to draw the "special" characters (these are.
bool specialCharsWillDraw () const
Returns whether the "special" characters will be drawn or.
virtual void drawTitle ()
Writes the title line.
virtual void drawStatus ()
Writes the status line.
virtual void drawMessage ()
Writes the message text (in the area within the borders)
virtual void drawSpecialChars ()
Writes the set of "special" characters to the window.
virtual void setReturnCode (const long &pReturnCode)
Explicitly sets the member return code for the window.
virtual void setMessageColor (e_cxColors pColor)
Returns the message color.
virtual void setTitleColor (e_cxColors pColor)
Sets the title color.
virtual void setStatusColor (e_cxColors pColor)
Sets the color of the status line at bottom of window.
virtual void setBorderColor (e_cxColors pColor)
Sets the color of the window border.
virtual bool hasAttr (e_WidgetItems pItem, attr_t pAttr)
Returns whether an attribute is set for a widget item.
bool getLeaveNow () const
Returns whether or not something told the window to leave now.
std::string getName () const
bool mouseEvtWasInWindow () const
Returns whether the current mouse information stored in the.
virtual bool mouseEvtWasInTitle () const
Returns whether the current mouse information stored in the.
virtual void doMouseBehavior ()
Triggers the window's mouse event behavior. This method can.
virtual void doMouseBehavior (int pMouseY, int pMouseX)
Triggers the window's mouse event behavior. Also sets the.
std::shared_ptr< cxFunction > getKeyFunction (int pKey) const
Returns a cxFunction pointer for a key.
std::shared_ptr< cxFunction0 > getKeyFunctionAsFunction0 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction0.
std::shared_ptr< cxFunction2 > getKeyFunctionAsFunction2 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction2.
std::shared_ptr< cxFunction4 > getKeyFunctionAsFunction4 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction4.
bool mouseEvtWasButtonEvt () const
Returns whether or not the mouse event read in mMouse was.
bool mouseButton1Pressed () const
Returns whether or not the first mouse button was pressed.
bool mouseButton1Released () const
Returns whether or not the first mouse button was released.
bool mouseButton1Clicked () const
Returns whether or not the first mouse button was clicked.
bool mouseButton1DoubleClicked () const
Returns whether or not the first mouse button was double-clicked.
bool mouseButton2Clicked () const
Returns whether or not the second mouse button was clicked.
bool mouseButton2DoubleClicked () const
Returns whether or not the second mouse button was double-clicked.
bool mouseButton3Clicked () const
Returns whether or not the second mouse button was clicked.
virtual void mouseButton1Click (int pY, int pX)
Tells the window that mouse button 1 was clicked at a certain.
virtual void mouseButton2Click (int pY, int pX)
Tells the window that mouse button 2 was clicked at a certain.
virtual void mouseButton3Click (int pY, int pX)
Tells the window that mouse button 3 was clicked at a certain.
std::string getString (int pRow, int pCol, int pNumber)
Get the contents of a portion of the window. (for debugging/testing)
void info ()
Display information about a window (for debugging/testing)
virtual void toggleBorderTop (bool pToggle)
Sets whether or not to display the top border.
virtual void toggleBorderBottom (bool pToggle)
Sets whether or not to display the bottom border.
virtual void toggleBorderLeft (bool pToggle)
Sets whether or not to display the left border.
virtual void toggleBorderRight (bool pToggle)
Sets whether or not to display the right border.
virtual void addSpecialChar (int pY, int pX, chtype pChar, attr_t pAttr=A_NORMAL)
Adds a character to be written somewhere in the window. These.
virtual void removeSpecialChar (int pY, int pX)
Removes a character from the set of special characters (by.
virtual void clearSpecialChars ()
Clears the collection of special characters.
virtual bool functionExistsForLastMouseState () const
Returns whether an external function pointer exists for the.
int getMouseState () const
Returns the current mouse state as it was last captured by the.
std::string getMouseStateStr () const
Returns a string version of the current mouse state as it was.
virtual e_cxColors getItemColor (e_WidgetItems pItem) const
Returns the color of one of the items in a window.
Public Member Functions inherited from cx::cxObject
cxObject ()
virtual ~cxObject ()
virtual void beep ()
Protected Member Functions
void copyCxSearchPanelStuff (const cxSearchPanel *pThatPanel)
Makes a copy of another cxSearchPanel.
Protected Member Functions inherited from cx::cxPanel
bool anyEnabledWindows () const
Returns whether any of the windows contained in mWindows are.
bool lastEnabledWindow (int pIndex) const
Returns whether or not a window in the panel with a given index.
bool firstEnabledWindow (int pIndex) const
Returns whether or not a window in the panel with a given index.
Protected Member Functions inherited from cx::cxWindow
virtual void reCreatePanel ()
Creates mPanel (by calling new_panel()), then sets up.
void freeWindow ()
Frees the memory used by the ncurses window and.
virtual void init (int pRow, int pCol, int pHeight, int pWidth, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pParentWindow=nullptr, bool pResizeVertically=true)
Initializes the window parameters and sets up the internal.
virtual void removeAllSubwindows ()
Removes all subwindow pointers.
virtual void addSubwindow (cxWindow *pSubWindow)
Adds a subwindow to the window. Subwindows of a.
virtual void removeSubWindow (const cxWindow *pSubWindow)
Removes a window from the subwindow list.
virtual void setElementColor (short &pColorPair, attr_t &pElementAttr, e_cxColors pColor)
Sets the color (and attribute, if necessary) of a color element.
virtual void enableAttrs (WINDOW *pWin, e_WidgetItems pItem)
Enables the attributes for one of the m*Attrs sets for an ncurses window.
virtual void disableAttrs (WINDOW *pWin, e_WidgetItems pItem)
Disables the attributes for one of the m*Attrs sets for an ncurses window.
virtual void writeWithHighlighting (WINDOW *pWindow, const std::string &pText, const int &pY, const int &pStartX, const int &pEndX, int pNormalTextItem=-1)
Writes text to an ncurses WINDOW, highlighting any characters.
virtual void copyCxWinStuff (const cxWindow *pThatWindow, bool pRecreateWin=true)
Makes a copy of a cxWindow's member variables.
virtual void getRowColBasedOn (cxWindow *pParentWindow, eHPosition pPosition, const std::string &pTitle, const std::string &pStatus, const std::string &pMessage, int &pRow, int &pCol)
Figures out how to align text based on a title & message.
virtual bool handleFunctionForLastKey (bool *pFunctionExists=nullptr, bool *pRunOnLeaveFunction=nullptr)
Looks for a function tied to the last keypress and.
virtual bool handleFunctionForLastMouseState (bool *pFunctionExists=nullptr, bool *pRunOnLeaveFunction=nullptr)
Looks for a function tied to the last mouse state captured.
virtual void draw ()
Fills the member ncurses window structure with the current.
void setKeyFunctions (const cxWindow &pWindow)
Returns whether or not a mouse event location is within.
void setFocusFunctions (const cxWindow &pWindow)
Re-sets the onFocus and onLeave functions from another.
bool parentIsCxPanel () const
Returns whether or not the parent window, if there is one, is.
bool parentIsCxForm () const
Returns whether or not the parent window, if there is one, is.
bool parentIsCxNotebook () const
Returns whether or not the parent window, if there is one, is.
cxWindowPtrContainer::const_iterator subWindows_begin () const
Returns a const iterator to the first subwindow.
cxWindowPtrContainer::const_iterator subWindows_end () const
Returns a const iterator to the one past the last subwindow.
cxWindowPtrContainer::const_reverse_iterator subWindows_rbegin () const
Returns a const reverse begin iterator for the subwindow collection.
cxWindowPtrContainer::const_reverse_iterator subWindows_rend () const
Returns a const reverse end iterator for the subwindow collection.
bool onFocusFunctionIsSet () const
Returns whether or not the onFocus function is set (if.
bool onLeaveFunctionIsSet () const
Returns whether or not the onLeave function is set (if.
Additional Inherited Members
Static Public Member Functions inherited from cx::cxObject
static bool UseColors ()
static void UseColors (bool useIt)
static bool UseBeeps ()
static void UseBeeps (bool useIt)
Protected Types inherited from cx::cxPanel
typedef std::vector< std::shared_ptr< cxWindow > > cxWindowPtrCollection
Protected Attributes inherited from cx::cxPanel
cxWindowPtrCollection mWindows
bool mCycleWin = true
std::shared_ptr< cxWindow > mLastWindow
Protected Attributes inherited from cx::cxWindow
WINDOW * mWindow = nullptr
Everything in the window is written here; this is an nCurses window structure.
messageLineContainer mMessageLines
Contains the text to be shown inside the window (note: the.
std::map< std::pair< int, int >, chtype > mSpecialChars
Contains "special" characters which are added to the window.
std::set< attr_t > mMessageAttrs
Message attributes.
std::set< attr_t > mTitleAttrs
Title attributes.
std::set< attr_t > mStatusAttrs
Status attributes.
std::set< attr_t > mBorderAttrs
Border attributes.
std::set< attr_t > mHotkeyAttrs
Hotkey attributes.
std::map< std::pair< int, int >, attr_t > mSpecialCharAttrs
Attributes for the "special" characters (which are added to.
short mMessageColorPair = eWHITE_BLUE
short mTitleColorPair = eGRAY_BLUE
short mStatusColorPair = eBROWN_BLUE
short mBorderColorPair = eGRAY_BLUE
eHPosition mHorizTitleAlignment = eHP_LEFT
eHPosition mHorizMessageAlignment = eHP_LEFT
eHPosition mHorizStatusAlignment = eHP_LEFT
eVPosition mVerticalMessageAlignment = eVP_TOP
bool mDrawMessage = true
bool mDrawTitle = true
bool mDrawStatus = true
bool mDrawSpecialChars = true
std::shared_ptr< cxFunction > mOnFocusFunction = nullptr
std::shared_ptr< cxFunction > mOnLeaveFunction = nullptr
bool mIsModal = false
bool mLeaveNow = false
std::map< int, std::shared_ptr< cxFunction > > mKeyFunctions
std::map< int, std::shared_ptr< cxFunction > > mMouseFunctions
std::map< int, bool > mQuitKeys
std::map< int, bool > mExitKeys
bool mHotkeyHighlighting
Static Protected Attributes inherited from cx::cxObject
static bool useColors
Whether or not to use colors.
static bool useBeeps
Whether or not to enable beeping.
Detailed Description
This class is based on cxPanel, and it contains a cxForm at the top.
and a cxMenu below the form. This class was designed as something
can be used to do database queries using user-inputted data from the
form and show the results in the menu.
Constructor & Destructor Documentation
cxSearchPanel() [1/2]
cx::cxSearchPanel::cxSearchPanel (cxWindow * pParentWindow = nullptr, int pRow = 0, int pCol = 0, int pHeight = DEFAULT_HEIGHT, int pWidth = DEFAULT_WIDTH, const std::string & pFormTitle = "", const std::string & pMenuTitle = "", eBorderStyle pFormBorderStyle = eBS_SINGLE_LINE, eBorderStyle pMenuBorderStyle = eBS_SINGLE_LINE) explicit
Default constructor.
Parameters
pParentWindow A pointer to the parent window.
pRow The row of the upper-left corner.
pCol The column of the upper-left corner.
pHeight The height of the window.
pWidth The width of the window.
pFormTitle The title for the form
pMenuTitle The title for the menu
pFormBorderStyle The border style for the form
pMenuBorderStyle The border style for the menu
cxSearchPanel() [2/2]
cx::cxSearchPanel::cxSearchPanel (const cxSearchPanel & pPanel)
Copy constructor.
Parameters
pPanel Another cxSearchPanel to copy
References cx::cxPanel::append(), ENTER, ESC, ESCAPE, cx::height(), cx::left(), SHIFT_TAB, cx::top(), and cx::width().
~cxSearchPanel()
cx::cxSearchPanel::~cxSearchPanel () virtual
Member Function Documentation
appendComboBoxToForm()
shared_ptr< cxComboBox > cx::cxSearchPanel::appendComboBoxToForm (int pRow, int pCol, int pHeight, int pWidth, const std::string & pLabel, const std::string & pValidator = "", const std::string & pHelpString = "", eInputOptions pInputKind = eINPUT_EDITABLE, const std::string & pName = "", std::string * pExtValue = nullptr) virtual
Adds a combo box to the form. Returns a pointer to the new input.
Parameters
pRow Y location of the upper-left corner of the input, relative to the form
pCol X location of the upper-left corner of the input, relative to the form
pHeight The height of the input
pWidth The width of the input
pLabel The label to use with the input
pValidator String to use to validate input; see README.txt for details; blank by default
pHelpString A string to be displayed in the statusbar of the form when the input has focus; defaults to empty string
pInputKind Used to set the kind of input (i.e., normal, read-only, etc.); defaults to eINPUT_EDITABLE
pName A name for the input (can be used as an alternative way to identify the input)
pExtValue A pointer to a string to be linked to this input and used for its value. Defaults to nullptr for none.
Returns
A pointer to the new cxMultiLineInput object that is created.
appendToForm()
shared_ptr< cxMultiLineInput > cx::cxSearchPanel::appendToForm (int pRow, int pCol, int pHeight, int pWidth, const std::string & pLabel, const std::string & pValidator = "", const std::string & pHelpString = "", eInputOptions pInputKind = eINPUT_EDITABLE, const std::string & pName = "", std::string * pExtValue = nullptr) virtual
Adds an input to the form and returns a pointer to the new.
input.
Parameters
pRow Y location of the upper-left corner of the input, relative to the form
pCol X location of the upper-left corner of the input, relative to the form
pHeight The height of the input
pWidth The width of the input
pLabel The label to use with the input
pValidator String to use to validate input; see README.txt for details; blank by default
pHelpString A string to be displayed in the statusbar of the form when the input has focus; defaults to empty string
pInputKind Used to set the kind of input (i.e., normal, read-only, etc.); defaults to eINPUT_EDITABLE
pName A name for the input (can be used as an alternative way to identify the input)
pExtValue A pointer to a string to be linked to this input and used for its value. Defaults to nullptr for none.
Returns
A pointer to the new cxMultiLineInput object that is created.
Referenced by cxSearchPanelResize(), cxSearchPanelTest(), and storeSearch().
appendToMenu() [1/2]
virtual void cx::cxSearchPanel::appendToMenu (const std::string & pDisplayText, const std::string & pHelpString = "", const std::string & pItemText = "", cxMenuItemType pType = cxITEM_NORMAL) virtual
Adds a string item to the end of the menu, defaulting the.
item's return code to the next one available.
Parameters
pDisplayText The text to display for the item
pHelpString A string to be displayed in the statusbar of the main window when the item is highlighted
pItemText Alternate text to use for the item
pType The kind of menu item (from the cxMenuItemType enumeration in cxMenuItemType.h)
appendToMenu() [2/2]
virtual void cx::cxSearchPanel::appendToMenu (const std::string & pDisplayText, long pReturnCode, const std::string & pHelpString = "", const std::string & pItemText = "", cxMenuItemType pType = cxITEM_NORMAL) virtual
Adds a string item to the end of the menu.
Parameters
pDisplayText The text to display for the item
pReturnCode The integer code that the the menu should return when show() exits
pHelpString A string to be displayed in the statusbar of the main window when the item is highlighted
pItemText Alternate text to use for the item
pType The kind of menu item (from the cxMenuItemType enumeration in cxMenuItemType.h)
Referenced by onFocusMenu().
clearFormInputs()
void cx::cxSearchPanel::clearFormInputs (bool pRefresh = false, bool pOnlyEditable = false) virtual
Clears the inputs on the form.
Parameters
pRefresh Whether or not to refresh the screen. Defaults to false.
pOnlyEditable Whether or not to clear only the editable inputs. Defaults to false.
clearFormKeyFunction()
void cx::cxSearchPanel::clearFormKeyFunction (int pFunctionKey) virtual
Removes a hotkey from the form so that it will not.
fire a function.
Parameters
pFunctionKey The hotkey to remove
clearFormKeyFunctions()
void cx::cxSearchPanel::clearFormKeyFunctions () virtual
Clears the form's list of external functions fired by hotkeys.
clearFormOnEnterFunction()
void cx::cxSearchPanel::clearFormOnEnterFunction () virtual
Removes the onEnter function from the form.
References ENTER.
clearMenu()
void cx::cxSearchPanel::clearMenu (bool pRefresh = false) virtual
Removes the menu items.
Parameters
pRefresh Whether or not to refresh the screen. Defaults to false.
Referenced by onFocusMenu().
clearMenuKeyFunction()
void cx::cxSearchPanel::clearMenuKeyFunction (int pFunctionKey) virtual
Removes a hotkey from the menu so that it will not.
fire a function.
Parameters
pFunctionKey The hotkey to remove
clearMenuKeyFunctions()
void cx::cxSearchPanel::clearMenuKeyFunctions () virtual
Clears the menu's list of external functions fired by hotkeys.
copyCxSearchPanelStuff()
void cx::cxSearchPanel::copyCxSearchPanelStuff (const cxSearchPanel * pThatPanel) protected
Makes a copy of another cxSearchPanel.
Parameters
pThatPanel A pointer to another cxSearchPanel to be copied
References cx::cxWindow::copyCxWinStuff(), cx::cxWindow::getBorderStyle(), cx::cxWindow::getExtStatusWindow(), cx::cxWindow::getExtTitleWindow(), cx::cxWindow::getHotkeyHighlighting(), cx::cxWindow::getMessage(), cx::cxWindow::getStatus(), cx::cxWindow::getTitle(), cx::cxWindow::height(), cx::cxWindow::left(), cx::cxPanel::move(), resize(), cx::cxWindow::setBorderStyle(), cx::cxWindow::setExtStatusWindow(), cx::cxWindow::setExtTitleWindow(), cx::cxWindow::setHotkeyHighlighting(), cx::cxWindow::setMessage(), cx::cxWindow::setStatus(), cx::cxWindow::setTitle(), cx::cxPanel::top(), and cx::cxWindow::width().
cxTypeStr()
string cx::cxSearchPanel::cxTypeStr () const override virtual
Returns the name of the cxWidgets class ("cxSearchPanel").
Returns
The name of the cxWidgets class ("cxSearchPanel")
Reimplemented from cx::cxPanel.
formHasKeyFunction()
bool cx::cxSearchPanel::formHasKeyFunction (int pFunctionKey) const virtual
Returns whether the form has a function hotkey set up to.
run a function.
Parameters
pFunctionKey The key to look for
Returns
Whether or not the form has pFunctionKey set up to run a function.
getForm()
const std::shared_ptr< cxForm > & cx::cxSearchPanel::getForm () const
Returns a pointer to the cxForm on the panel.
Returns
A pointer to the cxForm on the panel
Referenced by cxSearchPanelResize(), onFocusMenu(), and searchPanelOnFocus().
getMenu()
const std::shared_ptr< cxMenu > & cx::cxSearchPanel::getMenu () const
Returns a pointer to the cxMenu on the panel.
Returns
A pointer to the cxMenu on the panel
Referenced by cxSearchPanelResize(), formOnEnter(), menuOnEnter(), onFocusForm(), onFocusMenu(), onLeaveMenu(), storeSearch(), and storeSearchFormOnEnter().
getSelectedItem()
string cx::cxSearchPanel::getSelectedItem (bool pDisplayText = true) const virtual
Returns text of the item selected from the menu, if there was.
one. If not, this will return a blank string.
Parameters
pDisplayText If true (default), this will return the text displayed on the menu for the item. If false, this will return the alternate text for the item.
Returns
The text of the item selected from the menu
Referenced by cxSearchPanelTest(), and storeSearch().
itemWasSelected()
bool cx::cxSearchPanel::itemWasSelected () const virtual
Returns whether or not an item was selected from the menu.
Returns
Whether or not an item was selected from the menu
Referenced by cxSearchPanelTest().
menuHasKeyFunction()
bool cx::cxSearchPanel::menuHasKeyFunction (int pFunctionKey) const virtual
Returns whether the menu has a function hotkey set up to.
run a function.
Parameters
pFunctionKey The key to look for
Returns
Whether or not the menu has pFunctionKey set up to run a function.
resize()
void cx::cxSearchPanel::resize (int pNewHeight, int pNewWidth, bool pRefresh = true) override virtual
Changes the width and height, and re-sizes the form and menu.
accordingly.
Parameters
pNewHeight The new height
pNewWidth The new width
pRefresh Whether or not to refresh the window (defaults to true)
Reimplemented from cx::cxWindow.
References cx::height(), cx::cxWindow::resize(), and cx::width().
Referenced by copyCxSearchPanelStuff(), and cxSearchPanelResize().
setFormCurrent()
bool cx::cxSearchPanel::setFormCurrent () virtual
Makes the form be the current window.
Returns
true if it succeeded, or false if not
References cx::cxPanel::setCurrentWindow().
setFormHeight()
void cx::cxSearchPanel::setFormHeight (int pNewHeight, bool pRefresh = true) virtual
Sets the form's height. The menu will also be re-sized accordingly.
to appear directly underneath the form.
Parameters
pNewHeight The new height for the form
pRefresh Whether or not to refresh the screen. Defaults to true.
References cx::height().
Referenced by cxSearchPanelResize(), and storeSearch().
setFormKeyFunction() [1/3]
bool cx::cxSearchPanel::setFormKeyFunction (int pFunctionKey, funcPtr0 pFunction, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) virtual
Adds a function to the form to call when the user presses some.
key.
Parameters
pFunctionKey An int representing a function key
pFunction The function to be run - Must have signature string func()
pUseReturnVal Whether or not to use the function's return value (not used by cxForm, but could be useful for deriving classes - this is here so that setKeyFunction() in cxWindow will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the form after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
setFormKeyFunction() [2/3]
bool cx::cxSearchPanel::setFormKeyFunction (int pFunctionKey, funcPtr2 pFunction, void * p1, void * p2, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) virtual
Adds a function to the form to call when the user presses some.
key.
Parameters
pFunctionKey An int representing a function key
pFunction The function to be run - Must have signature string func(void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxForm, but could be useful for deriving classes - this is here so that setKeyFunction() in cxWindow will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the form after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
setFormKeyFunction() [3/3]
bool cx::cxSearchPanel::setFormKeyFunction (int pFunctionKey, funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) virtual
Adds a function to the form to call when the user presses some.
key. Note that functions added with this method take precedence
over functions with 2 void parameters.
Parameters
pFunctionKey An int representing a function key
pFunction The function to be run - Must have signature string func(void*, void*, void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
p3 Pointer to the 3rd parameter to be used for the function
p4 Pointer to the 4th parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxForm, but could be useful for deriving classes - this is here so that setKeyFunction() in cxWindow will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the form after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
setFormOnEnterFunction() [1/3]
bool cx::cxSearchPanel::setFormOnEnterFunction (funcPtr0 pFunction) virtual
Sets a function to be called when the enter key is pressed on.
the form.
Parameters
pFunction The function to call - Must have this signature: string func()
Returns
True if the key & function was added or false if not
References ENTER.
setFormOnEnterFunction() [2/3]
bool cx::cxSearchPanel::setFormOnEnterFunction (funcPtr2 pFunction, void * p1, void * p2) virtual
Sets a function to be called when the enter key is pressed on.
the form.
Parameters
pFunction The function to call - Must have this signature: string func(void*, void*)
p1 The 1st parameter to the function (pointer)
p2 The 2nd parameter to the function (pointer)
Returns
True if the key & function was added or false if not
References ENTER.
setFormOnEnterFunction() [3/3]
bool cx::cxSearchPanel::setFormOnEnterFunction (funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4) virtual
Sets a function to be called when the enter key is pressed on.
the form.
Parameters
pFunction The function to call - Must have this signature: string func(void*, void*, void*, void*)
p1 The 1st parameter to the function (pointer)
p2 The 2nd parameter to the function (pointer)
p3 The 3rd parameter to the function (pointer)
p4 The 4th parameter to the function (pointer)
Returns
True if the key & function was added or false if not
References ENTER.
Referenced by cxSearchPanelTest(), and storeSearch().
setFormOnFocusFunction() [1/3]
void cx::cxSearchPanel::setFormOnFocusFunction (funcPtr0 pFuncPtr, bool pUseVal = false, bool pExitAfterRun = false)
Sets the onFocus funtion for the form.
Parameters
pFuncPtr A pointer to the function - Must have the signature string someFunc().
pUseVal Whether or not the function's return value should be set as the value in the field (defaults to false)
pExitAfterRun Whether or not the form should exit after the function runs (defaults to false; if true, the input loop won't be started).
setFormOnFocusFunction() [2/3]
void cx::cxSearchPanel::setFormOnFocusFunction (funcPtr2 pFuncPtr, void * p1, void * p2, bool pUseVal = false, bool pExitAfterRun = false)
Sets the onFocus funtion for the form.
Parameters
pFuncPtr A pointer to the function - Must have the signature string someFunc(void*, void*).
p1 A pointer to the first argument
p2 A pointer to the 2nd argument
pUseVal Whether or not the function's return value should be set as the value in the field (defaults to false)
pExitAfterRun Whether or not the form should exit after the function runs (defaults to false; if true, the input loop won't be started).
setFormOnFocusFunction() [3/3]
void cx::cxSearchPanel::setFormOnFocusFunction (funcPtr4 pFuncPtr, void * p1, void * p2, void * p3, void * p4, bool pUseVal = false, bool pExitAfterRun = false)
Sets the onFocus funtion for the form.
Parameters
pFuncPtr A pointer to the function - Must have the signature string someFunc(void*, void*, void*, void*).
p1 A pointer to the first argument
p2 A pointer to the 2nd argument
p3 A pointer to the 3rd argument
p4 A pointer to the 4th argument
pUseVal Whether or not the function's return value should be set as the value in the field (defaults to false)
pExitAfterRun Whether or not the form should exit after the function runs (defaults to false; if true, the input loop won't be started).
Referenced by cxSearchPanelResize(), and cxSearchPanelTest().
setFormOnLeaveFunction() [1/3]
void cx::cxSearchPanel::setFormOnLeaveFunction (funcPtr0 pFuncPtr)
Sets the onLeave function for the form.
Parameters
pFuncPtr A pointer to the function - Must have the signature string someFunc(void*, void*).
setFormOnLeaveFunction() [2/3]
void cx::cxSearchPanel::setFormOnLeaveFunction (funcPtr2 pFuncPtr, void * p1, void * p2)
Sets the onLeave function for the form.
Parameters
pFuncPtr A pointer to the function - Must have the signature string someFunc(void*, void*).
p1 A pointer to the first argument
p2 A pointer to the 2nd argument
setFormOnLeaveFunction() [3/3]
void cx::cxSearchPanel::setFormOnLeaveFunction (funcPtr4 pFuncPtr, void * p1, void * p2, void * p3, void * p4)
Sets the onLeave function for the form.
Parameters
pFuncPtr A pointer to the function - Must have the signature string someFunc(void*, void*, void*, void*).
p1 A pointer to the first argument
p2 A pointer to the 2nd argument
p3 A pointer to the 3rd argument
p4 A pointer to the 4th argument
Referenced by cxSearchPanelResize(), and cxSearchPanelTest().
setMenuCurrent()
bool cx::cxSearchPanel::setMenuCurrent () virtual
Makes the menu be the current window.
Returns
true if it succeeded, or false if not
References cx::cxPanel::setCurrentWindow().
setMenuHeight()
void cx::cxSearchPanel::setMenuHeight (int pNewHeight, bool pRefresh = true) virtual
Sets the menu's height. The form will also be re-sized accordingly.
to appear directly above the menu.
Parameters
pNewHeight The new height for the menu
pRefresh Whether or not to refresh the screen. Defaults to true.
References cx::height().
Referenced by cxSearchPanelResize().
setMenuKeyFunction() [1/3]
bool cx::cxSearchPanel::setMenuKeyFunction (int pFunctionKey, funcPtr0 pFunction, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) virtual
Adds a function to the menu to call when the user presses some.
key.
Parameters
pFunctionKey An int representing a function key
pFunction The function to be run - Must have signature string func()
pUseReturnVal Whether or not to use the function's return value (not used by cxMenu, but could be useful for deriving classes - this is here so that setKeyFunction() in cxWindow will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the menu after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
setMenuKeyFunction() [2/3]
bool cx::cxSearchPanel::setMenuKeyFunction (int pFunctionKey, funcPtr2 pFunction, void * p1, void * p2, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) virtual
Adds a function to the menu to call when the user presses some.
key.
Parameters
pFunctionKey An int representing a function key
pFunction The function to be run - Must have signature string func(void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxMenu, but could be useful for deriving classes - this is here so that setKeyFunction() in cxWindow will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the menu after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
setMenuKeyFunction() [3/3]
bool cx::cxSearchPanel::setMenuKeyFunction (int pFunctionKey, funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) virtual
Adds a function to the menu to call when the user presses some.
key. Note that functions added with this method take precedence
over functions with 2 void parameters.
Parameters
pFunctionKey An int representing a function key
pFunction The function to be run - Must have signature string func(void*, void*, void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
p3 Pointer to the 3rd parameter to be used for the function
p4 Pointer to the 4th parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxMenu, but could be useful for deriving classes - this is here so that setKeyFunction() in cxWindow will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the menu after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
setMenuOnFocusFunction() [1/3]
void cx::cxSearchPanel::setMenuOnFocusFunction (funcPtr0 pFunction, bool pUseVal = false, bool pExitAfterRun = false) virtual
Sets the onFocus function for the menu.
Parameters
pFunction The function to be run - Must have this signature: string func()
pUseVal
pExitAfterRun Whether or not the menu should exit after the function finishes running (defaults to false).
setMenuOnFocusFunction() [2/3]
void cx::cxSearchPanel::setMenuOnFocusFunction (funcPtr2 pFunction, void * p1, void * p2, bool pUseVal = false, bool pExitAfterRun = false) virtual
Sets the onFocus function for the menu.
Parameters
pFunction The function to be run - Must have this signature: string func(void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
pUseVal
pExitAfterRun Whether or not the menu should exit after the function finishes running (defaults to false).
setMenuOnFocusFunction() [3/3]
void cx::cxSearchPanel::setMenuOnFocusFunction (funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4, bool pUseVal = false, bool pExitAfterRun = false) virtual
Sets the onFocus function for the menu.
Parameters
pFunction The function to be run - Must have this signature: string func(void*, void*, void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
p3 Pointer to the 3rd parameter to be used for the function
p4 Pointer to the 4th parameter to be used for the function
pUseVal
pExitAfterRun Whether or not the menu should exit after the function finishes running (defaults to false).
Referenced by cxSearchPanelResize(), and cxSearchPanelTest().
setMenuOnLeaveFunction() [1/3]
void cx::cxSearchPanel::setMenuOnLeaveFunction (funcPtr0 pFunction) virtual
Sets the onLeave function for the menu.
Parameters
pFunction The function to be run - Must have this signature: string func()
setMenuOnLeaveFunction() [2/3]
void cx::cxSearchPanel::setMenuOnLeaveFunction (funcPtr2 pFunction, void * p1, void * p2) virtual
Sets the onLeave function for the menu.
Parameters
pFunction The function to be run - Must have this signature: string func(void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
setMenuOnLeaveFunction() [3/3]
void cx::cxSearchPanel::setMenuOnLeaveFunction (funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4) virtual
Sets the onLeave function for the menu.
Parameters
pFunction The function to be run - Must have this signature: string func(void*, void*, void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
p3 Pointer to the 3rd parameter to be used for the function
p4 Pointer to the 4th parameter to be used for the function
Referenced by cxSearchPanelResize(), and cxSearchPanelTest().
setMenuOnSelectItemFunction() [1/3]
bool cx::cxSearchPanel::setMenuOnSelectItemFunction (funcPtr0 pFunction, bool pExitAfterRun, bool pRunOnLeaveFunction) virtual
Sets a function to run when the user selects an item from the.
menu.
Parameters
pFunction A pointer to the function to run. Must have this signature: string func()
pExitAfterRun Whether or not the menu should exit after the function runs
pRunOnLeaveFunction Whether or not the function should run its onLeave function if it exits after the function runs
Returns
true if the function was set, or false if not
setMenuOnSelectItemFunction() [2/3]
bool cx::cxSearchPanel::setMenuOnSelectItemFunction (funcPtr2 pFunction, void * p1, void * p2, bool pExitAfterRun, bool pRunOnLeaveFunction) virtual
Sets a function to run when the user selects an item from the.
menu.
Parameters
pFunction A pointer to the function to run. Must have this signature: string func(void*, void*)
p1 A pointer to the first parameter to pass to the function
p2 A pointer to the second parameter to pass to the function
pExitAfterRun Whether or not the menu should exit after the function runs
pRunOnLeaveFunction Whether or not the function should run its onLeave function if it exits after the function runs
Returns
true if the function was set, or false if not
setMenuOnSelectItemFunction() [3/3]
bool cx::cxSearchPanel::setMenuOnSelectItemFunction (funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4, bool pExitAfterRun, bool pRunOnLeaveFunction) virtual
Sets a function to run when the user selects an item from the.
menu.
Parameters
pFunction A pointer to the function to run. Must have this signature: string func(void*, void*, void*, void*)
p1 A pointer to the first parameter to pass to the function
p2 A pointer to the second parameter to pass to the function
p3 A pointer to the 3rd parameter to pass to the function
p4 A pointer to the 4th parameter to pass to the function
pExitAfterRun Whether or not the menu should exit after the function runs
pRunOnLeaveFunction Whether or not the function should run its onLeave function if it exits after the function runs
Returns
true if the function was set, or false if not
The documentation for this class was generated from the following files:
/home/erico/projects/cxWidgets/src/cxSearchPanel.h
/home/erico/projects/cxWidgets/src/cxSearchPanel.cpp