cxWidgets: cx::cxMultiForm Class Reference
cx::cxMultiForm Class Reference
Represents a form that can.
#include <cxMultiForm.h>
Public Member Functions
cxMultiForm (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", eBorderStyle pBorderStyle=eBS_SINGLE_LINE, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pAutoExit=false, bool pStacked=false)
cxMultiForm (const cxMultiForm &pThatMultiForm)
virtual ~cxMultiForm ()
cxMultiForm & operator= (const cxMultiForm &pThatMultiForm)
Assignment operator.
virtual std::shared_ptr< cxForm > appendForm (int pRow, int pCol, int pHeight, int pWidth, const std::string &pTitle="", eBorderStyle pBorderStyle=eBS_NOBORDER, bool pStacked=false)
Appends a subform to the form.
virtual bool appendForm (std::shared_ptr< cxForm > &pForm, int pRow, int pCol, bool *pMoved=nullptr)
Appends a subform to the form via a pointer.
virtual bool appendForm (std::shared_ptr< cxForm > &pForm)
Appends a subform to the form via a pointer (without.
virtual std::shared_ptr< cxForm > getForm (unsigned pIndex) const
Returns a pointer to one of the subforms (by index), or.
virtual std::shared_ptr< cxForm > getForm (const std::string &pTitle) const
Returns a pointer to one of the subforms (by title), or.
virtual long show (bool pBringToTop=false, bool pShowSubwindows=true) override
virtual long showModal (bool pShowSelf=true, bool pBringToTop=false, bool pShowSubwindows=true) override
Shows the form and waits for input.
virtual void showAllSubforms (bool pBringToTop=true, bool pSkipCurrentForm=false) const
Shows (refreshes) all inputs.
virtual bool removeSubform (unsigned pIndex)
Removes a subform (by index).
virtual bool removeSubform (const std::string &pTitle)
Removes a subform (by title).
virtual std::string getValue (unsigned pFormIndex, int pInputIndex) const
Gets the value of an input on one of the subforms (by indexes)
virtual std::string getValue (int pIndex) const override
Returns the value associated with a particular input (by index).
virtual std::string getValue (const std::string &pStr, bool pIsLabel=true) const override
Returns the value associated with a particular input (by label or name).
virtual std::string getValue (unsigned pFormIndex, const std::string &pLabel, bool pIsLabel=true) const
Gets the value of an input on one of the subforms (by.
virtual std::string getValue (const std::string &pTitle, int pInputIndex) const
Gets the value of an input on one of the subforms (by.
virtual std::string getValue (const std::string &pTitle, const std::string &pLabel, bool pIsLabel=true) const
Gets the value of an input on one of the subforms (by.
virtual bool setValue (unsigned pFormIndex, int pInputIndex, const std::string &pValue, bool pRefresh=false)
Sets a value of an input on one of the subforms.
virtual bool setValue (unsigned pFormIndex, const std::string &pLabel, const std::string &pValue, bool pIsLabel=true, bool pRefresh=false)
Sets a value of an input on one of the subforms.
virtual bool setValue (const std::string &pTitle, int pInputIndex, const std::string &pValue, bool pRefresh=false)
Sets a value of an input on one of the subforms.
virtual bool setValue (const std::string &pTitle, const std::string &pLabel, const std::string &pValue, bool pIsLabel=true, bool pRefresh=false)
Sets a value of an input on one of the subforms.
virtual bool setValue (int pIndex, const std::string &pValue, bool pRefresh=false) override
virtual bool setValue (const std::string &pLabel, const std::string &pValue, bool pIsLabel=true, bool pRefresh=false) override
size_t numSubforms () const
Returns the number of subforms on the form.
virtual int getLastKey () const override
Returns the last key typed by the user.
bool hasEditableSubforms () const
Returns whether any of the subforms contain.
virtual bool move (int pNewRow, int pNewCol, bool pRefresh=true) override
virtual void hide (bool pHideSubwindows=true) override
Hides the form.
virtual void unhide (bool pUnhideSubwindows=true) override
Un-hides the form.
virtual bool setKeyFunction (int pKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
virtual bool setKeyFunction (int pKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
virtual bool setKeyFunction (int pKey, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
virtual bool setCurrentSubform (int pIndex)
Changes which subform is to have the focus (by index).
virtual bool setCurrentSubform (const std::string &pTitle)
Changes which subform is to have the focus (by title).
virtual bool setCurrentSubformByPtr (const std::shared_ptr< cxForm > &pForm)
Changes which subform is to have the focus (by pointer).
virtual bool setCurrentSubformByPtr (cxForm *pForm)
virtual int getCurrentForm () const
Returns the index of the current form.
virtual int getSubformIndex (const std::shared_ptr< cxForm > &pForm) const
Returns the index of a subform on the.
virtual int getSubformIndex (cxForm *pForm) const
virtual bool hasChanged () const override
Returns whether or not any inputs on the form,.
virtual void setChanged (bool pDataChanged) override
Setter for whether or not data should be considered changed.
virtual void setSubformEnabled (unsigned pIndex, bool pEnabled)
Enables or disables one of the subforms (by index).
virtual void setSubformEnabled (const std::string &pTitle, bool pEnabled)
Enables or disables one of the subforms (by title).
virtual bool subformIsEnabled (unsigned pIndex) const
Returns whether one of the subforms is.
virtual bool subformIsEnabled (const std::string &pTitle) const
Returns whether one of the subforms is.
virtual bool addQuitKey (int pKey, bool pRunOnLeaveFunction=true, bool pOverride=false) override
Adds a key that will cause the form to quit and.
virtual void removeQuitKey (int pKey) override
Removes a quit key (but doesn't work for ESC)
virtual bool addExitKey (int pKey, bool pRunOnLeaveFunction=true, bool pOverride=false) override
Adds a key that will cause the form to quit and.
virtual void removeExitKey (int pKey) override
Removes an exit key.
virtual void setDisableCursorOnShow (bool pDisableCursorOnShow) override
Sets whether the window should disable the cursor.
virtual void clear (bool pRefresh=false) override
Clears the multiForm and all the subforms.
void setAssumeMovingBackwards (bool pAssumeMovingBackwards)
Normally, if the cursor is on the last form when a cxMultiForm.
bool getAssumeMovingBackwards () const
Returns whether it will be assumed that the user is moving.
virtual void setEnabled (bool pEnabled) override
Enables or disables the multiForm. Enabling/disabling a.
virtual std::string cxTypeStr () const override
Returns the name of the cxWidgets class. This can be used to.
Public Member Functions inherited from cx::cxForm
cxForm (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", eBorderStyle pBorderStyle=eBS_SINGLE_LINE, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pAutoExit=false, bool pStacked=false)
cxForm (const cxForm &pThatForm)
virtual ~cxForm ()
virtual std::shared_ptr< cxMultiLineInput > append (int pRow, int pCol, int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputOption=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue=nullptr, int pRightLabelOffset=0, int pRightLabelHeight=1, int pRightLabelWidth=7, bool pShowRightLabel=false, eInputType pInputType=eIT_CXMULTILINEINPUT)
Adds an input to the form. Applies the A_STANDOUT attribute.
virtual std::shared_ptr< cxComboBox > appendComboBox (int pRow, int pCol, int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputOption=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue=nullptr, int pRightLabelOffset=0, int pRightLabelHeight=1, int pRightLabelWidth=7, bool pShowRightLabel=false)
Adds a combo box to the form. Applies the A_STANDOUT attribute.
virtual cxMLInputPtrPair appendPair (int pRow, int pCol, int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputOption=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue1=nullptr, std::string *pExtValue2=nullptr, int pRightLabel1Offset=0, int pRightLabel1Height=1, int pRightLabel1Width=7, bool pShowRightLabel1=false, int pRightLabel2Offset=0, int pRightLabel2Height=1, int pRightLabel2Width=7, bool pShowRightLabel2=false, eInputType pInput1Type=eIT_CXMULTILINEINPUT, eInputType pInput2Type=eIT_CXMULTILINEINPUT)
Appends a pair of inputs to a form, one to the right of the.
virtual cxComboBoxPtrPair appendComboBoxPair (int pRow, int pCol, int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputOption=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue1=nullptr, std::string *pExtValue2=nullptr, int pRightLabel1Offset=0, int pRightLabel1Height=1, int pRightLabel1Width=7, bool pShowRightLabel1=false, int pRightLabel2Offset=0, int pRightLabel2Height=1, int pRightLabel2Width=7, bool pShowRightLabel2=false)
Appends a pair of cxComboBoxes to a form, one to the right of.
virtual void appendPair (std::shared_ptr< cxMultiLineInput > &pInput1, std::shared_ptr< cxMultiLineInput > &pInput2, int pRow, int pCol, const std::string &pName="")
Appends 2 inputs to the form, one to the right of the other.
virtual std::shared_ptr< cxMultiLineInput > append (int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputOption=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue=nullptr, int pRightLabelOffset=0, int pRightLabelHeight=1, int pRightLabelWidth=7, bool pShowRightLabel=false, eInputType pInputType=eIT_CXMULTILINEINPUT)
Appends an input to the form below the last item currently in.
virtual std::shared_ptr< cxComboBox > appendComboBox (int pHeight, int pWidth, const std::string &pLabel, const std::string &pValidator="", const std::string &pHelpString="", eInputOptions pInputOption=eINPUT_EDITABLE, const std::string &pName="", std::string *pExtValue=nullptr, int pRightLabelOffset=0, int pRightLabelHeight=1, int pRightLabelWidth=7, bool pShowRightLabel=false)
Appends a combo box to the form below the last.
virtual std::shared_ptr< cxMultiLineInput > append (const cxMultiLineInput &pInput)
Appends a copy of an input to a form.
virtual void append (std::shared_ptr< cxMultiLineInput > &pInput, int pRow, int pCol, bool *pMoved=nullptr)
Appends a cxMultiLineInput to the form via a pointer.
virtual void remove (unsigned int pIndex)
virtual void remove (const std::string &pLabel, bool pIsLabel=true)
virtual void remove (const std::shared_ptr< cxMultiLineInput > &pInput)
virtual void remove (cxMultiLineInput *pInput)
virtual void removeAll ()
Removes all inputs from the form.
virtual void setFieldKeyFunction (const std::string &pLabel, int pFunctionKey, const std::shared_ptr< cxFunction > &pFieldFunction, bool pIsLabel=true)
virtual void setFieldKeyFunction (const std::string &pLabel, int pFunctionKey, funcPtr4 pFieldFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal, bool pExitAfterRun=false, bool pIsLabel=true)
virtual void setFieldKeyFunction (unsigned pIndex, int pFunctionKey, funcPtr4 pFieldFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal, bool pExitAfterRun=false)
virtual void setFieldKeyFunction (const std::string &pLabel, int pFunctionKey, funcPtr2 pFieldFunction, void *p1, void *p2, bool pUseVal, bool pExitAfterRun=false, bool pIsLabel=true)
virtual void setFieldKeyFunction (unsigned int pIndex, int pFunctionKey, const std::shared_ptr< cxFunction > &pFieldFunction)
virtual void setFieldKeyFunction (unsigned int pIndex, int pFunctionKey, funcPtr2 pFieldFunction, void *p1, void *p2, bool pUseVal, bool pExitAfterRun=false)
virtual void setOnFocusFunction (const std::shared_ptr< cxFunction > &pFunction) override
Sets the form window's "on focus" function.
virtual void setOnFocusFunction (const std::string &pLabel, const std::shared_ptr< cxFunction > &pFunction, bool pIsLabel=true)
virtual void setOnFocusFunction (unsigned pIndex, const std::shared_ptr< cxFunction > &pFunction)
virtual void setOnFocusFunction (const std::string &pLabel, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal, bool pIsLabel=true)
virtual void setOnFocusFunction (unsigned pIndex, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal)
virtual void setOnLeaveFunction (const std::shared_ptr< cxFunction > &pFunction) override
Sets the form window's "on leave" function.
virtual void setOnLeaveFunction (const std::string &pLabel, const std::shared_ptr< cxFunction > &pFunction, bool pIsLabel=true)
virtual void setOnLeaveFunction (unsigned pIndex, const std::shared_ptr< cxFunction > &pFunction)
virtual void setOnLeaveFunction (const std::string &pLabel, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pIsLabel=true)
virtual void setOnLeaveFunction (unsigned pIndex, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
virtual void setFieldLabel (unsigned pIndex, const std::string &pLabel)
virtual void setFieldLabel (const std::string &pName, const std::string &pLabel)
virtual void setFieldName (unsigned pIndex, const std::string &pName)
virtual void setFieldName (const std::string &pLabel, const std::string &pName)
Sets a field name (by label)
virtual void enableInputLoop (const std::string &pLabel, bool pDoInputLoop, bool pIsLabel=true)
Enables or disables the input loop for one of the.
virtual void enableInputLoop (unsigned pIndex, bool pDoInputLoop)
Enables or disables the input loop for one of the.
virtual void setAutoExit (bool pAutoExit)
Sets whether the form should automatically exit when the user.
bool getAutoExit () const
Returns the set value of whether the form should exit upon.
virtual void setStartAtFirstInput (bool pStartAtFirstInput)
Sets whether or not to always start at the first editable.
bool getStartAtFirstInput () const
Returns whether or not the form will always start at the first.
void setApplyAttrDefaults (bool pApplyAttrDefaults)
Sets whether to apply the default attributes to the inputs when.
bool getApplyAttrDefaults () const
Returns whether default attributes are applied to new inputs.
virtual bool modalGetsKeypress () const override
Returns whether or not a call to showModal() will wait for a.
size_t numInputs () const
Returns the number of inputs in the form.
virtual std::string getLabel (int pIndex) const
Returns the label of one of the inputs (by index).
virtual std::string getName (int pIndex) const
Returns the name of one of the inputs (by index).
virtual std::string getName (const std::string &pLabel) const
Returns the name of one of the inputs (by label).
virtual std::string getStatus (int pIndex) const
Returns the status text of one of the inputs (by index).
virtual std::string getStatus (const std::string &pLabel, bool pIsLabel=true) const
Returns the status text of one of the inputs (by label/name).
virtual int refreshInput (unsigned pIndex)
virtual int refreshInput (const std::string &pStr, bool pIsLabel=true)
bool setMaskChar (int pIndex, char pMaskChar)
bool setMaskChar (const std::string &pLabel, char pMaskChar, bool pIsLabel=true)
Sets the masking character for an input (by label).
bool getMasked (int pIndex)
bool getMasked (const std::string &pLabel, bool pIsLabel=true)
virtual bool toggleMasking (int pIndex, bool pMasking)
virtual bool toggleMasking (const std::string &pLabel, bool pMasking, bool pIsLabel=true)
Enables/disables masking for an input (by label).
virtual bool setCurrentInput (int pIndex)
Changes which input on the form should have focus (by index).
virtual bool setCurrentInput (const std::string &pLabel, bool pIsLabel=true)
Changes which input on the form should have focus (by label/name).
virtual bool setCurrentInputByPtr (const std::shared_ptr< cxMultiLineInput > &pInput)
Changes which input on the form should have focus (by pointer).
virtual bool setCurrentInputByPtr (const cxMultiLineInput *const pInput)
virtual bool setKeyFunction (int pKey, const std::shared_ptr< cxFunction > &pFunction) override
Sets a function to be called when a key is pressed.
virtual void clearKeyFunction (int pKey) override
Removes a function pointer for a keypress for the form so that it will no.
virtual bool setKeyFunction (int pIndex, int pKey, const std::shared_ptr< cxFunction > &pFunction)
Sets a function to be called when a key is pressed.
virtual bool setKeyFunction (const std::string &pLabel, int pKey, const std::shared_ptr< cxFunction > &pFunction, bool pIsLabel=true)
Sets a function to be called when a key is pressed.
virtual bool setKeyFunction (int pIndex, int pKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal, bool pExitAfterRun, bool pRunOnLeaveFunction, bool pRunValidator)
Adds a function to call when the user presses some key for.
virtual bool setKeyFunction (const std::string &pLabel, int pKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal, bool pExitAfterRun, bool pRunOnLeaveFunction, bool pRunValidator, bool pIsLabel=true)
Adds a function to call when the user presses some key for.
virtual bool setKeyFunction (int pIndex, int pKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseVal, bool pExitAfterRun, bool pRunOnLeaveFunction, bool pRunValidator)
Adds a function to call when the user presses some key for.
virtual bool setKeyFunction (const std::string &pLabel, int pKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseVal, bool pExitAfterRun, bool pRunOnLeaveFunction, bool pRunValidator, bool pIsLabel=true)
Adds a function to call when the user presses some key for.
virtual bool setKeyFunction (int pIndex, int pKey, funcPtr0 pFunction, bool pUseVal, bool pExitAfterRun, bool pRunOnLeaveFunction, bool pRunValidator)
Adds a function to call when the user presses some key for.
virtual bool setKeyFunction (const std::string &pLabel, int pKey, funcPtr0 pFunction, bool pUseVal, bool pExitAfterRun, bool pRunOnLeaveFunction, bool pRunValidator, bool pIsLabel=true)
Adds a function to call when the user presses some key for.
bool allFieldsBlank () const
void setLabelColor (const int &pIndex, e_cxColors pColor)
Sets the color of the label of one of the inputs (by index)
void setLabelColor (const std::string &pLabel, e_cxColors pColor, bool pIsLabel=true)
Sets the color of the label of one of the inputs (by label/name)
void setAllLabelColor (e_cxColors pColor)
Sets the color of the labels on all inputs.
int getLabelColor (const int &pIndex) const
Returns the label color of one of the inputs (by index).
int getLabelColor (const std::string &pLabel, bool pIsLabel=true) const
Returns the label color of one of the inputs (by label/name).
void setValueColor (const int &pIndex, e_cxColors pColor)
Sets the color of the value section of one of the inputs (by index)
void setValueColor (const std::string &pLabel, e_cxColors pColor, bool pIsLabel=true)
Sets the color of the value section of one of the inputs (by label/name)
void setAllValueColor (e_cxColors pColor)
Sets the color of the value section of all inputs on the form.
int getValueColor (const int &pIndex) const
Returns the color of the value section of one of the inputs (by index).
int getValueColor (const std::string &pLabel, bool pIsLabel=true) const
Returns the color of the value section of one of the inputs (by label/name).
void setAllColors (e_cxColors pLabelColor, e_cxColors pValueColor)
Sets the label & value colors of all inputs on the form.
virtual void setColor (e_WidgetItems pItem, e_cxColors pColor) override
Sets the color of one of the window items. For label & value.
int inputTopRow (int pIndex) const
Returns the top row of an input (by index), or -1 if the given.
int inputTopRow (const std::string &pLabel, bool pIslabel=true) const
Returns the top row of an input (by label/name), or -1 if there is no.
int inputLeftCol (int pIndex) const
Returns the left column of an input (by index), or -1 if the given.
int inputLeftCol (const std::string &pLabel, bool pIsLabel=true) const
Returns the left column of an input (by label/name), or -1 if there are.
int inputHeight (int pIndex) const
Returns the height of an input (by index), or -1 if the given index.
int inputHeight (const std::string &pLabel, bool pIsLabel=true) const
Returns the height of an input (by label/name), or -1 if there is no input.
int inputWidth (int pIndex) const
Returns the width of an input (by index), or -1 if the given index.
int inputWidth (const std::string &pLabel, bool pIsLabel=true) const
Returns the width of an input (by label/name), or -1 if there is.
int maxInputLen (int pIndex) const
Returns the maximum length of input accepted by an input (by index),.
int maxInputLen (const std::string &pLabel, bool pIsLabel=true) const
Returns the maximum length of input accepted by an input (by index),.
std::string inputLabel (int pIndex) const
Returns the label of an input at a given index.
std::string inputLabel (const std::string &pName) const
Returns the label of an input.
std::string inputName (int pIndex) const
Returns the name of an input at a given index.
std::string inputName (const std::string &pLabel) const
Returns the name of an input.
virtual void scrollInputs (int pVScrollAmt, int pHScrollAmt, bool pRefresh=false, bool pBringToTop=false)
Scrolls (moves) the inputs in the window.
virtual void toggleCursor (int pIndex, bool pShowCursor)
Toggles the display of the cursor for an input (by index).
virtual void toggleCursor (const std::string &pLabel, bool pShowCursor, bool pIsLabel=true)
Toggles the display of the cursor for an input (by label/name).
virtual void toggleCursor (bool pShowCursor)
Toggles the display of the cursor on all inputs.
std::shared_ptr< cxMultiLineInput > getInput (int pIndex) const
Returns a pointer to an input at a given index, or nullptr if the index.
std::shared_ptr< cxMultiLineInput > getInput (const std::string &pLabel, bool pIsLabel=true) const
Returns a pointer to an input with a given label/name, or.
std::shared_ptr< cxMultiLineInput > getCurrentInput () const
Returns a pointer to the current input. If there are no inputs.
virtual int getInputOption (int pIndex) const
Returns the editability option for an input (by index).
virtual int getInputOption (const std::string &pLabel, bool pIsLabel=true) const
Returns the editability option for an input (by label/name).
virtual void setInputOption (int pIndex, eInputOptions pInputOption, bool pRefresh=true)
Sets the input kind for one of the inputs (by index).
virtual void setInputOption (const std::string &pLabel, eInputOptions pInputOption, bool pIsLabel=true, bool pRefresh=true)
Sets the input kind for one of the inputs (by label/name).
virtual void setAllInputOption (eInputOptions pInputOption, bool pRefresh=true)
Sets the input kind for all inputs on the form.
virtual void setStatus (const std::string &pStatus, bool pRefreshStatus=true) override
Mutator for the status line text. After this method.
virtual void disableCustomStatus (bool pRefreshStatus=true)
Turns off the custom status text set with setStatus.
virtual void setValidatorFunction (int pIndex, const std::shared_ptr< cxFunction > &pFunction)
Sets a validator function to be run before focus is lost for one.
virtual void setValidatorFunction (int pIndex, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets a validator function to be run before focus is lost for one.
virtual void setValidatorFunction (const std::string &pLabel, const std::shared_ptr< cxFunction > &pFunction, bool pIsLabel=true)
Sets a validator function to be run before focus is lost for one.
virtual void setValidatorFunction (const std::string &pLabel, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pIsLabel=true)
Sets a validator function to be run before focus is lost for one.
virtual void showInputsOnBorder (bool pShowInputsOnBorder)
Toggles whether to show inputs if they're on.
virtual void setOnKeyFunction (int pIndex, const std::shared_ptr< cxFunction > &pFunction)
Sets a function to be run whenever a key is pressed in an input (by index).
virtual void setOnKeyFunction (int pIndex, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets a function to be run whenever a key is pressed in an input (by index).
virtual void setOnKeyFunction (const std::string &pLabel, const std::shared_ptr< cxFunction > &pFunction, bool pIsLabel=true)
Sets a function to be run whenever a key is pressed in an.
virtual void setOnKeyFunction (const std::string &pLabel, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pIsLabel=true)
Sets a function to be run whenever a key is pressed in an.
virtual void setOnKeyFunction (int pIndex, funcPtr2 pFunction, void *p1, void *p2)
Sets a function to be run whenever a key is pressed in an input (by index).
virtual void setOnKeyFunction (const std::string &pLabel, funcPtr2 pFunction, void *p1, void *p2, bool pIsLabel=true)
Sets a function to be run whenever a key is pressed in an.
virtual void setOnKeyFunction (int pIndex, funcPtr0 pFunction)
Sets a function to be run whenever a key is pressed in an input (by index).
virtual void setOnKeyFunction (const std::string &pLabel, funcPtr0 pFunction, bool pIsLabel=true)
Sets a function to be run whenever a key is pressed in an.
virtual void setAllOnKeyFunction (const std::shared_ptr< cxFunction > &pFunction)
Sets a function to be run whenever a key is pressed, in all.
virtual void setAllOnKeyFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets a function to be run whenever a key is pressed, in all.
virtual void setAllOnKeyFunction (funcPtr2 pFunction, void *p1, void *p2)
Sets a function to be run whenever a key is pressed, in all.
virtual void setAllOnKeyFunction (funcPtr0 pFunction)
Sets a function to be run whenever a key is pressed, in all.
virtual void toggleOnKeyFunction (int pIndex, bool pRunOnKeyFunction)
Sets whether or not an onKey function should run for one of the.
virtual void toggleOnKeyFunction (const std::string &pLabel, bool pRunOnKeyFunction, bool pIsLabel=true)
Sets whether or not an onKey function should run for one of the.
virtual void toggleAllOnKeyFunction (bool pRunOnKeyFunction)
Sets whether or not the onKey function for all inputs should.
virtual bool onKeyFunctionEnabled (int pIndex) const
Returns whether the onKey function is enabled for one of the.
virtual bool onKeyFunctionEnabled (const std::string &pLabel, bool pIsLabel=true) const
Returns whether the onKey function is enabled for one of the.
cxForm & operator= (const cxForm &pThatForm)
Assignment operator.
virtual bool addInputJumpKey (int pKey, int pIndex)
virtual bool addInputJumpKey (int pKey, const std::string &pLabel, bool pIsLabel=true)
Adds a hotkey for the form that will cause the.
virtual int getCurrentInputIndex () const
Returns the index of the input that currently has focus.
virtual std::string getCurrentInputLabel () const
Returns the label of the input that currently has focus.
virtual std::string getCurrentInputName () const
Returns the name of the input that currently has focus.
virtual int getInputIndex (const std::string &pLabel, bool pIsLabel=true) const
Returns the index of an input, based on its label or name.
virtual int getInputIndex (const std::shared_ptr< cxMultiLineInput > &pInput) const
Returns the index of an input based on a pointer. May.
virtual int getInputIndex (const cxMultiLineInput *pInput) const
virtual void setInputJumpKey (int pInputJumpKey)
Sets the hotkey to be used to bring up the menu to choose.
virtual int getInputJumpKey () const
Returns which key is being used as the jump hotkey.
virtual void setCanBeEditable (int pIndex, bool pCanBeEditable)
Sets whether an input can be set editable (by index). If.
virtual void setCanBeEditable (const std::string &pLabel, bool pCanBeEditable, bool pIsLabel=true)
Sets whether an input can be set editable (by label/name). For.
virtual void setAllCanBeEditable (bool pCanBeEditable)
Sets the ability of all inputs to be able to be editable.
virtual bool canBeEditable (int pIndex) const
Returns whether or not an input can be set editable.
virtual bool canBeEditable (const std::string &pLabel, bool pIsLabel=true) const
Returns whether or not an input can be set editable.
virtual bool anyInputsCanBeEditable () const
Returns whether any input on the form (at least 1) can be set editable.
virtual void setAllowQuit (bool pAllowQuit)
Sets whether the form should allow the user to quit.
virtual bool getAllowQuit () const
Returns whether the user is able to quit out of the form.
virtual void setAllowExit (bool pAllowExit)
Sets whether the form should allow the user to exit.
virtual bool getAllowExit () const
Returns whether the user is able to exit out of the form.
virtual void setOnFocusFunction (funcPtr4 pFuncPtr, void *p1, void *p2, void *p3, void *p4, bool pUseVal=false, bool pExitAfterRun=false) override
Sets a function to be run when focus is gained (at.
virtual void setOnFocusFunction (funcPtr2 pFuncPtr, void *p1, void *p2, bool pUseVal=false, bool pExitAfterRun=false) override
Sets a function to be run when focus is gained (at.
virtual void setOnFocusFunction (funcPtr0 pFuncPtr, bool pUseVal=false, bool pExitAfterRun=false) override
Sets a function to be run when focus is gained (at.
virtual void setLoopStartFunction (const std::shared_ptr< cxFunction > &pFuncPtr)
Sets a function to be run at the start of each.
virtual void setLoopEndFunction (const std::shared_ptr< cxFunction > &pFuncPtr)
Sets a function to be run at the end of each.
virtual void setOnLeaveFunction (funcPtr4 pFuncPtr, void *p1, void *p2, void *p3, void *p4) override
Sets a function to be run when focus is lost.
virtual void setOnLeaveFunction (funcPtr2 pFuncPtr, void *p1, void *p2) override
Sets a function to be run when focus is lost.
virtual void setOnLeaveFunction (funcPtr0 pFuncPtr) override
Sets a function to be run when focus is lost.
virtual void showAllInputs (bool pBringToTop=true, bool pSkipCurrentInput=false) const
Shows (refreshes) all inputs.
virtual bool formKeyIsSet (int pKey) const
Returns whether a key is set as a form function.
virtual bool isStacked () const
Returns whether or not the form is in 'stacked'.
virtual bool getExitOnLeaveFirst () const
Returns whether the form is set to exit its showModal() when.
virtual void setExitOnLeaveFirst (bool pExitOnLeaveFirst)
Sets whether the form should exit when the user leaves.
virtual bool hasEditableInputs () const
Returns whether the form has any inputs that are.
virtual int firstEditableInput () const
Returns the index of the first editable input in.
virtual int lastEditableInput () const
Returns the index of the last editable input in.
virtual void bringToTop (bool pRefresh=true) override
Brings the window to the top.
virtual void trapNonAssignedFKeys (bool pTrapNonAssignedFKeys)
Sets whether non-assigned function keys should.
cxMultiForm * getParentMultiForm () const
Returns the parent cxMultiForm pointer.
virtual void setParentMultiForm (cxMultiForm *pParentMultiForm)
Sets the parent cxMultiForm that this cxForm is associated with.
virtual bool runLoopStartFunction ()
Runs the loop start function, if it's set.
virtual bool runLoopEndFunction ()
Runs the loop end function, if it's set.
virtual int maxValueLen (int pIndex) const
Returns the maximum length of the value that may be set for an.
virtual int maxValueLen (const std::string &pLabel, bool pIsLabel=true)
Returns the maximum length of the value that may be set for an.
virtual bool isEditable (int pIndex) const
Returns whether one of the inputs on.
virtual bool isEditable (const std::string &pLabel, bool pIsLabel=true) const
Returns whether one of the inputs on.
virtual void setWaitForInputIfEmpty (bool pWaitForInputIfEmpty)
Toggles whether or not the form should wait for.
virtual bool getWaitForInputIfEmpty () const
Returns whether or not the form will wait for.
virtual void clearInputs (bool pRefresh=false, bool pOnlyEditable=false)
Clears the values of all the inputs on the form.
virtual void getValues (std::map< std::string, std::string > &pValues, bool pUseLabels=true, bool pSkipBlankIDs=false) const
Gets the values from the form in the form of a map of input.
virtual void setValues (const std::map< std::string, std::string > &pValues, bool pUseLabels=true, bool pRefresh=false, bool pDisableValidatorFunctions=false)
Sets the values in the form with a map of input labels/names.
virtual void useInputStatus (bool pUseInputStatus)
Toggles whether or not to use the status text of the inputs.
virtual bool hasInput (const std::string &pStr, bool pIsLabel=true) const
Returns whether or not the form has an input with a given.
virtual cxWindow * getParent () const override
Returns a pointer to the parent window. If the cxForm.
virtual void addAttr (e_WidgetItems pItem, attr_t pAttr) override
Returns the index of the next editable input after a given.
virtual void setAttr (e_WidgetItems pItem, attr_t pAttr) override
Sets the ncurses attribute to use for one of the items in the.
virtual void removeAttr (e_WidgetItems pItem, attr_t pAttr) override
Removes an ncurses attribute from one of the item lists. For.
virtual void removeAttrs (e_WidgetItems pItem) override
Removes all attributes for a given window item. For eLABEL,.
virtual void getAttrs (e_WidgetItems pItem, std::set< attr_t > &pAttrs) const override
Returns the set of ncurses attributes for a given item.
virtual void getNavKeys (std::set< int > &pNavKeys) const
Gathers a set of keys considered to be "navigational" keys from.
virtual void getNavKeyStrings (std::set< std::string > &pNavKeyStrings) const
Creates a set of string representations of keys considered to.
virtual bool hasNavKey (int pKey) const
Returns whether at least one of the inputs on the form has.
virtual void setLastKey (int pLastKey) override
Sets the last keypress.
virtual void quitNow () override
This causes the form to exit its input loop with a code of.
virtual void exitNow () override
This causes the form to exit its input loop with a code of.
virtual void setExtendedHelpKey (int pKey)
Sets a single key to use to display extended help for all.
virtual void addExtendedHelpKey (int pKey)
Adds an additional key to be used to display the extended.
virtual std::set< int > getExtendedHelpKeys () const
Returns the keys used to display extended help for the inputs.
std::string getExtendedHelpKeyStrings () const
Returns a comma-separated list of strings representing the.
virtual void clearExtendedHelpKeys ()
Removes all extended help keys.
virtual void setUseExtendedHelpKeys (bool pUseExtendedHelpKeys)
Sets whether or not to use the extended help keys.
virtual bool getUseExtendedHelpKeys () const
Returns whether or not the extended help keys are enabled.
virtual std::string getExtendedHelp (int pIndex) const
Gets the extended help string from one of the inputs (by.
virtual std::string getExtendedHelp (const std::string &pIDStr, bool pIsLabel=true) const
Returns the extended help string from one of the inputs (by.
virtual void setExtendedHelp (int pIndex, const std::string &pExtendedHelp)
Sets the extended help for one of the inputs (by index).
virtual void setExtendedHelp (const std::string &pIDStr, const std::string &pExtendedHelp, bool pIsLabel=true)
Sets the extended help for one of the inputs (by label/name).
virtual void validateOnJumpKey (int pIndex, bool pValidate)
Sets whether or not the validator function should run for an.
virtual void validateOnJumpKey (const std::string &pID, bool pValidate, bool pIsLabel=true)
Sets whether or not the validator function should run for an.
virtual void allValidateOnJumpKey (bool pValidate)
Sets whether or not the validator function should run for all.
virtual bool swap (int pInput1Index, int pInput2Index)
Swaps the order of 2 inputs (by index). If both indexes.
virtual bool swap (std::shared_ptr< cxWindow > &pInput1, std::shared_ptr< cxWindow > &pInput2)
Swaps the order of 2 inputs (by pointer). If both pointers.
std::string getName () const
std::string getStatus () const
Accessor for the status line text.
Public Member Functions inherited from cx::cxWindow
cxWindow (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", const std::string &pMessage="", const std::string &pStatus="", eBorderStyle pBorderStyle=eBS_SINGLE_LINE, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Default constructor.
cxWindow (cxWindow *pParentWindow, int pRow, int pCol, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor.
cxWindow (cxWindow *pParentWindow, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, int pHeight, int pWidth, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, const std::string &pStatus, int pHeight, int pWidth, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, eHPosition pHPosition, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Lets you specify the horizontal position.
cxWindow (const cxWindow &pThatWindow)
Copy constructor.
virtual ~cxWindow ()
virtual void centerHoriz (bool pRefresh=true)
Centers the window horizontally on the screen.
virtual void alignHoriz (eHPosition pPosition, bool pRefresh=true)
Aligns the window horizontally on the screen.
virtual void centerVert (bool pRefresh=true)
Centers the window vertically on the screen.
virtual void alignVert (eVPosition pPosition, bool pRefresh=true)
Aligns the window vertically on the screen.
virtual void center (bool pRefresh=true)
Centers the window on the screen.
virtual std::string getTitle () const
Accessor for title text - Returns the first string in the.
virtual void setTitle (const std::string &pTitle, bool pRefreshTitle=true)
Setter for the title text - This sets the first string in the.
std::string getStatus () const
Accessor for the status line text.
std::string getMessage () const
Returns the message that appears in the window, concatenating all message lines together.
virtual void setMessage (const std::string &pMessage)
Sets the text that appears within the window.
virtual void addMessageLineBelow (const std::string &pLine)
Adds a line to the message to be displayed in the window,.
virtual void addMessageLinesBelow (const std::vector< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLinesBelow (const std::list< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLinesBelow (const std::deque< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLineAbove (const std::string &pLine)
Adds a line to the message to be displayed in the window,.
virtual void addMessageLinesAbove (const std::vector< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void addMessageLinesAbove (const std::list< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void addMessageLinesAbove (const std::deque< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void setMessageLines (const std::vector< std::string > &pLines)
Sets the message lines in the window.
virtual void setMessageLines (const std::list< std::string > &pLines)
Sets the message lines in the window.
virtual void setMessageLines (const std::deque< std::string > &pLines)
Sets the message lines in the window.
virtual void removeMessageLine (unsigned pIndex)
Removes a line from the text inside the window (by index).
virtual void setMessageLine (unsigned pIndex, const std::string &pLine)
Modifies one of the lines displayed in the window.
void setHorizTitleAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the title text.
eHPosition getHorizTitleAlignment () const
Accessor for the title text alignment.
void setHorizMessageAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the message text.
eHPosition getHorizMessageAlignment () const
Accessor for the horizontal message text alignment.
void setHorizStatusAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the status text.
eHPosition getHorizStatusAlignment () const
Accessor for the horizontal status text alignment.
void setVerticalMessageAlignment (eVPosition pVAlignment)
Sets the vertical alignment of the message text.
eVPosition getVerticalMessageAlignment () const
Accessor for the vertical message text alignment.
void setExtTitleWindow (cxWindow *pWindow, bool pRefreshTitle=true)
Sets an external cxWindow object to be used for the title, rather.
cxWindow * getExtTitleWindow () const
Accessor for the external title window pointer.
void setExtStatusWindow (cxWindow *pWindow, bool pRefreshStatus=true)
Sets an external cxWindow object to be used for status, rather.
cxWindow * getExtStatusWindow () const
Accessor for the external status window pointer.
bool isHidden () const
Returns whether or not the window is hidden.
virtual long setFocus (bool pShowSelf=true, bool pBringToTop=true, bool pShowSubwindows=true)
Alias for showModal()
virtual void setFocusColors ()
Turns on the ncurses attribute A_REVERSE for the window to.
virtual void setFocusColors (attr_t pAttr)
Turns on the ncurses attribute pAttr for the window to.
virtual void unSetFocusColors ()
Disables focus for this window and unhighlights the message.
virtual void unSetFocusColors (attr_t pAttr)
Disables focus for this window and un-highlights the message (using pAttr)
virtual void erase (bool pEraseSubwindows=true)
Erases the window.
virtual void bringToBottom (bool pRefresh=false)
Puts the window on the bottom of all other windows.
virtual bool isOnTop () const
Returns whether the window is on top of all other windows.
virtual bool isOnBottom () const
Returns whether the window is on the bottom of all other windows.
virtual bool isAbove (const cxWindow &pThatWindow) const
Returns whether the window is above another window.
virtual bool isBelow (const cxWindow &pThatWindow) const
Returns whether a window is below another window.
void touchWindow ()
Marks the window's entire content as dirty so that the next.
virtual void drawBorder (int pRow, int pCol, int pHeight, int pWidth, bool pTop=true, bool pBottom=true, bool pLeft=true, bool pRight=true)
Draws the border (based on the border style)
virtual void drawBorder (int pHeight, int pWidth)
Draws a box in the window.
virtual void drawBorder ()
Draws a box for the window border.
virtual int top () const
Returns the top row of the window.
virtual int centerRow () const
Returns the center row of the window.
virtual int bottom () const
Returns the bottom row of the window.
virtual int left () const
Returns the left column of the window.
virtual int centerCol () const
Returns the center column of the window.
virtual int right () const
Returns the right column of the window.
virtual int width (int pWidth)
Changes the width of the window.
virtual int width () const
Returns the width of the window.
virtual int height (int pHeight)
Changes the height of the window.
virtual int height () const
Returns the height of the window.
virtual void getRect (int &pTop, int &pLeft, int &pBottom, int &pRight)
Returns the coordinates of the rectangle defining the window.
virtual bool pointIsInWindow (int pY, int pX) const
Returns whether a screen location is in the window (including.
virtual bool pointIsInTitle (int pY, int pX) const
Returns whether a screen location is in the title of the window.
virtual void getSize (int &pHeight, int &pWidth)
Returns the height & width of the window.
virtual void resize (int pNewHeight, int pNewWidth, bool pRefresh=true)
Changes the window's width and height. The window's upper-left.
virtual bool moveRelative (int pVerticalOffset, int pHorizOffset, bool pRefresh=true)
Changes the window's position via vertical & horizontal offsets.
unsigned numSubWindows ()
Returns the number of subwindows in this window.
void setSubWinMessage (unsigned pIndex, const std::string &pMessage)
Sets the message of one of the subwindows (by index).
void setSubWinMessage (const std::string &pTitle, const std::string &pMessage)
Sets the message of one of the subwindows (by title).
virtual bool hasFocus () const
Returns true if window has focus, false otherwise.
virtual void setBorderStyle (eBorderStyle pBorderStyle)
Sets the border style.
eBorderStyle getBorderStyle () const
Returns the border style.
bool hasBorder () const
Does this window have a border?
void setParent (cxWindow *pNewParent)
Changes the pointer to the parent window; changes the parent window.
virtual void dump (std::string &pResult)
Returns a string containing all the characters.
virtual void showSubwindows (bool pBringToTop=true, bool pShowSubwindows=true)
Shows the subwindows for the window.
cxWindow & operator= (const cxWindow &pThatWindow)
Assignment operator.
virtual void writeText (int pRow, int pCol, const std::string &pText, bool pRefresh=true)
Writes text on the window. Note that the text is not permanant, so.
virtual void setHotkeyHighlighting (bool pHotkeyHighlighting)
Enables/disables the use of hotkey attributes when writing the message.
bool getHotkeyHighlighting () const
Returns whether hotkey attributes are used when writing the message.
virtual bool isEnabled () const
Returns whether or not the window is enabled.
virtual bool getDisableCursorOnShow () const
Returns whether or not the window will disable.
virtual bool getExitOnMouseOutside () const
Returns whether the window exits its modal input loop when.
virtual void setExitOnMouseOutside (bool pExitOnMouseOutside)
Sets whether the window should exit its modal input loop.
virtual bool lastKeyWasMouseEvt () const
Returns whether or not the last keypress was a mouse event.
virtual void getLastMouseEvtCoords (int &pY, int &pX)
Returns the coordinates of the last mouse event in the window.
virtual bool getChangeColorsOnFocus () const
Returns whether the window will change.
virtual void setChangeColorsOnFocus (bool pChangeColorsOnFocus)
Sets whether colors should change when focus.
virtual bool runOnFocusFunction (std::string *pFunctionRetval=nullptr)
Runs the onFocus function, if it's set.
virtual bool runOnLeaveFunction (std::string *pFunctionRetval=nullptr)
Runs the onLeave function, if it's set. However, if the last.
virtual void toggleOnFocusFunction (bool pRunOnFocus)
Sets whether or not the onFocus function should run.
virtual void toggleOnLeaveFunction (bool pRunOnLeave)
Sets whether or not the onLeave function should run.
virtual bool onFocusFunctionEnabled () const
Returns whether or not the onFocus function is set to run.
virtual bool onLeaveFunctionEnabled () const
Returns whether or not the onLeave function is set to run.
virtual const std::shared_ptr< cxFunction > & getOnFocusFunction () const
Accessor for the onFocus function.
virtual const std::shared_ptr< cxFunction > & getOnLeaveFunction () const
Accessor for the onLeave function.
virtual bool isModal () const
Returns whether or not the window is currently.
virtual void clearKeyFunctionByPtr (funcPtr4 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctionByPtr (funcPtr2 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctionByPtr (funcPtr0 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctions ()
Clears the list of external functions fired by hotkeys.
virtual bool hasKeyFunction (int pKey) const
Returns whether an external function exists for a keypress.
virtual bool setMouseFunction (int pMouseState, const std::shared_ptr< cxFunction > &pFunction)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state. This.
virtual void clearMouseFunction (int pMouseState)
Removes a function pointer for a mouse event so that it will.
virtual void clearMouseFunctions ()
Clears the list of external functions fired by mouse events.
virtual bool hasMouseFunction (int pMouseState) const
Returns whether an external function exists for a mouse event.
std::map< int, std::shared_ptr< cxFunction > >::iterator keyFunctions_begin ()
Returns a begin iterator to the map of cxFunction pointers.
std::map< int, std::shared_ptr< cxFunction > >::iterator keyFunctions_end ()
Returns an end iterator to the map of cxFunction pointers.
virtual void getFunctionKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual void getFunctionKeys (std::vector< int > &pKeys) const
Populates a collection with integers representing the keys.
virtual void setShowSubwinsForward (bool pShowSubwinsForward)
Toggles the order in which subwindows will be shown.
virtual bool getShowSubwinsForward () const
Returns whether or not the subwindows will be shown.
virtual void setShowSelfBeforeSubwins (bool pShowSelfBeforeSubwins)
Sets whether the window will show itself before.
virtual bool getShowSelfBeforeSubwins () const
Returns whether or not the window will show itself before.
virtual long getReturnCode () const
Returns the return code set by the last call to.
virtual bool addTitleString (int pHPos, const std::string &pStr, bool pRefreshTitle=false)
Adds/sets a string to appear in the title at.
virtual std::string getTitleString (int pHPos) const
Returns the title string set at a given horizontal position.
virtual std::map< int, std::string > getTitleStrings () const
Returns the map of title strings for the window.
virtual void getTitleStrings (std::map< int, std::string > &pTitleStrings) const
Returns the map of title strings for the window (using an.
virtual void setTitleStrings (const std::map< int, std::string > &pTitleStrings)
Sets all the title strings via a map of horizontal.
virtual void removeTitleString (int pHPos)
Removes a title string at a given horizontal position.
virtual void removeTitleStrings ()
Removes all title strings.
virtual bool addStatusString (int pHPos, const std::string &pStr, bool pRefreshStatus=false)
Adds/sets a string to appear in the status line at.
virtual std::string getStatusString (int pHPos) const
Returns the status string set at a given horizontal position.
virtual std::map< int, std::string > getStatusStrings () const
Returns the map of status strings for the window.
virtual void getStatusStrings (std::map< int, std::string > &pStatusStrings) const
Returns the map of status strings for the window (using an.
virtual void setStatusStrings (const std::map< int, std::string > &pStatusStrings)
Sets all the status strings via a map of horizontal.
virtual void removeStatusString (int pHPos)
Removes a status string at a given horizontal position.
virtual void removeStatusStrings ()
Removes all status strings.
virtual void removeQuitKeys ()
Removes all quit keys.
virtual void removeExitKeys ()
Removes all exit keys.
virtual bool hasExitKey (int pKey) const
Returns whether or not a key exists in the.
virtual bool hasQuitKey (int pKey) const
Returns whether or not a key exists in the.
virtual void getQuitKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual std::string getQuitKeyListString () const
Returns a string containing a comma-separated list of the.
virtual void getExitKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual std::string getExitKeyListString () const
Returns a string containing a comma-separated list of the.
virtual std::map< int, bool > getQuitKeys () const
Returns the keys that will make the window quit its input.
virtual std::map< int, bool > getExitKeys () const
Returns the keys that will make the window exit is input.
void toggleMessage (bool pDrawMessage)
Sets whether or not to draw the message area (the area within.
void toggleTitle (bool pDrawTitle)
Sets whether or not to draw the title.
void toggleStatus (bool pDrawStatus)
Sets whether or not to draw the status line.
bool messageWillDraw () const
Returns whether the message will draw or not.
bool titleWillDraw () const
Returns whether the title will draw or not.
bool statusWillDraw () const
Returns whether the status line will draw or not.
void toggleSpecialChars (bool pDrawSpecialChars)
Sets whether or not to draw the "special" characters (these are.
bool specialCharsWillDraw () const
Returns whether the "special" characters will be drawn or.
virtual void drawTitle ()
Writes the title line.
virtual void drawStatus ()
Writes the status line.
virtual void drawMessage ()
Writes the message text (in the area within the borders)
virtual void drawSpecialChars ()
Writes the set of "special" characters to the window.
virtual void setReturnCode (const long &pReturnCode)
Explicitly sets the member return code for the window.
virtual void setMessageColor (e_cxColors pColor)
Returns the message color.
virtual void setTitleColor (e_cxColors pColor)
Sets the title color.
virtual void setStatusColor (e_cxColors pColor)
Sets the color of the status line at bottom of window.
virtual void setBorderColor (e_cxColors pColor)
Sets the color of the window border.
virtual bool hasAttr (e_WidgetItems pItem, attr_t pAttr)
Returns whether an attribute is set for a widget item.
bool getLeaveNow () const
Returns whether or not something told the window to leave now.
std::string getName () const
virtual void setName (const std::string &pName)
Sets the name of the window. The name is an alternative means.
bool mouseEvtWasInWindow () const
Returns whether the current mouse information stored in the.
virtual bool mouseEvtWasInTitle () const
Returns whether the current mouse information stored in the.
virtual void doMouseBehavior ()
Triggers the window's mouse event behavior. This method can.
virtual void doMouseBehavior (int pMouseY, int pMouseX)
Triggers the window's mouse event behavior. Also sets the.
std::shared_ptr< cxFunction > getKeyFunction (int pKey) const
Returns a cxFunction pointer for a key.
std::shared_ptr< cxFunction0 > getKeyFunctionAsFunction0 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction0.
std::shared_ptr< cxFunction2 > getKeyFunctionAsFunction2 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction2.
std::shared_ptr< cxFunction4 > getKeyFunctionAsFunction4 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction4.
bool mouseEvtWasButtonEvt () const
Returns whether or not the mouse event read in mMouse was.
bool mouseButton1Pressed () const
Returns whether or not the first mouse button was pressed.
bool mouseButton1Released () const
Returns whether or not the first mouse button was released.
bool mouseButton1Clicked () const
Returns whether or not the first mouse button was clicked.
bool mouseButton1DoubleClicked () const
Returns whether or not the first mouse button was double-clicked.
bool mouseButton2Clicked () const
Returns whether or not the second mouse button was clicked.
bool mouseButton2DoubleClicked () const
Returns whether or not the second mouse button was double-clicked.
bool mouseButton3Clicked () const
Returns whether or not the second mouse button was clicked.
virtual void mouseButton1Click (int pY, int pX)
Tells the window that mouse button 1 was clicked at a certain.
virtual void mouseButton2Click (int pY, int pX)
Tells the window that mouse button 2 was clicked at a certain.
virtual void mouseButton3Click (int pY, int pX)
Tells the window that mouse button 3 was clicked at a certain.
std::string getString (int pRow, int pCol, int pNumber)
Get the contents of a portion of the window. (for debugging/testing)
void info ()
Display information about a window (for debugging/testing)
virtual void toggleBorderTop (bool pToggle)
Sets whether or not to display the top border.
virtual void toggleBorderBottom (bool pToggle)
Sets whether or not to display the bottom border.
virtual void toggleBorderLeft (bool pToggle)
Sets whether or not to display the left border.
virtual void toggleBorderRight (bool pToggle)
Sets whether or not to display the right border.
virtual void addSpecialChar (int pY, int pX, chtype pChar, attr_t pAttr=A_NORMAL)
Adds a character to be written somewhere in the window. These.
virtual void removeSpecialChar (int pY, int pX)
Removes a character from the set of special characters (by.
virtual void clearSpecialChars ()
Clears the collection of special characters.
virtual bool functionExistsForLastMouseState () const
Returns whether an external function pointer exists for the.
int getMouseState () const
Returns the current mouse state as it was last captured by the.
std::string getMouseStateStr () const
Returns a string version of the current mouse state as it was.
virtual e_cxColors getItemColor (e_WidgetItems pItem) const
Returns the color of one of the items in a window.
Public Member Functions inherited from cx::cxObject
cxObject ()
virtual ~cxObject ()
virtual void beep ()
Protected Member Functions
void copyCxMultiFormStuff (const cxMultiForm *pThatMultiForm)
Makes a copy of a cxMultiForm's member variables.
long doInputLoop (bool pShowSubforms)
Handles the input loop. Returns cxID_QUIT or cxID_EXIT,.
int lowestSubformRow (unsigned pIndex=0) const
Returns the lowest row of any subform on the form, starting at.
Protected Member Functions inherited from cx::cxForm
void copyCxFormStuff (const cxForm *pThatForm)
Makes a copy of a cxForm's member variables.
void lookForEditableInputs ()
Scans all inputs to see if any are editable and updates.
long doInputLoop (bool &pRunOnLeaveFunction)
Handles the input loop. Returns cxID_QUIT or cxID_EXIT,.
virtual bool doCurrentInput (long &pReturnCode, bool &pRunOnLeaveFunction, bool &pFunctionExists, bool pExitOverride=false)
Gets input from the current input (for use in the input loop).
virtual void setIsModal (bool pIsModal)
Sets whether the form is modal or not.
Protected Member Functions inherited from cx::cxWindow
virtual void reCreatePanel ()
Creates mPanel (by calling new_panel()), then sets up.
void freeWindow ()
Frees the memory used by the ncurses window and.
virtual void init (int pRow, int pCol, int pHeight, int pWidth, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pParentWindow=nullptr, bool pResizeVertically=true)
Initializes the window parameters and sets up the internal.
virtual void removeAllSubwindows ()
Removes all subwindow pointers.
virtual void addSubwindow (cxWindow *pSubWindow)
Adds a subwindow to the window. Subwindows of a.
virtual void removeSubWindow (const cxWindow *pSubWindow)
Removes a window from the subwindow list.
virtual void setElementColor (short &pColorPair, attr_t &pElementAttr, e_cxColors pColor)
Sets the color (and attribute, if necessary) of a color element.
virtual void enableAttrs (WINDOW *pWin, e_WidgetItems pItem)
Enables the attributes for one of the m*Attrs sets for an ncurses window.
virtual void disableAttrs (WINDOW *pWin, e_WidgetItems pItem)
Disables the attributes for one of the m*Attrs sets for an ncurses window.
virtual void writeWithHighlighting (WINDOW *pWindow, const std::string &pText, const int &pY, const int &pStartX, const int &pEndX, int pNormalTextItem=-1)
Writes text to an ncurses WINDOW, highlighting any characters.
virtual void copyCxWinStuff (const cxWindow *pThatWindow, bool pRecreateWin=true)
Makes a copy of a cxWindow's member variables.
virtual void getRowColBasedOn (cxWindow *pParentWindow, eHPosition pPosition, const std::string &pTitle, const std::string &pStatus, const std::string &pMessage, int &pRow, int &pCol)
Figures out how to align text based on a title & message.
virtual bool handleFunctionForLastKey (bool *pFunctionExists=nullptr, bool *pRunOnLeaveFunction=nullptr)
Looks for a function tied to the last keypress and.
virtual bool handleFunctionForLastMouseState (bool *pFunctionExists=nullptr, bool *pRunOnLeaveFunction=nullptr)
Looks for a function tied to the last mouse state captured.
virtual void draw ()
Fills the member ncurses window structure with the current.
void setKeyFunctions (const cxWindow &pWindow)
Returns whether or not a mouse event location is within.
void setFocusFunctions (const cxWindow &pWindow)
Re-sets the onFocus and onLeave functions from another.
bool parentIsCxPanel () const
Returns whether or not the parent window, if there is one, is.
bool parentIsCxForm () const
Returns whether or not the parent window, if there is one, is.
bool parentIsCxNotebook () const
Returns whether or not the parent window, if there is one, is.
cxWindowPtrContainer::const_iterator subWindows_begin () const
Returns a const iterator to the first subwindow.
cxWindowPtrContainer::const_iterator subWindows_end () const
Returns a const iterator to the one past the last subwindow.
cxWindowPtrContainer::const_reverse_iterator subWindows_rbegin () const
Returns a const reverse begin iterator for the subwindow collection.
cxWindowPtrContainer::const_reverse_iterator subWindows_rend () const
Returns a const reverse end iterator for the subwindow collection.
bool onFocusFunctionIsSet () const
Returns whether or not the onFocus function is set (if.
bool onLeaveFunctionIsSet () const
Returns whether or not the onLeave function is set (if.
Additional Inherited Members
Static Public Member Functions inherited from cx::cxObject
static bool UseColors ()
static void UseColors (bool useIt)
static bool UseBeeps ()
static void UseBeeps (bool useIt)
Protected Types inherited from cx::cxForm
typedef std::vector< std::shared_ptr< cxMultiLineInput > > inputPtrContainer
Protected Attributes inherited from cx::cxForm
inputPtrContainer mInputs
int mCurrentInput = 0
std::vector< std::pair< int, int > > mInputPositions
bool mTrapNonAssignedFKeys = true
If mTrapNonAssignedFKeys is true, function keys that aren't.
bool mStartAtFirstInput = false
mStartAtFirstInput keeps track of whether or not the form
Protected Attributes inherited from cx::cxWindow
WINDOW * mWindow = nullptr
Everything in the window is written here; this is an nCurses window structure.
messageLineContainer mMessageLines
Contains the text to be shown inside the window (note: the.
std::map< std::pair< int, int >, chtype > mSpecialChars
Contains "special" characters which are added to the window.
std::set< attr_t > mMessageAttrs
Message attributes.
std::set< attr_t > mTitleAttrs
Title attributes.
std::set< attr_t > mStatusAttrs
Status attributes.
std::set< attr_t > mBorderAttrs
Border attributes.
std::set< attr_t > mHotkeyAttrs
Hotkey attributes.
std::map< std::pair< int, int >, attr_t > mSpecialCharAttrs
Attributes for the "special" characters (which are added to.
short mMessageColorPair = eWHITE_BLUE
short mTitleColorPair = eGRAY_BLUE
short mStatusColorPair = eBROWN_BLUE
short mBorderColorPair = eGRAY_BLUE
eHPosition mHorizTitleAlignment = eHP_LEFT
eHPosition mHorizMessageAlignment = eHP_LEFT
eHPosition mHorizStatusAlignment = eHP_LEFT
eVPosition mVerticalMessageAlignment = eVP_TOP
bool mDrawMessage = true
bool mDrawTitle = true
bool mDrawStatus = true
bool mDrawSpecialChars = true
std::shared_ptr< cxFunction > mOnFocusFunction = nullptr
std::shared_ptr< cxFunction > mOnLeaveFunction = nullptr
bool mIsModal = false
bool mLeaveNow = false
std::map< int, std::shared_ptr< cxFunction > > mKeyFunctions
std::map< int, std::shared_ptr< cxFunction > > mMouseFunctions
std::map< int, bool > mQuitKeys
std::map< int, bool > mExitKeys
bool mHotkeyHighlighting
Static Protected Attributes inherited from cx::cxObject
static bool useColors
Whether or not to use colors.
static bool useBeeps
Whether or not to enable beeping.
Detailed Description
Represents a form that can.
contain subforms (forms within the
form). Note that this class uses dynamic memory when subforms are added and stores the pointers to the subforms in member data. getForm() can be used to return a pointer to one of the subforms so that you can perform operations on one of the subforms; however, you should never use the 'delete' operator on one of the pointers returned by getForm() because the destructor of this class takes care of freeing the memory used by the subforms.
Constructor & Destructor Documentation
cxMultiForm() [1/2]
cx::cxMultiForm::cxMultiForm (cxWindow * pParentWindow = nullptr, int pRow = 0, int pCol = 0, int pHeight = DEFAULT_HEIGHT, int pWidth = DEFAULT_WIDTH, const std::string & pTitle = "", eBorderStyle pBorderStyle = eBS_SINGLE_LINE, cxWindow * pExtTitleWindow = nullptr, cxWindow * pExtStatusWindow = nullptr, bool pAutoExit = false, bool pStacked = false) explicit
Default constructor. All parameters have default values.
Parameters
pParentWindow Pointer to parent window; default nullptr
pRow Y location of form; default 0
pCol X location of form; default 0
pHeight Height of form, in lines; defaults to 24
pWidth Width of form; defaults to 80
pTitle Title of form; defaults to empty string
pBorderStyle The type of border to use - can be eBS_SINGLE_LINE for a single-line border or eBS_NOBORDER for no border.
pExtTitleWindow A pointer to another cxWindow in which to display the window title.
pExtStatusWindow A pointer to another cxWindow in which to display the status.
pAutoExit Whether or not to exit the form when the user tries to go to the next input from the last input. Defaults to false.
pStacked If true, the form will behave assuming each input is on its own line.
cxMultiForm() [2/2]
cx::cxMultiForm::cxMultiForm (const cxMultiForm & pThatMultiForm)
Copy constructor
Parameters
pThatMultiForm Another cxForm object to be copied
References copyCxMultiFormStuff(), cx::height(), cx::left(), cx::cxForm::setIsModal(), cx::top(), and cx::width().
~cxMultiForm()
cx::cxMultiForm::~cxMultiForm () virtual
Member Function Documentation
addExitKey()
bool cx::cxMultiForm::addExitKey (int pKey, bool pRunOnLeaveFunction = true, bool pOverride = false) override virtual
Adds a key that will cause the form to quit and.
return cxID_EXIT. Normally, if the key already exists
as a function key, it will not be added as an exit key.
Parameters
pKey The key to add
pRunOnLeaveFunction Whether or not to run the onLeave functions when the multiForm exits. Defaults to true. Note that this affects both the onLeave function for the multiForm, as well as the current subform when the multiForm is modal.
pOverride If true, then the key will be added as an exit key regardless if the key exists as a function key. This defaults to false.
Returns
Whether or not the key was added
Reimplemented from cx::cxForm.
References cx::cxForm::addExitKey(), and cx::cxWindow::removeQuitKey().
addQuitKey()
bool cx::cxMultiForm::addQuitKey (int pKey, bool pRunOnLeaveFunction = true, bool pOverride = false) override virtual
Adds a key that will cause the form to quit and.
return cxID_QUIT. Normally, if the key already exists
as a function key, it will not be added as an exit key.
Parameters
pKey The key to add
pRunOnLeaveFunction Whether or not to run the onLeave functions when the multiForm exits. Defaults to true. Note that this affects both the onLeave function for the multiForm, as well as the current subform when the multiForm is modal.
pOverride If true, then the key will be added as an exit key regardless if the key exists as a function key. This defaults to false.
Returns
Whether or not the key was added
Reimplemented from cx::cxForm.
References cx::cxForm::addQuitKey(), and cx::cxWindow::removeExitKey().
appendForm() [1/3]
virtual std::shared_ptr< cxForm > cx::cxMultiForm::appendForm (int pRow, int pCol, int pHeight, int pWidth, const std::string & pTitle = "", eBorderStyle pBorderStyle = eBS_NOBORDER, bool pStacked = false) virtual
Appends a subform to the form.
Parameters
pRow The row of the subform (relative to the parent form)
pCol The column of the subform (relative to the parent form)
pHeight The height of the subform
pWidth The width of the subform
pBorderStyle The type of border for the subform (defaults to eBS_NOBORDER) - See cxBorderStyles.h for border types
pTitle The title for the subform (defaults to blank) - Note that this will only appear if the subform has a border.
pStacked Whether or not the subform should be in 'stacked' mode (with each input above the next).
Returns
A pointer to the subform
Referenced by multiForm(), multiForm2(), and multiFormWithDisabledSubform().
appendForm() [2/3]
virtual bool cx::cxMultiForm::appendForm (std::shared_ptr< cxForm > & pForm) virtual
Appends a subform to the form via a pointer (without.
moving it). The pointer that is passed in must
point to a dynamically-created cxForm object created
with the 'new' operator, because cxMultiForm
cleans up its subform pointers in the destructor with
the 'delete' operator.
Parameters
pForm A pointer to a cxForm (or a deriving object)
Returns
Whether or not the subform got appended (true/false)
appendForm() [3/3]
virtual bool cx::cxMultiForm::appendForm (std::shared_ptr< cxForm > & pForm, int pRow, int pCol, bool * pMoved = nullptr) virtual
Appends a subform to the form via a pointer.
The pointer that is passed in must point to a
dynamically-created cxForm object created with
the 'new' operator, because cxMultiForm cleans
up its subform pointers in the destructor with
the 'delete' operator.
Parameters
pForm A pointer to a cxForm (or a deriving object)
pRow The row on the form where you want the subform to be located
pCol The column on the form where you want the subform to be located
pMoved If non-null, the boolean pointed to by this variable will store whether or not the subform was able to be moved.
Returns
Whether or not the subform got appended (true/false)
clear()
void cx::cxMultiForm::clear (bool pRefresh = false) override virtual
Clears the multiForm and all the subforms.
Parameters
pRefresh Whether or not to refresh the multiForm and the subforms as they are cleared (defaults to false).
Reimplemented from cx::cxWindow.
References cx::cxWindow::clear().
copyCxMultiFormStuff()
void cx::cxMultiForm::copyCxMultiFormStuff (const cxMultiForm * pThatMultiForm) protected
Makes a copy of a cxMultiForm's member variables.
Parameters
pThatMultiForm A pointer to another cxMultiForm whose members to copy
References cx::cxForm::copyCxFormStuff(), cx::cxWindow::freeWindow(), getLastKey(), cx::cxForm::setIsModal(), and cx::cxForm::setLastKey().
Referenced by cxMultiForm(), and operator=().
cxTypeStr()
string cx::cxMultiForm::cxTypeStr () const override virtual
Returns the name of the cxWidgets class. This can be used to.
determine the type of cxWidgets object that deriving classes
derive from in applications.
Returns
The name of the cxWidgets class.
Reimplemented from cx::cxForm.
doInputLoop()
long cx::cxMultiForm::doInputLoop (bool pShowSubforms) protected
Handles the input loop. Returns cxID_QUIT or cxID_EXIT,.
depending on the user's input. This function is meant
not to be virtual, since it is specifically for
cxMultiForm.
Parameters
pShowSubforms Whether or not to have the subforms show themselves before running their input loops.
Returns
A return code (cxID_QUIT or cxID_EXIT, depending on the user's input).
References cx::cxID_EXIT, cx::cxID_QUIT, cx::cxForm::getAllowQuit(), cx::cxForm::getAutoExit(), getLastKey(), cx::cxForm::getWaitForInputIfEmpty(), cx::cxWindow::handleFunctionForLastMouseState(), cx::cxForm::hasEditableInputs(), hasEditableSubforms(), cx::messageBox(), cx::cxWindow::mLeaveNow, cx::cxWindow::mouseButton1Clicked(), cx::cxWindow::mouseEvtWasInWindow(), cx::cxWindow::mWindow, cx::cxWindow::parentIsCxPanel(), cx::cxForm::runLoopEndFunction(), cx::cxForm::runLoopStartFunction(), cx::cxWindow::runOnFocusFunction(), and cx::cxForm::setLastKey().
Referenced by showModal().
getAssumeMovingBackwards()
bool cx::cxMultiForm::getAssumeMovingBackwards () const
Returns whether it will be assumed that the user is moving.
backwards through the subforms when the cxMultiForm gains
focus (see setAssumeMovingBackwards())
Returns
Whether or not to assume the user is moving backwards and to set the cursor on the last input of the last subform.
getCurrentForm()
int cx::cxMultiForm::getCurrentForm () const virtual
Returns the index of the current form.
Returns
The index of the current form
getForm() [1/2]
virtual std::shared_ptr< cxForm > cx::cxMultiForm::getForm (const std::string & pTitle) const virtual
Returns a pointer to one of the subforms (by title), or.
nullptr if there is no subform with the given title.
Parameters
pTitle The title of the subform
Returns
A pointer to the subform, or nullptr if there is no subform with the given title. The return value should always be checked against nullptr before it's used.
getForm() [2/2]
shared_ptr< cxForm > cx::cxMultiForm::getForm (unsigned pIndex) const virtual
Returns a pointer to one of the subforms (by index), or.
nullptr if the index is out of bounds.
Parameters
pIndex The index of the subform
Returns
A pointer to the subform, or nullptr if pIndex is out of bounds. The return value should always be checked against nullptr before it's used.
References form().
Referenced by multiForm2_goToForm1_Input1(), and multiForm2_goToForm3_Input1().
getLastKey()
int cx::cxMultiForm::getLastKey () const override virtual
Returns the last key typed by the user.
Returns
The last key typed by the user
Reimplemented from cx::cxWindow.
References cx::cxWindow::getLastKey().
Referenced by copyCxMultiFormStuff(), and doInputLoop().
getSubformIndex() [1/2]
int cx::cxMultiForm::getSubformIndex (const std::shared_ptr< cxForm > & pForm) const virtual
Returns the index of a subform on the.
form, given a cxForm pointer.
Parameters
pForm A pointer to a cxForm
Returns
The index of the subform, or -1 if the given cxForm pointer isn't a subform on this form.
References getSubformIndex().
Referenced by getSubformIndex().
getSubformIndex() [2/2]
int cx::cxMultiForm::getSubformIndex (cxForm * pForm) const virtual
References numSubforms().
getValue() [1/6]
virtual std::string cx::cxMultiForm::getValue (const std::string & pStr, bool pIsLabel = true) const override virtual
Returns the value associated with a particular input (by label or name).
Overridden from cxForm to prevent hiding.
Reimplemented from cx::cxForm.
getValue() [2/6]
virtual std::string cx::cxMultiForm::getValue (const std::string & pTitle, const std::string & pLabel, bool pIsLabel = true) const virtual
Gets the value of an input on one of the subforms (by.
title & label/name).
Parameters
pTitle The title of the subform
pLabel The label/name of the input on the subfrom
pIsLabel If true (default), pLabel specifies the label of the input. If false, pLabel specifies the name of the input.
Returns
The value stored in the input, or a blank string if there is no subform with the given title or if there is no input on the subform with the given label/name.
getValue() [3/6]
virtual std::string cx::cxMultiForm::getValue (const std::string & pTitle, int pInputIndex) const virtual
Gets the value of an input on one of the subforms (by.
title & input index)
Parameters
pTitle The title of the subform
pInputIndex The index of the input on the subform
Returns
The value stored in the input, or a blank string if there is no subform with the given title or pInputIndex is out of bounds.
getValue() [4/6]
string cx::cxMultiForm::getValue (int pIndex) const override virtual
Returns the value associated with a particular input (by index).
Overridden from cxForm to prevent hiding.
Reimplemented from cx::cxForm.
References cx::cxForm::getValue().
getValue() [5/6]
virtual std::string cx::cxMultiForm::getValue (unsigned pFormIndex, const std::string & pLabel, bool pIsLabel = true) const virtual
Gets the value of an input on one of the subforms (by.
index & label/name)
Parameters
pFormIndex The subform index
pLabel The label/name of the input on the subform
pIsLabel If true (default), pLabel specifies the label of the input on the form. If false, pLabel specifies the name of the input.
Returns
The value stored in the input, or a blank string if pFormIndex is out of bounds or there is no input on the subform with the given label/name.
getValue() [6/6]
string cx::cxMultiForm::getValue (unsigned pFormIndex, int pInputIndex) const virtual
Gets the value of an input on one of the subforms (by indexes)
Parameters
pFormIndex The subform index
pInputIndex The index of the input on the subform
Returns
The value stored in the input, or a blank string if the indexes are out of bounds.
hasChanged()
bool cx::cxMultiForm::hasChanged () const override virtual
Returns whether or not any inputs on the form,.
or any inputs on any of the subforms, have changed.
Returns
true if the values of any inputs on the form or on any of the subforms have changed; returns false if nothing has changed.
Reimplemented from cx::cxForm.
References cx::cxForm::hasChanged().
hasEditableSubforms()
bool cx::cxMultiForm::hasEditableSubforms () const
Returns whether any of the subforms contain.
inputs that are currently editable.
Returns
Whether or not any of the subforms contain inputs that are currently editable.
Referenced by doInputLoop().
hide()
void cx::cxMultiForm::hide (bool pHideSubwindows = true) override virtual
Hides the form.
Parameters
pHideSubwindows Whether or not to also hide the subwindows (defaults to true)
Reimplemented from cx::cxForm.
References cx::cxForm::hide().
Referenced by show().
lowestSubformRow()
int cx::cxMultiForm::lowestSubformRow (unsigned pIndex = 0) const protected
Returns the lowest row of any subform on the form, starting at.
a given index. Returns -1 if there are no subforms or if
the given index is out of bounds.
Parameters
pIndex The index at which to start. Defaults to 0.
Returns
The lowest row (relative to the form) of the subforms, or -1 if there are no inputs or pIndex is out of bounds.
References cx::top().
move()
bool cx::cxMultiForm::move (int pNewRow, int pNewCol, bool pRefresh = true) override virtual
Changes the window's position (based on a new upper-left corner). Also moves the input windows.
Parameters
pNewRow The new topmost row of the form
pNewCol The new leftmost column of the form
pRefresh Whether or not to refrseh the window (defaults to true)
Returns
Whether or not the move succeeded or not (true/false)
Reimplemented from cx::cxForm.
References cx::left(), cx::cxForm::move(), show(), and cx::top().
Referenced by multiForm().
numSubforms()
size_t cx::cxMultiForm::numSubforms () const
Returns the number of subforms on the form.
Returns
The number of subforms on the form
Referenced by cx::cxPanel::exitNow(), getSubformIndex(), cx::cxPanel::quitNow(), and setCurrentSubformByPtr().
operator=()
cxMultiForm & cx::cxMultiForm::operator= (const cxMultiForm & pThatMultiForm)
Assignment operator.
Parameters
pThatMultiForm Another cxMultiForm to be copied
Returns
References copyCxMultiFormStuff().
removeExitKey()
void cx::cxMultiForm::removeExitKey (int pKey) override virtual
Removes an exit key.
Parameters
pKey The key to remove from the list of exit keys
Reimplemented from cx::cxForm.
References cx::cxForm::removeExitKey().
removeQuitKey()
void cx::cxMultiForm::removeQuitKey (int pKey) override virtual
Removes a quit key (but doesn't work for ESC)
Parameters
pKey The key to remove from the list of quit keys
Reimplemented from cx::cxForm.
References cx::cxForm::removeQuitKey().
removeSubform() [1/2]
virtual bool cx::cxMultiForm::removeSubform (const std::string & pTitle) virtual
Removes a subform (by title).
Parameters
pTitle The title of the subform
Returns
True if the remove succeeded, or false if not (i.e., if there were no subforms with the given title).
removeSubform() [2/2]
bool cx::cxMultiForm::removeSubform (unsigned pIndex) virtual
Removes a subform (by index).
Parameters
pIndex The index of the subform
Returns
True if the remove succeeded, or false if not (i.e., if pIndex is out of bounds).
setAssumeMovingBackwards()
void cx::cxMultiForm::setAssumeMovingBackwards (bool pAssumeMovingBackwards)
Normally, if the cursor is on the last form when a cxMultiForm.
gains focus, the cursor will be set to the last input on that
form, assuming the user is moving backwards through the
subforms. This method can turn that off.
Parameters
pAssumeMovingBackwards Whether or not to assume the user is moving backwards and to set the cursor on the last input of the last subform.
setChanged()
void cx::cxMultiForm::setChanged (bool pDataChanged) override virtual
Setter for whether or not data should be considered changed.
Parameters
pDataChanged Whether or not data should be considered changed (true/false)
Reimplemented from cx::cxForm.
References cx::cxForm::setChanged().
setCurrentSubform() [1/2]
virtual bool cx::cxMultiForm::setCurrentSubform (const std::string & pTitle) virtual
Changes which subform is to have the focus (by title).
Parameters
pTitle The title of the subform that should next get focus
Returns
True if successful or false if not
setCurrentSubform() [2/2]
bool cx::cxMultiForm::setCurrentSubform (int pIndex) virtual
Changes which subform is to have the focus (by index).
Parameters
pIndex The index of the subform that should next get focus
Returns
True if successful or false if not
References cx::cxWindow::mIsModal.
Referenced by multiForm2_goToForm1_Input1(), and multiForm2_goToForm3_Input1().
setCurrentSubformByPtr() [1/2]
virtual bool cx::cxMultiForm::setCurrentSubformByPtr (const std::shared_ptr< cxForm > & pForm) virtual
Changes which subform is to have the focus (by pointer).
This has a different function name so as not to be
ambiguous to the compiler.
Parameters
pForm A pointer to a cxForm (if it exists in the multiForm, it will then be the current window).
Returns
True if successful or false if not
setCurrentSubformByPtr() [2/2]
bool cx::cxMultiForm::setCurrentSubformByPtr (cxForm * pForm) virtual
References cx::cxWindow::mIsModal, and numSubforms().
setDisableCursorOnShow()
void cx::cxMultiForm::setDisableCursorOnShow (bool pDisableCursorOnShow) override virtual
Sets whether the window should disable the cursor.
when it's shown (this is the default behavior).
Parameters
pDisableCursorOnShow Whether or not to disable the cursor when shown
Reimplemented from cx::cxForm.
References cx::cxForm::setDisableCursorOnShow().
setEnabled()
void cx::cxMultiForm::setEnabled (bool pEnabled) override virtual
Enables or disables the multiForm. Enabling/disabling a.
cxMultiForm consequently also enables/disables all the inputs
and subforms.
Parameters
pEnabled Whether the multiForm should be enabled or not (true/false)
Reimplemented from cx::cxForm.
References cx::cxForm::setEnabled().
setKeyFunction() [1/3]
bool cx::cxMultiForm::setKeyFunction (int pKey, funcPtr0 pFunction, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) override virtual
Adds a function to call when the user presses some key. Note that the function key is expected to be F1-F10 (the setFocus() function only expects these keys for running functions).
Parameters
pKey An int representing a function key
pFunction The function to be run - Must have signature string func()
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxForm, but could be useful for deriving classes - this is here so that setKeyFunction() in cxForm will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the form after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
Reimplemented from cx::cxForm.
References cx::cxForm::setKeyFunction().
setKeyFunction() [2/3]
bool cx::cxMultiForm::setKeyFunction (int pKey, funcPtr2 pFunction, void * p1, void * p2, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) override virtual
Adds a function to call when the user presses some key. Note that the function key is expected to be F1-F10 (the setFocus() function only expects these keys for running functions).
Parameters
pKey An int representing a function key
pFunction The function to be run - Must have signature string func(void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxForm, but could be useful for deriving classes - this is here so that setKeyFunction() in cxForm will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the form after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
Reimplemented from cx::cxForm.
References cx::cxForm::setKeyFunction().
setKeyFunction() [3/3]
bool cx::cxMultiForm::setKeyFunction (int pKey, funcPtr4 pFunction, void * p1, void * p2, void * p3, void * p4, bool pUseReturnVal = false, bool pExitAfterRun = false, bool pRunOnLeaveFunction = true) override virtual
Adds a function to call when the user presses some key. Note that the function key is expected to be F1-F10 (the setFocus() function only expects these keys for running functions). Note that functions added with this method take precedence over functions with 2 void parameters.
Parameters
pKey An int representing a function key
pFunction The function to be run - Must have signature string func(void*, void*, void*, void*)
p1 Pointer to the first parameter to be used for the function
p2 Pointer to the second parameter to be used for the function *
p3 Pointer to the 3rd parameter to be used for the function
p4 Pointer to the 4th parameter to be used for the function
pUseReturnVal Whether or not to use the function's return value (not used by cxForm, but could be useful for deriving classes - this is here so that setKeyFunction() in cxForm will be overridden). Defaults to false.
pExitAfterRun Whether or not to exit the form after running the function (defaults to false)
pRunOnLeaveFunction Whether or not to run the onLeave function when the window exits (if pExitAfterRun is true). Defaults to true.
Returns
True if the key & function was added or false if not
Reimplemented from cx::cxForm.
References cx::cxForm::setKeyFunction().
Referenced by multiForm2().
setSubformEnabled() [1/2]
virtual void cx::cxMultiForm::setSubformEnabled (const std::string & pTitle, bool pEnabled) virtual
Enables or disables one of the subforms (by title).
Parameters
pTitle The title of the subform
pEnabled Whether the subform should be enabled or not (true/false)
setSubformEnabled() [2/2]
void cx::cxMultiForm::setSubformEnabled (unsigned pIndex, bool pEnabled) virtual
Enables or disables one of the subforms (by index).
Parameters
pIndex The index of the subform
pEnabled Whether the subform should be enabled or not (true/false)
Referenced by multiFormWithDisabledSubform().
setValue() [1/6]
virtual bool cx::cxMultiForm::setValue (const std::string & pLabel, const std::string & pValue, bool pIsLabel = true, bool pRefresh = false) override virtual
Sets the value of one of the inputs on the form (by label/name).
Parameters
pLabel The label of the input
pValue The new string value for the input
pIsLabel If true (default), pLabel specifies the label of the input. If false, pLabel specifies the name of the input.
pRefresh Whether or not to refresh the input (defaults to false)
Returns
True if successful or false if not
Reimplemented from cx::cxForm.
setValue() [2/6]
virtual bool cx::cxMultiForm::setValue (const std::string & pTitle, const std::string & pLabel, const std::string & pValue, bool pIsLabel = true, bool pRefresh = false) virtual
Sets a value of an input on one of the subforms.
Parameters
pTitle The title of the subform
pLabel The label/name of the input on the subform
pValue The value to set in the input
pIsLabel If true (default), pLabel specifies the label of the input. If false, pLabel specifies the name of the input.
pRefresh Whether or not to refresh the input (defaults to false)
Returns
true if successful or false if not
setValue() [3/6]
virtual bool cx::cxMultiForm::setValue (const std::string & pTitle, int pInputIndex, const std::string & pValue, bool pRefresh = false) virtual
Sets a value of an input on one of the subforms.
Parameters
pTitle The title of the subform
pInputIndex The index of the input on the subform
pValue The value to set in the input
pRefresh Whether or not to refresh the input after the value is set
Returns
true if successful or false if not
setValue() [4/6]
virtual bool cx::cxMultiForm::setValue (int pIndex, const std::string & pValue, bool pRefresh = false) override virtual
Sets the value of one of the inputs on the form (by index).
Parameters
pIndex The index of the input
pValue The value to be placed at that index.
pRefresh Whether or not to refresh the input (defaults to false)
Returns
True if successful or false if not
Reimplemented from cx::cxForm.
setValue() [5/6]
virtual bool cx::cxMultiForm::setValue (unsigned pFormIndex, const std::string & pLabel, const std::string & pValue, bool pIsLabel = true, bool pRefresh = false) virtual
Sets a value of an input on one of the subforms.
Parameters
pFormIndex The index of the subform
pLabel The label/name of the input on the subform
pValue The value to set in the input
pIsLabel If true (default), pLabel specifies the label of the input. If false, pLabel specifies the name of the input.
pRefresh Whether or not to refresh the input (defaults to false)
Returns
true if successful or false if not
setValue() [6/6]
virtual bool cx::cxMultiForm::setValue (unsigned pFormIndex, int pInputIndex, const std::string & pValue, bool pRefresh = false) virtual
Sets a value of an input on one of the subforms.
Parameters
pFormIndex The index of the subform
pInputIndex The index of the input on the subform
pValue The value to set in the input
pRefresh Whether or not to refresh the input after the value is set
Returns
true if successful or false if not
show()
long cx::cxMultiForm::show (bool pBringToTop = false, bool pShowSubwindows = true) override virtual
Shows the form
Parameters
pBringToTop Whether or not to bring this window to the top. Defaults to false.
pShowSubwindows Whether or not to show sub-windows also. Defaults to true. Note that the subforms are considered subwindows, so if this parameter is false and the first parameter is true, the subforms won't show.
Returns
The return value of cxForm::show()
Reimplemented from cx::cxForm.
References cx::cxFIRST_AVAIL_RETURN_CODE, cx::cxWindow::getShowSelfBeforeSubwins(), hide(), cx::cxWindow::isEnabled(), cx::cxWindow::show(), cx::cxForm::show(), and showAllSubforms().
Referenced by move(), and showModal().
showAllSubforms()
void cx::cxMultiForm::showAllSubforms (bool pBringToTop = true, bool pSkipCurrentForm = false) const virtual
Shows (refreshes) all inputs.
Parameters
pBringToTop Whether or not to bring the inputs to the top (defaults to true)
pSkipCurrentForm Whether or not to skip the current form (defaults to false)
References cx::cxWindow::isBelow().
Referenced by show().
showModal()
long cx::cxMultiForm::showModal (bool pShowSelf = true, bool pBringToTop = false, bool pShowSubwindows = true) override virtual
Shows the form and waits for input.
Parameters
pShowSelf Whether or not to show the window before running the input loop. Defaults to true.
pBringToTop Whether or not to bring this window to the top. Defaults to false.
pShowSubwindows Whether or not to show sub-windows also. Defaults to true. Note that the subforms are considered subwindows, so if this parameter is false and the first parameter is true, the subforms won't show.
Returns
A return code based on user input; see the eReturnCodes enumeration in cxReturnCodes.h
Reimplemented from cx::cxForm.
References cx::cxID_EXIT, doInputLoop(), cx::cxWindow::getLeaveNow(), cx::cxWindow::getReturnCode(), cx::cxWindow::isEnabled(), cx::cxWindow::mIsModal, cx::cxWindow::runOnFocusFunction(), cx::cxWindow::runOnLeaveFunction(), cx::cxWindow::setReturnCode(), and show().
Referenced by multiForm(), multiForm2(), and multiFormWithDisabledSubform().
subformIsEnabled() [1/2]
virtual bool cx::cxMultiForm::subformIsEnabled (const std::string & pTitle) const virtual
Returns whether one of the subforms is.
enabled (by title).
Parameters
pTitle The title of the subform
Returns
Whether the subform is enabled or not (true/false). Returns false if there is no subform with the given title.
subformIsEnabled() [2/2]
bool cx::cxMultiForm::subformIsEnabled (unsigned pIndex) const virtual
Returns whether one of the subforms is.
enabled (by index).
Parameters
pIndex The index of the subform
Returns
Whether the subform is enabled or not (true/false). Returns false if pIndex is out of bounds.
References cx::cxWindow::isEnabled().
unhide()
void cx::cxMultiForm::unhide (bool pUnhideSubwindows = true) override virtual
Un-hides the form.
Parameters
pUnhideSubwindows Whether or not to also unhide the subwindows (defaults to true)
Reimplemented from cx::cxForm.
References cx::cxWindow::isEnabled(), and cx::cxForm::unhide().
The documentation for this class was generated from the following files:
/home/erico/projects/cxWidgets/src/cxMultiForm.h
/home/erico/projects/cxWidgets/src/cxMultiForm.cpp