cxWidgets: cx::cxNotebook Class Reference
cx::cxNotebook Class Reference
This class represents a notebook control, which manages multiple.
#include <cxNotebook.h>
Public Member Functions
cxNotebook (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, bool pLabelsOnTop=true, bool pLeftLabelSpace=true, bool pRightLabelSpace=true, int pTabSpacing=0, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pTabNavWrap=true)
Constructor.
virtual ~cxNotebook ()
void setLabelsOnTop (bool pLabelsOnTop, bool pRefresh=false)
Toggles whether the labels should be on the top or bottom.
bool getLabelsOnTop () const
Returns whether the labels are set to appear on top.
void setLeftLabelSpace (bool pLeftLabelSpace)
Toggles the option to have a space to the left of label text.
bool getLeftLabelSpace () const
Returns the currently-set option of having a space to the left.
void setRightLabelSpace (bool pRightLabelSpace)
Toggles the option to have a space to the right of label text.
bool getRightLabelSpace () const
Returns the currently-set option of having a space to the right.
bool setTabSpacing (int pTabSpacing, bool pRefresh=false)
Sets the number of spaces to use for horizontal alignment of.
int getTabSpacing () const
Returns the number of spaces being used for horizontal tab.
void setTabNavWrap (bool pTabNavWrap)
Sets whether or not the user will be able to wrap from the.
bool getTabNavWrap () const
Returns whether or not wrapping is allowed between the first.
virtual long show (bool pBringToTop=false, bool pShowSubwindows=true) override
Shows the notebook.
virtual long showModal (bool pShowSelf=true, bool pBringToTop=true, bool pShowSubwindows=true) override
Shows the notebook and allows the user to interact with the.
virtual void hide (bool pHideSubwindows=true) override
Hides the notebook.
virtual void unhide (bool pUnhideSubwindows=true) override
Un-hides the notebook.
virtual std::string cxTypeStr () const override
Returns the class type as a string ("cxNotebook")
virtual bool windowIsInNotebook (cxWindow *pWindow) const
Returns whether a window exists in the notebook.
virtual std::shared_ptr< cxPanel > append (const std::string &pLabel, const std::string &pPanelName="")
Appends a new panel & tab to the notebook. Returns a pointer.
virtual cxPanel * getPanel (unsigned int pIndex) const
Returns a pointer to one of the panels in the notebook (by.
virtual cxPanel * getPanel (const std::string &pID, bool pIsLabel=true) const
Returns a pointer to one of the panels in the notebook (by.
virtual cxPanel * getCurrentPanelPtr () const
Returns a pointer to the current panel, or nullptr if there is.
virtual bool move (int pNewRow, int pNewCol, bool pRefresh=true) override
Changes the notebok's position, based on a new upper-left.
virtual void setShowPanelWindow (unsigned int pIndex, bool pShowPanelWindow)
Sets whether one of the panels in the notebook should show.
virtual void setShowPanelWindow (const std::string &pID, bool pShowPanelWindow, bool pIsLabel=true)
Sets whether one of the panels in the notebook should show.
virtual bool getShowPanelWindow () const override
Returns whether or not the panel window will be shown.
virtual bool getShowPanelWindow (unsigned int pIndex) const
Returns whether or not one of the panels in the notebook will.
virtual bool getShowPanelWindow (const std::string &pID, bool pIsLabel=true) const
Returns whether or not one of the panels in the notebook will.
virtual void showSubwindows (bool pBringToTop=true, bool pShowSubwindows=true) override
Shows the subwindows for the notebook. This is overidden here.
virtual std::string getLabel (unsigned int pIndex) const
Returns the label for one of the panels (by index).
virtual std::string getLabel (const std::string &pName) const
Returns the label forone of the panels (by panel name).
virtual bool setLabel (unsigned int pIndex, const std::string &pLabel, bool pRefresh=false)
Sets the label for one of the panels (by index). If the new.
virtual bool setLabel (const std::string &pID, const std::string &pLabel, bool pIsLabel=true, bool pRefresh=false)
Sets the label for one of the panels (by label/name). If the.
virtual void setEnabled (bool pEnabled) override
Enables or disables the notebook.
virtual void setEnabled (unsigned int pIndex, bool pEnabled) override
Enables or disables a window in the notebook (by index). (This.
virtual void setEnabled (const std::string &pID, bool pEnabled, bool pIsTitle=true) override
Enables or disables a window in the panel (by title/name).
void setNextTabKey (int pKey)
Sets the key to be used for navigation to the next tab.
int getNextTabKey () const
Returns the key that is used for navigation to the next tab.
void setPrevTabKey (int pKey)
Sets the key to be used for navigation to the previous tab.
int getPrevTabKey () const
Returns the key that is used for navigation to the previous tab.
void setTabNavKey (int pKey)
Sets the key that is used for bringing up a tab selection menu.
int getTabNavKey () const
Returns the key currently used for bringing up the tab.
void setAllDisabledMsg (const std::string &pAllDisabledMsg)
Sets the message to be displayed when all the panels in the.
const std::string & getAllDisabledMsg () const
Returns the message that is displayed when all the panels in.
void setNoWindowsMsg (const std::string &pNoWindowsMsg)
Sets the message to be displayed when there are no panels in.
const std::string & getWindowDisabledMsg () const
Returns the message that is displayed when one of the panels in.
void setWindowDisabledMsg (const std::string &pMsg)
Sets the message to be displayed when a window is disabled.
const std::string & getNoWindowsMsg () const
Returns the message that is displayed when there are no panels.
virtual bool mouseEvtWasInTitle () const override
Returns whether the current mouse information's coordinates.
virtual std::shared_ptr< cxWindow > removeWindow (unsigned int pIndex) override
Removes a panel from the notebook. This returns a cxWindow.
virtual void removeWindow (cxWindow *pWindow) override
Removes a panel from the notebook, without freeing its memory.
virtual void removeWindow (const std::shared_ptr< cxWindow > &pWindow) override
Removes a panel from the notebook (by shared_ptr), without.
virtual void delWindow (unsigned int pIndex) override
Removes a panel from the notebook (by index) and frees up its.
virtual void delWindow (cxWindow *pWindow)
Removes a panel from the notebook (by pointer). Does nothing.
virtual void delWindow (const std::shared_ptr< cxWindow > &pWindow) override
Removes a panel from the notebook (by shared_ptr).
virtual bool setCurrentWindow (unsigned int pIndex) override
Sets which panel will get focus in the next call to.
virtual bool setCurrentWindow (const std::string &pTitle)
Sets which panel will get focus in the next call to.
virtual bool setCurrentWindow (const std::string &pID, bool pIsLabel) override
Sets which window will get focus in the next call to.
virtual bool setCurrentWindowByPtr (cxWindow *pWindow) override
Sets which window will get focus in the next.
virtual bool setCurrentWindowByPtr (const std::shared_ptr< cxWindow > &pWindow) override
Sets which window will get focus in the next.
virtual bool windowIsInPanel (const std::shared_ptr< cxWindow > &pWindow) const override
Returns whether a cxWindow object is contained in the notebook.
virtual int lastClickTabIndex () const
Returns the index of the tab (label window) that was clicked.
virtual bool swap (int pWindow1Index, int pWindow2Index) override
Swaps the order of 2 panels (by index). If both indexes are.
virtual bool swap (const std::shared_ptr< cxWindow > &pWindow1, const std::shared_ptr< cxWindow > &pWindow2) override
Swaps the order of 2 panels (by pointer). If both pointers are.
virtual bool swap (cxWindow *pWindow1, cxWindow *pWindow2) override
Swaps the order of 2 subwindows (by pointer). If both pointers.
bool selectNextWin ()
Selects the next available (enabled) window (moving forward),.
bool selectPrevWin ()
Selects the previous available (enabled) window (moving.
Public Member Functions inherited from cx::cxPanel
cxPanel (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", const std::string &pMessage="", const std::string &pStatus="", eBorderStyle pBorderStyle=eBS_NOBORDER, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pMessageUnderlines=false)
Default constructor.
virtual ~cxPanel ()
virtual unsigned int numWindows () const
Returns the number of windows that are contained.
virtual std::shared_ptr< cxWindow > getWindow (unsigned pIndex) const
Gets a pointer to one of the subwindows (by index).
virtual void delWindow (unsigned pIndex)
Removes a window from the panel (by index) and frees the memory.
virtual void delAllWindows ()
Removes all windows from the panel. Also frees the memory used.
virtual bool setCurrentWindow (unsigned pIndex)
Sets which window will get focus in the next.
virtual bool setKeyFunction (int pKey, const std::shared_ptr< cxFunction > &pFunction) override
Sets a function to be called when a key is pressed.
virtual void clearKeyFunction (int pKey) override
Removes a function pointer for a keypress for the panel so that it will no.
virtual bool setKeyFunction (int pKey, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
Sets a function to be called when a key is pressed. Note that.
virtual bool setKeyFunction (int pKey, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
Sets a function to be called when a key is pressed. Note that.
virtual bool setKeyFunction (int pKey, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true) override
Sets a function to be called when a key is pressed. Note that.
virtual int getCurrentWindowIndex () const
Returns the index of the current window.
virtual int getWindowIndex (const std::shared_ptr< cxWindow > &pWindow) const
Given a cxWindow pointer, this function will return the index.
virtual int getWindowIndex (cxWindow *pWindow) const
virtual const std::shared_ptr< cxWindow > & getCurrentWindowPtr () const
Returns a pointer to the current window.
virtual bool getAllowExit () const
Returns whether the user is allowed to exit out.
virtual void setAllowExit (bool pAllowExit)
Sets whether the user is allowed to exit out of.
virtual bool getAllowQuit () const
Returns whether the user is allowed to quit out.
virtual void setAllowQuit (bool pAllowQuit)
Sets whether the user is allowed to quit out of.
virtual bool windowIsEnabled (unsigned pIndex) const
Returns whether or not one of the windows in the panel.
virtual void enableWindow (unsigned pIndex, bool pEnabled=true)
Enables/disables one of the windows in the panel (by index).
virtual void clear (bool pRefresh=false) override
Clears all the window in the panel.
virtual bool addQuitKey (int pKey, bool pRunOnLeaveFunction=true, bool pOverride=false) override
Adds a key that will cause the window to quit its input loop.
virtual void removeQuitKey (int pKey) override
Removes a quit key.
virtual bool addExitKey (int pKey, bool pRunOnLeaveFunction=true, bool pOverride=false) override
Adds a key that will cause the window to quit its input loop.
virtual void removeExitKey (int pKey) override
Removes an exit key.
virtual void setEnabled (unsigned pIndex, bool pEnabled)
Enables or disables a window in the panel (by index).
virtual void setColor (e_WidgetItems pItem, e_cxColors pColor) override
Sets the color of one of the window items.
virtual void quitNow () override
This causes the panel to stop its input loop with a code of.
virtual void exitNow () override
This causes the panel to stop its input loop with a code of.
const std::shared_ptr< cxWindow > & getLastWindow () const
Returns a pointer to the last window in the panel that was.
virtual void setName (unsigned pIndex, const std::string &pName)
Sets the name of one of the windows in the panel (by index).
virtual void setName (const std::string &pID, const std::string &pName, bool pIsTitle=true)
Sets the name of one of the windows in the panel (by title/name).
virtual void setName (const std::string &pName) override
Sets the name of the panel. The name is an alternative means.
virtual int top () const override
Returns the top row of the window.
virtual int bottom () const override
Returns the bottom row of the window.
Public Member Functions inherited from cx::cxWindow
cxWindow (cxWindow *pParentWindow=nullptr, int pRow=0, int pCol=0, int pHeight=DEFAULT_HEIGHT, int pWidth=DEFAULT_WIDTH, const std::string &pTitle="", const std::string &pMessage="", const std::string &pStatus="", eBorderStyle pBorderStyle=eBS_SINGLE_LINE, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Default constructor.
cxWindow (cxWindow *pParentWindow, int pRow, int pCol, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor.
cxWindow (cxWindow *pParentWindow, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, int pHeight, int pWidth, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, const std::string &pStatus, int pHeight, int pWidth, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, const std::string &pMessage, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Centers the window in the middle of the screen.
cxWindow (cxWindow *pParentWindow, eHPosition pHPosition, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pExtTitleWindow=nullptr, cxWindow *pExtStatusWindow=nullptr, bool pHotkeyHighlighting=false)
Overloaded constructor - Lets you specify the horizontal position.
cxWindow (const cxWindow &pThatWindow)
Copy constructor.
virtual ~cxWindow ()
virtual void centerHoriz (bool pRefresh=true)
Centers the window horizontally on the screen.
virtual void alignHoriz (eHPosition pPosition, bool pRefresh=true)
Aligns the window horizontally on the screen.
virtual void centerVert (bool pRefresh=true)
Centers the window vertically on the screen.
virtual void alignVert (eVPosition pPosition, bool pRefresh=true)
Aligns the window vertically on the screen.
virtual void center (bool pRefresh=true)
Centers the window on the screen.
virtual std::string getTitle () const
Accessor for title text - Returns the first string in the.
virtual void setTitle (const std::string &pTitle, bool pRefreshTitle=true)
Setter for the title text - This sets the first string in the.
std::string getStatus () const
Accessor for the status line text.
virtual void setStatus (const std::string &pStatus, bool pRefreshStatus=true)
Mutator for the status line text.
std::string getMessage () const
Returns the message that appears in the window, concatenating all message lines together.
virtual void setMessage (const std::string &pMessage)
Sets the text that appears within the window.
virtual void addMessageLineBelow (const std::string &pLine)
Adds a line to the message to be displayed in the window,.
virtual void addMessageLinesBelow (const std::vector< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLinesBelow (const std::list< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLinesBelow (const std::deque< std::string > &pLines)
Adds lines to the message below the current message text.
virtual void addMessageLineAbove (const std::string &pLine)
Adds a line to the message to be displayed in the window,.
virtual void addMessageLinesAbove (const std::vector< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void addMessageLinesAbove (const std::list< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void addMessageLinesAbove (const std::deque< std::string > &pLines)
Adds lines to the message above the current message text.
virtual void setMessageLines (const std::vector< std::string > &pLines)
Sets the message lines in the window.
virtual void setMessageLines (const std::list< std::string > &pLines)
Sets the message lines in the window.
virtual void setMessageLines (const std::deque< std::string > &pLines)
Sets the message lines in the window.
virtual void removeMessageLine (unsigned pIndex)
Removes a line from the text inside the window (by index).
virtual void setMessageLine (unsigned pIndex, const std::string &pLine)
Modifies one of the lines displayed in the window.
void setHorizTitleAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the title text.
eHPosition getHorizTitleAlignment () const
Accessor for the title text alignment.
void setHorizMessageAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the message text.
eHPosition getHorizMessageAlignment () const
Accessor for the horizontal message text alignment.
void setHorizStatusAlignment (eHPosition pHAlignment)
Sets the horizontal alignment of the status text.
eHPosition getHorizStatusAlignment () const
Accessor for the horizontal status text alignment.
void setVerticalMessageAlignment (eVPosition pVAlignment)
Sets the vertical alignment of the message text.
eVPosition getVerticalMessageAlignment () const
Accessor for the vertical message text alignment.
void setExtTitleWindow (cxWindow *pWindow, bool pRefreshTitle=true)
Sets an external cxWindow object to be used for the title, rather.
cxWindow * getExtTitleWindow () const
Accessor for the external title window pointer.
void setExtStatusWindow (cxWindow *pWindow, bool pRefreshStatus=true)
Sets an external cxWindow object to be used for status, rather.
cxWindow * getExtStatusWindow () const
Accessor for the external status window pointer.
bool isHidden () const
Returns whether or not the window is hidden.
virtual bool modalGetsKeypress () const
Returns whether or not a call to showModal() will wait for a.
virtual long setFocus (bool pShowSelf=true, bool pBringToTop=true, bool pShowSubwindows=true)
Alias for showModal()
virtual void setFocusColors ()
Turns on the ncurses attribute A_REVERSE for the window to.
virtual void setFocusColors (attr_t pAttr)
Turns on the ncurses attribute pAttr for the window to.
virtual void unSetFocusColors ()
Disables focus for this window and unhighlights the message.
virtual void unSetFocusColors (attr_t pAttr)
Disables focus for this window and un-highlights the message (using pAttr)
virtual void erase (bool pEraseSubwindows=true)
Erases the window.
virtual void bringToTop (bool pRefresh=true)
Brings the window to the top.
virtual void bringToBottom (bool pRefresh=false)
Puts the window on the bottom of all other windows.
virtual bool isOnTop () const
Returns whether the window is on top of all other windows.
virtual bool isOnBottom () const
Returns whether the window is on the bottom of all other windows.
virtual bool isAbove (const cxWindow &pThatWindow) const
Returns whether the window is above another window.
virtual bool isBelow (const cxWindow &pThatWindow) const
Returns whether a window is below another window.
void touchWindow ()
Marks the window's entire content as dirty so that the next.
virtual void drawBorder (int pRow, int pCol, int pHeight, int pWidth, bool pTop=true, bool pBottom=true, bool pLeft=true, bool pRight=true)
Draws the border (based on the border style)
virtual void drawBorder (int pHeight, int pWidth)
Draws a box in the window.
virtual void drawBorder ()
Draws a box for the window border.
virtual int centerRow () const
Returns the center row of the window.
virtual int left () const
Returns the left column of the window.
virtual int centerCol () const
Returns the center column of the window.
virtual int right () const
Returns the right column of the window.
virtual int width (int pWidth)
Changes the width of the window.
virtual int width () const
Returns the width of the window.
virtual int height (int pHeight)
Changes the height of the window.
virtual int height () const
Returns the height of the window.
virtual void getRect (int &pTop, int &pLeft, int &pBottom, int &pRight)
Returns the coordinates of the rectangle defining the window.
virtual bool pointIsInWindow (int pY, int pX) const
Returns whether a screen location is in the window (including.
virtual bool pointIsInTitle (int pY, int pX) const
Returns whether a screen location is in the title of the window.
virtual void getSize (int &pHeight, int &pWidth)
Returns the height & width of the window.
virtual void addAttr (e_WidgetItems pItem, attr_t pAttr)
Adds an ncurses attribute to use for one of the items in the.
virtual void setAttr (e_WidgetItems pItem, attr_t pAttr)
Sets the ncurses attribute to use for one of the items in the.
virtual void removeAttr (e_WidgetItems pItem, attr_t pAttr)
Removes an ncurses attribute from one of the item lists.
virtual void removeAttrs (e_WidgetItems pItem)
Removes all attributes for a given window item.
virtual void getAttrs (e_WidgetItems pItem, std::set< attr_t > &pAttrs) const
Returns the set of ncurses attributes for a given item.
virtual void resize (int pNewHeight, int pNewWidth, bool pRefresh=true)
Changes the window's width and height. The window's upper-left.
virtual bool moveRelative (int pVerticalOffset, int pHorizOffset, bool pRefresh=true)
Changes the window's position via vertical & horizontal offsets.
unsigned numSubWindows ()
Returns the number of subwindows in this window.
void setSubWinMessage (unsigned pIndex, const std::string &pMessage)
Sets the message of one of the subwindows (by index).
void setSubWinMessage (const std::string &pTitle, const std::string &pMessage)
Sets the message of one of the subwindows (by title).
virtual bool hasFocus () const
Returns true if window has focus, false otherwise.
virtual void setBorderStyle (eBorderStyle pBorderStyle)
Sets the border style.
eBorderStyle getBorderStyle () const
Returns the border style.
bool hasBorder () const
Does this window have a border?
virtual cxWindow * getParent () const
Returns a pointer to the parent window.
void setParent (cxWindow *pNewParent)
Changes the pointer to the parent window; changes the parent window.
virtual void dump (std::string &pResult)
Returns a string containing all the characters.
cxWindow & operator= (const cxWindow &pThatWindow)
Assignment operator.
virtual void writeText (int pRow, int pCol, const std::string &pText, bool pRefresh=true)
Writes text on the window. Note that the text is not permanant, so.
virtual void setHotkeyHighlighting (bool pHotkeyHighlighting)
Enables/disables the use of hotkey attributes when writing the message.
bool getHotkeyHighlighting () const
Returns whether hotkey attributes are used when writing the message.
virtual bool isEnabled () const
Returns whether or not the window is enabled.
virtual void setDisableCursorOnShow (bool pDisableCursorOnShow)
Sets whether the window should disable the cursor.
virtual bool getDisableCursorOnShow () const
Returns whether or not the window will disable.
virtual bool getExitOnMouseOutside () const
Returns whether the window exits its modal input loop when.
virtual void setExitOnMouseOutside (bool pExitOnMouseOutside)
Sets whether the window should exit its modal input loop.
virtual int getLastKey () const
Returns the last key pressed by the user (for showModal(), etc.)
virtual void setLastKey (int pLastKey)
Sets the last keypress.
virtual bool lastKeyWasMouseEvt () const
Returns whether or not the last keypress was a mouse event.
virtual void getLastMouseEvtCoords (int &pY, int &pX)
Returns the coordinates of the last mouse event in the window.
virtual bool getChangeColorsOnFocus () const
Returns whether the window will change.
virtual void setChangeColorsOnFocus (bool pChangeColorsOnFocus)
Sets whether colors should change when focus.
virtual void setOnFocusFunction (const std::shared_ptr< cxFunction > &pFunction)
Sets the window's "on focus" function.
virtual void setOnFocusFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseVal=false, bool pExitAfterRun=false)
Sets the "on focus" function pointer.
virtual void setOnFocusFunction (funcPtr2 pFunction, void *p1, void *p2, bool pUseVal=false, bool pExitAfterRun=false)
Sets the "on focus" function pointer.
virtual void setOnFocusFunction (funcPtr0 pFunction, bool pUseVal=false, bool pExitAfterRun=false)
Sets the "on focus" function pointer.
virtual void setOnLeaveFunction (const std::shared_ptr< cxFunction > &pFunction)
Sets the window's "on leave" function.
virtual void setOnLeaveFunction (funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4)
Sets the "on leave" function pointer.
virtual void setOnLeaveFunction (funcPtr2 pFunction, void *p1, void *p2)
Sets the "on focus" function pointer.
virtual void setOnLeaveFunction (funcPtr0 pFunction)
Sets the "on focus" function pointer.
virtual bool runOnFocusFunction (std::string *pFunctionRetval=nullptr)
Runs the onFocus function, if it's set.
virtual bool runOnLeaveFunction (std::string *pFunctionRetval=nullptr)
Runs the onLeave function, if it's set. However, if the last.
virtual void toggleOnFocusFunction (bool pRunOnFocus)
Sets whether or not the onFocus function should run.
virtual void toggleOnLeaveFunction (bool pRunOnLeave)
Sets whether or not the onLeave function should run.
virtual bool onFocusFunctionEnabled () const
Returns whether or not the onFocus function is set to run.
virtual bool onLeaveFunctionEnabled () const
Returns whether or not the onLeave function is set to run.
virtual const std::shared_ptr< cxFunction > & getOnFocusFunction () const
Accessor for the onFocus function.
virtual const std::shared_ptr< cxFunction > & getOnLeaveFunction () const
Accessor for the onLeave function.
virtual bool isModal () const
Returns whether or not the window is currently.
virtual void clearKeyFunctionByPtr (funcPtr4 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctionByPtr (funcPtr2 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctionByPtr (funcPtr0 pFunction)
Removes a keypress function pointer.
virtual void clearKeyFunctions ()
Clears the list of external functions fired by hotkeys.
virtual bool hasKeyFunction (int pKey) const
Returns whether an external function exists for a keypress.
virtual bool setMouseFunction (int pMouseState, const std::shared_ptr< cxFunction > &pFunction)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr4 pFunction, void *p1, void *p2, void *p3, void *p4, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr2 pFunction, void *p1, void *p2, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state.
virtual bool setMouseFunction (int pMouseState, funcPtr0 pFunction, bool pUseReturnVal=false, bool pExitAfterRun=false, bool pRunOnLeaveFunction=true)
Sets a function to be called for a certain mouse state. This.
virtual void clearMouseFunction (int pMouseState)
Removes a function pointer for a mouse event so that it will.
virtual void clearMouseFunctions ()
Clears the list of external functions fired by mouse events.
virtual bool hasMouseFunction (int pMouseState) const
Returns whether an external function exists for a mouse event.
std::map< int, std::shared_ptr< cxFunction > >::iterator keyFunctions_begin ()
Returns a begin iterator to the map of cxFunction pointers.
std::map< int, std::shared_ptr< cxFunction > >::iterator keyFunctions_end ()
Returns an end iterator to the map of cxFunction pointers.
virtual void getFunctionKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual void getFunctionKeys (std::vector< int > &pKeys) const
Populates a collection with integers representing the keys.
virtual void setShowSubwinsForward (bool pShowSubwinsForward)
Toggles the order in which subwindows will be shown.
virtual bool getShowSubwinsForward () const
Returns whether or not the subwindows will be shown.
virtual void setShowSelfBeforeSubwins (bool pShowSelfBeforeSubwins)
Sets whether the window will show itself before.
virtual bool getShowSelfBeforeSubwins () const
Returns whether or not the window will show itself before.
virtual long getReturnCode () const
Returns the return code set by the last call to.
virtual bool addTitleString (int pHPos, const std::string &pStr, bool pRefreshTitle=false)
Adds/sets a string to appear in the title at.
virtual std::string getTitleString (int pHPos) const
Returns the title string set at a given horizontal position.
virtual std::map< int, std::string > getTitleStrings () const
Returns the map of title strings for the window.
virtual void getTitleStrings (std::map< int, std::string > &pTitleStrings) const
Returns the map of title strings for the window (using an.
virtual void setTitleStrings (const std::map< int, std::string > &pTitleStrings)
Sets all the title strings via a map of horizontal.
virtual void removeTitleString (int pHPos)
Removes a title string at a given horizontal position.
virtual void removeTitleStrings ()
Removes all title strings.
virtual bool addStatusString (int pHPos, const std::string &pStr, bool pRefreshStatus=false)
Adds/sets a string to appear in the status line at.
virtual std::string getStatusString (int pHPos) const
Returns the status string set at a given horizontal position.
virtual std::map< int, std::string > getStatusStrings () const
Returns the map of status strings for the window.
virtual void getStatusStrings (std::map< int, std::string > &pStatusStrings) const
Returns the map of status strings for the window (using an.
virtual void setStatusStrings (const std::map< int, std::string > &pStatusStrings)
Sets all the status strings via a map of horizontal.
virtual void removeStatusString (int pHPos)
Removes a status string at a given horizontal position.
virtual void removeStatusStrings ()
Removes all status strings.
virtual void removeQuitKeys ()
Removes all quit keys.
virtual void removeExitKeys ()
Removes all exit keys.
virtual bool hasExitKey (int pKey) const
Returns whether or not a key exists in the.
virtual bool hasQuitKey (int pKey) const
Returns whether or not a key exists in the.
virtual void getQuitKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual std::string getQuitKeyListString () const
Returns a string containing a comma-separated list of the.
virtual void getExitKeyStrings (std::vector< std::string > &pKeys) const
Populates a collection of strings representing the keys.
virtual std::string getExitKeyListString () const
Returns a string containing a comma-separated list of the.
virtual std::map< int, bool > getQuitKeys () const
Returns the keys that will make the window quit its input.
virtual std::map< int, bool > getExitKeys () const
Returns the keys that will make the window exit is input.
void toggleMessage (bool pDrawMessage)
Sets whether or not to draw the message area (the area within.
void toggleTitle (bool pDrawTitle)
Sets whether or not to draw the title.
void toggleStatus (bool pDrawStatus)
Sets whether or not to draw the status line.
bool messageWillDraw () const
Returns whether the message will draw or not.
bool titleWillDraw () const
Returns whether the title will draw or not.
bool statusWillDraw () const
Returns whether the status line will draw or not.
void toggleSpecialChars (bool pDrawSpecialChars)
Sets whether or not to draw the "special" characters (these are.
bool specialCharsWillDraw () const
Returns whether the "special" characters will be drawn or.
virtual void drawTitle ()
Writes the title line.
virtual void drawStatus ()
Writes the status line.
virtual void drawMessage ()
Writes the message text (in the area within the borders)
virtual void drawSpecialChars ()
Writes the set of "special" characters to the window.
virtual void setReturnCode (const long &pReturnCode)
Explicitly sets the member return code for the window.
virtual void setMessageColor (e_cxColors pColor)
Returns the message color.
virtual void setTitleColor (e_cxColors pColor)
Sets the title color.
virtual void setStatusColor (e_cxColors pColor)
Sets the color of the status line at bottom of window.
virtual void setBorderColor (e_cxColors pColor)
Sets the color of the window border.
virtual bool hasAttr (e_WidgetItems pItem, attr_t pAttr)
Returns whether an attribute is set for a widget item.
bool getLeaveNow () const
Returns whether or not something told the window to leave now.
std::string getName () const
bool mouseEvtWasInWindow () const
Returns whether the current mouse information stored in the.
virtual void doMouseBehavior ()
Triggers the window's mouse event behavior. This method can.
virtual void doMouseBehavior (int pMouseY, int pMouseX)
Triggers the window's mouse event behavior. Also sets the.
std::shared_ptr< cxFunction > getKeyFunction (int pKey) const
Returns a cxFunction pointer for a key.
std::shared_ptr< cxFunction0 > getKeyFunctionAsFunction0 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction0.
std::shared_ptr< cxFunction2 > getKeyFunctionAsFunction2 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction2.
std::shared_ptr< cxFunction4 > getKeyFunctionAsFunction4 (int pKey) const
Returns a cxFunction pointer for a key, casted to a cxFunction4.
bool mouseEvtWasButtonEvt () const
Returns whether or not the mouse event read in mMouse was.
bool mouseButton1Pressed () const
Returns whether or not the first mouse button was pressed.
bool mouseButton1Released () const
Returns whether or not the first mouse button was released.
bool mouseButton1Clicked () const
Returns whether or not the first mouse button was clicked.
bool mouseButton1DoubleClicked () const
Returns whether or not the first mouse button was double-clicked.
bool mouseButton2Clicked () const
Returns whether or not the second mouse button was clicked.
bool mouseButton2DoubleClicked () const
Returns whether or not the second mouse button was double-clicked.
bool mouseButton3Clicked () const
Returns whether or not the second mouse button was clicked.
virtual void mouseButton1Click (int pY, int pX)
Tells the window that mouse button 1 was clicked at a certain.
virtual void mouseButton2Click (int pY, int pX)
Tells the window that mouse button 2 was clicked at a certain.
virtual void mouseButton3Click (int pY, int pX)
Tells the window that mouse button 3 was clicked at a certain.
std::string getString (int pRow, int pCol, int pNumber)
Get the contents of a portion of the window. (for debugging/testing)
void info ()
Display information about a window (for debugging/testing)
virtual void toggleBorderTop (bool pToggle)
Sets whether or not to display the top border.
virtual void toggleBorderBottom (bool pToggle)
Sets whether or not to display the bottom border.
virtual void toggleBorderLeft (bool pToggle)
Sets whether or not to display the left border.
virtual void toggleBorderRight (bool pToggle)
Sets whether or not to display the right border.
virtual void addSpecialChar (int pY, int pX, chtype pChar, attr_t pAttr=A_NORMAL)
Adds a character to be written somewhere in the window. These.
virtual void removeSpecialChar (int pY, int pX)
Removes a character from the set of special characters (by.
virtual void clearSpecialChars ()
Clears the collection of special characters.
virtual bool functionExistsForLastMouseState () const
Returns whether an external function pointer exists for the.
int getMouseState () const
Returns the current mouse state as it was last captured by the.
std::string getMouseStateStr () const
Returns a string version of the current mouse state as it was.
virtual e_cxColors getItemColor (e_WidgetItems pItem) const
Returns the color of one of the items in a window.
Public Member Functions inherited from cx::cxObject
cxObject ()
virtual ~cxObject ()
virtual void beep ()
Additional Inherited Members
Static Public Member Functions inherited from cx::cxObject
static bool UseColors ()
static void UseColors (bool useIt)
static bool UseBeeps ()
static void UseBeeps (bool useIt)
Protected Types inherited from cx::cxPanel
typedef std::vector< std::shared_ptr< cxWindow > > cxWindowPtrCollection
Protected Member Functions inherited from cx::cxPanel
bool anyEnabledWindows () const
Returns whether any of the windows contained in mWindows are.
bool lastEnabledWindow (int pIndex) const
Returns whether or not a window in the panel with a given index.
bool firstEnabledWindow (int pIndex) const
Returns whether or not a window in the panel with a given index.
Protected Member Functions inherited from cx::cxWindow
virtual void reCreatePanel ()
Creates mPanel (by calling new_panel()), then sets up.
void freeWindow ()
Frees the memory used by the ncurses window and.
virtual void init (int pRow, int pCol, int pHeight, int pWidth, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus, cxWindow *pParentWindow=nullptr, bool pResizeVertically=true)
Initializes the window parameters and sets up the internal.
virtual void removeAllSubwindows ()
Removes all subwindow pointers.
virtual void addSubwindow (cxWindow *pSubWindow)
Adds a subwindow to the window. Subwindows of a.
virtual void removeSubWindow (const cxWindow *pSubWindow)
Removes a window from the subwindow list.
virtual void setElementColor (short &pColorPair, attr_t &pElementAttr, e_cxColors pColor)
Sets the color (and attribute, if necessary) of a color element.
virtual void enableAttrs (WINDOW *pWin, e_WidgetItems pItem)
Enables the attributes for one of the m*Attrs sets for an ncurses window.
virtual void disableAttrs (WINDOW *pWin, e_WidgetItems pItem)
Disables the attributes for one of the m*Attrs sets for an ncurses window.
virtual void writeWithHighlighting (WINDOW *pWindow, const std::string &pText, const int &pY, const int &pStartX, const int &pEndX, int pNormalTextItem=-1)
Writes text to an ncurses WINDOW, highlighting any characters.
virtual void copyCxWinStuff (const cxWindow *pThatWindow, bool pRecreateWin=true)
Makes a copy of a cxWindow's member variables.
virtual void getRowColBasedOn (cxWindow *pParentWindow, eHPosition pPosition, const std::string &pTitle, const std::string &pStatus, const std::string &pMessage, int &pRow, int &pCol)
Figures out how to align text based on a title & message.
virtual bool handleFunctionForLastKey (bool *pFunctionExists=nullptr, bool *pRunOnLeaveFunction=nullptr)
Looks for a function tied to the last keypress and.
virtual bool handleFunctionForLastMouseState (bool *pFunctionExists=nullptr, bool *pRunOnLeaveFunction=nullptr)
Looks for a function tied to the last mouse state captured.
virtual void draw ()
Fills the member ncurses window structure with the current.
void setKeyFunctions (const cxWindow &pWindow)
Returns whether or not a mouse event location is within.
void setFocusFunctions (const cxWindow &pWindow)
Re-sets the onFocus and onLeave functions from another.
bool parentIsCxPanel () const
Returns whether or not the parent window, if there is one, is.
bool parentIsCxForm () const
Returns whether or not the parent window, if there is one, is.
bool parentIsCxNotebook () const
Returns whether or not the parent window, if there is one, is.
cxWindowPtrContainer::const_iterator subWindows_begin () const
Returns a const iterator to the first subwindow.
cxWindowPtrContainer::const_iterator subWindows_end () const
Returns a const iterator to the one past the last subwindow.
cxWindowPtrContainer::const_reverse_iterator subWindows_rbegin () const
Returns a const reverse begin iterator for the subwindow collection.
cxWindowPtrContainer::const_reverse_iterator subWindows_rend () const
Returns a const reverse end iterator for the subwindow collection.
bool onFocusFunctionIsSet () const
Returns whether or not the onFocus function is set (if.
bool onLeaveFunctionIsSet () const
Returns whether or not the onLeave function is set (if.
Protected Attributes inherited from cx::cxPanel
cxWindowPtrCollection mWindows
bool mCycleWin = true
std::shared_ptr< cxWindow > mLastWindow
Protected Attributes inherited from cx::cxWindow
WINDOW * mWindow = nullptr
Everything in the window is written here; this is an nCurses window structure.
messageLineContainer mMessageLines
Contains the text to be shown inside the window (note: the.
std::map< std::pair< int, int >, chtype > mSpecialChars
Contains "special" characters which are added to the window.
std::set< attr_t > mMessageAttrs
Message attributes.
std::set< attr_t > mTitleAttrs
Title attributes.
std::set< attr_t > mStatusAttrs
Status attributes.
std::set< attr_t > mBorderAttrs
Border attributes.
std::set< attr_t > mHotkeyAttrs
Hotkey attributes.
std::map< std::pair< int, int >, attr_t > mSpecialCharAttrs
Attributes for the "special" characters (which are added to.
short mMessageColorPair = eWHITE_BLUE
short mTitleColorPair = eGRAY_BLUE
short mStatusColorPair = eBROWN_BLUE
short mBorderColorPair = eGRAY_BLUE
eHPosition mHorizTitleAlignment = eHP_LEFT
eHPosition mHorizMessageAlignment = eHP_LEFT
eHPosition mHorizStatusAlignment = eHP_LEFT
eVPosition mVerticalMessageAlignment = eVP_TOP
bool mDrawMessage = true
bool mDrawTitle = true
bool mDrawStatus = true
bool mDrawSpecialChars = true
std::shared_ptr< cxFunction > mOnFocusFunction = nullptr
std::shared_ptr< cxFunction > mOnLeaveFunction = nullptr
bool mIsModal = false
bool mLeaveNow = false
std::map< int, std::shared_ptr< cxFunction > > mKeyFunctions
std::map< int, std::shared_ptr< cxFunction > > mMouseFunctions
std::map< int, bool > mQuitKeys
std::map< int, bool > mExitKeys
bool mHotkeyHighlighting
Static Protected Attributes inherited from cx::cxObject
static bool useColors
Whether or not to use colors.
static bool useBeeps
Whether or not to enable beeping.
Detailed Description
This class represents a notebook control, which manages multiple.
cxPanels with associated tabs. This derives from cxPanel; this
class is similar to a cxPanel, except that this class does not
automatically go to the next/previous window - the user has to click
on the associated tab or press the pageUp/pageDown keys to go between
tabs (and those keys may be changed).
An alternate way to navigate between the tabs is with a keypress,
which brings up a menu listing the tab labels, allowing the user to
choose a tab. By default, this key is F5; however, this can be
changed with the setTabNavKey() method.
By default, the user is able to wrap between the first and last
ediable tabs using the tab navigation keys. This behavior can be
changed with a call to setTabNavWrap().
Constructor & Destructor Documentation
cxNotebook()
cx::cxNotebook::cxNotebook (cxWindow * pParentWindow = nullptr, int pRow = 0, int pCol = 0, int pHeight = DEFAULT_HEIGHT, int pWidth = DEFAULT_WIDTH, bool pLabelsOnTop = true, bool pLeftLabelSpace = true, bool pRightLabelSpace = true, int pTabSpacing = 0, cxWindow * pExtTitleWindow = nullptr, cxWindow * pExtStatusWindow = nullptr, bool pTabNavWrap = true) explicit
Constructor.
Parameters
pParentWindow A pointer to the parent window. Can be nullptr.
pRow The row of the upper-left corner.
pCol The column of the upper-left corner.
pHeight The height of the window.
pWidth The width of the window.
pLabelsOnTop Whether or not the labels should be on top. If false, the labels will be on the bottom. This defaults to true (labels on top).
pLeftLabelSpace Whether or not to have a space to the left of label text. Defaults to true.
pRightLabelSpace Whether or not to have a space to the right of label text. Defaults to true.
pTabSpacing The number of spaces to use for horizontal alignment of the tabs (label windows). 0 would be sharing left/right borders, 1 would be right next to each other, etc. This defaults to 0.
pExtTitleWindow A pointer to another cxWindow in which to display the window title.
pExtStatusWindow A pointer to another cxWindow in which to display the status.
pTabNavWrap Whether or not to enable the user to wrap between the first and last enabled tabs using the navigation keys. Defaults to true.
References setShowPanelWindow().
~cxNotebook()
cx::cxNotebook::~cxNotebook () virtual
Member Function Documentation
append()
virtual std::shared_ptr< cxPanel > cx::cxNotebook::append (const std::string & pLabel, const std::string & pPanelName = "") virtual
Appends a new panel & tab to the notebook. Returns a pointer.
to the cxPanel that was added. If the panel can't be added
(i.e., if the label is too long for the tab to fit on the
screen), this won't create the panel, and this will return
nullptr.
Parameters
pLabel The label for the panel
pPanelName This can specify a name for the panel to allow identification later. This is optional and defaults to a blank string.
Returns
A smart pointer to the cxPanel that was added. If it couldn't be added, the smart pointer's pointer will be null.
Referenced by cxNotebookRemoveWindowTest(), cxNotebookSetTabSpacing(), cxNotebookSwapTest(), cxNotebookTest1(), cxNotebookTest2(), and cxNotebookWithEmptyPanelTest().
cxTypeStr()
string cx::cxNotebook::cxTypeStr () const override virtual
Returns the class type as a string ("cxNotebook")
Returns
The class type as a string ("cxNotebook")
Reimplemented from cx::cxPanel.
delWindow() [1/3]
void cx::cxNotebook::delWindow (const std::shared_ptr< cxWindow > & pWindow) override virtual
Removes a panel from the notebook (by shared_ptr).
Overridden from cxPanel to prevent hiding.
Parameters
pWindow A shared_ptr to a panel to remove from the notebook
Reimplemented from cx::cxPanel.
References cx::cxPanel::delWindow().
delWindow() [2/3]
void cx::cxNotebook::delWindow (cxWindow * pWindow) virtual
Removes a panel from the notebook (by pointer). Does nothing.
if the panel does not reside in the notebook. Note: If you
want to re-use the panel, you can use removeWindow() instead.
Parameters
pWindow A pointer to a panel to remove from the notebook
References cx::cxPanel::getWindowIndex(), and removeWindow().
delWindow() [3/3]
void cx::cxNotebook::delWindow (unsigned int pIndex) override virtual
Removes a panel from the notebook (by index) and frees up its.
memory. Does nothing if the index is out of bounds. Note:
If you want to re-use the window, you can use removeWindow()
instead.
Parameters
pIndex The index of the panel to remove from the notebook
References removeWindow().
Referenced by cxNotebookRemoveWindowTest().
getAllDisabledMsg()
const string & cx::cxNotebook::getAllDisabledMsg () const
Returns the message that is displayed when all the panels in.
the notebook are disabled.
Returns
The message that is displayed when all the panels in the notebook are disabled
getCurrentPanelPtr()
cxPanel * cx::cxNotebook::getCurrentPanelPtr () const virtual
Returns a pointer to the current panel, or nullptr if there is.
no current panel for some reason (i.e., if the notebook has
no panels).
Returns
A pointer to the current panel, or nullptr if there is none
References cx::cxPanel::getCurrentWindowPtr().
getLabel() [1/2]
virtual std::string cx::cxNotebook::getLabel (const std::string & pName) const virtual
Returns the label forone of the panels (by panel name).
Parameters
pName The name of the panel
Returns
The label of the panel. If there is no panel with the given name, this will return a blank string.
getLabel() [2/2]
string cx::cxNotebook::getLabel (unsigned int pIndex) const virtual
Returns the label for one of the panels (by index).
Parameters
pIndex The index of the panel
Returns
The label of the panel. If pIndex is out of bounds, this will return a blank string.
getLabelsOnTop()
bool cx::cxNotebook::getLabelsOnTop () const
Returns whether the labels are set to appear on top.
Returns
Boolean: true if the labels are set to appear on top, or false if they are to appear on the bottom.
getLeftLabelSpace()
bool cx::cxNotebook::getLeftLabelSpace () const
Returns the currently-set option of having a space to the left.
of label text.
Returns
Boolean: true if it's enabled, false if not.
getNextTabKey()
int cx::cxNotebook::getNextTabKey () const
Returns the key that is used for navigation to the next tab.
Returns
The key that is used for navigation to the next tab
getNoWindowsMsg()
const string & cx::cxNotebook::getNoWindowsMsg () const
Returns the message that is displayed when there are no panels.
in the notebook.
Returns
The message that is displayed when there are no panels in the notebook
getPanel() [1/2]
virtual cxPanel * cx::cxNotebook::getPanel (const std::string & pID, bool pIsLabel = true) const virtual
Returns a pointer to one of the panels in the notebook (by.
label/name).
Parameters
pID The label/name of the panel
pIsLabel If true, this will treat pID as a label. If false, this will treat pID as a name for a panel. This defaults to true.
Returns
A pointer to the panel with the given label/name. If there is no panel for the given label/name, this will return nullptr.
getPanel() [2/2]
cxPanel * cx::cxNotebook::getPanel (unsigned int pIndex) const virtual
Returns a pointer to one of the panels in the notebook (by.
index).
Parameters
pIndex The index of the panel to retrieve
Returns
A pointer to the panel with the given index. If there is no panel for the given index, this will return nullptr.
References cx::cxPanel::getWindow(), and cx::cxPanel::numWindows().
Referenced by setShowPanelWindow().
getPrevTabKey()
int cx::cxNotebook::getPrevTabKey () const
Returns the key that is used for navigation to the previous tab.
Returns
The key that is used for navigation to the previous tab
getRightLabelSpace()
bool cx::cxNotebook::getRightLabelSpace () const
Returns the currently-set option of having a space to the right.
of label text.
Returns
Boolean: true if it's enabled, false if not.
getShowPanelWindow() [1/3]
bool cx::cxNotebook::getShowPanelWindow () const override virtual
Returns whether or not the panel window will be shown.
Overridden from cxPanel to prevent hiding.
Returns
Whether or not the panel window will be shown
Reimplemented from cx::cxPanel.
References cx::cxPanel::getShowPanelWindow().
getShowPanelWindow() [2/3]
virtual bool cx::cxNotebook::getShowPanelWindow (const std::string & pID, bool pIsLabel = true) const virtual
Returns whether or not one of the panels in the notebook will.
show its window when it gets focus (by label/name).
Parameters
pID The label/name of the panel in the notebook
pShowPanelWindow Whether or not the panel should show its window when it gets focus.
pIsLabel If true, this will treat pID as a label. If false, this will treat pID as a name for a panel. This defaults to true.
Returns
Whether or not the panel in the notebook will show its window when it gets focus.
getShowPanelWindow() [3/3]
bool cx::cxNotebook::getShowPanelWindow (unsigned int pIndex) const virtual
Returns whether or not one of the panels in the notebook will.
show its window when it gets focus (by index).
Parameters
pIndex The index of the panel
Returns
Whether or not the panel in the notebook will show its window when it gets focus.
References cx::cxPanel::getShowPanelWindow(), cx::cxPanel::getWindow(), and cx::cxPanel::mWindows.
getTabNavKey()
int cx::cxNotebook::getTabNavKey () const
Returns the key currently used for bringing up the tab.
selection menu
Returns
The key currently used for bringing up the tab selection menu
getTabNavWrap()
bool cx::cxNotebook::getTabNavWrap () const
Returns whether or not wrapping is allowed between the first.
and last enabled tabs using the navigation keys.
Returns
Whether or not wrapping is allowed between the first and last enabled tabs using the navigation keys
getTabSpacing()
int cx::cxNotebook::getTabSpacing () const
Returns the number of spaces being used for horizontal tab.
alignment.
Returns
The number of spaces being used for horizontal tab alignment
getWindowDisabledMsg()
const string & cx::cxNotebook::getWindowDisabledMsg () const
Returns the message that is displayed when one of the panels in.
the notebook is disabled.
Returns
The message that is displayed when one of the panels in the notebook is disabled.
hide()
void cx::cxNotebook::hide (bool pHideSubwindows = true) override virtual
Hides the notebook.
Parameters
pHideSubwindows Whether or not to also hide the subwindows (defaults to true)
Reimplemented from cx::cxPanel.
References cx::cxPanel::hide().
Referenced by show().
lastClickTabIndex()
int cx::cxNotebook::lastClickTabIndex () const virtual
Returns the index of the tab (label window) that was clicked.
on. If the user didn't click on a tab window, then this will
return -1.
Returns
The index of the tab that was clicked on, or -1 if the user didn't click on a tab window.
mouseEvtWasInTitle()
bool cx::cxNotebook::mouseEvtWasInTitle () const override virtual
Returns whether the current mouse information's coordinates.
are within the top row of the notebook.
Returns
Whether or not the last mouse event occurred in the top row of the notebook
Reimplemented from cx::cxWindow.
References cx::left(), cx::right(), and cx::cxPanel::top().
move()
bool cx::cxNotebook::move (int pNewRow, int pNewCol, bool pRefresh = true) override virtual
Changes the notebok's position, based on a new upper-left.
corner. Also moves all the contained windows accordingly.
Parameters
pNewRow The new topmost row for the notebook
pNewCol The new leftmost column for the notebook
pRefresh Whether or not to refresh the window (defaults to true)
Returns
Whether or not the move succeeded or not (true/false)
Reimplemented from cx::cxPanel.
References cx::cxPanel::move().
removeWindow() [1/3]
void cx::cxNotebook::removeWindow (const std::shared_ptr< cxWindow > & pWindow) override virtual
Removes a panel from the notebook (by shared_ptr), without.
freeing its memory. Overridden from cxPanel to prevent hiding.
Parameters
pWindow A shared_ptr to a panel to be removed from the notebook
Reimplemented from cx::cxPanel.
References cx::cxPanel::removeWindow().
removeWindow() [2/3]
void cx::cxNotebook::removeWindow (cxWindow * pWindow) override virtual
Removes a panel from the notebook, without freeing its memory.
so that it may be used elsewhere. Note: If you don't want to
re-use the window, use delWindow() instead, as this frees up
the window's memory using delete. This takes a cxWindow*
rather than a cxPanel* so that this method will override the
version from cxPanel.
Parameters
pWindow A pointer to a panel to be removed from the notebook
Reimplemented from cx::cxPanel.
References cx::cxPanel::getWindowIndex(), and removeWindow().
removeWindow() [3/3]
shared_ptr< cxWindow > cx::cxNotebook::removeWindow (unsigned int pIndex) override virtual
Removes a panel from the notebook. This returns a cxWindow.
pointer rather than a cxPanel pointer so that this method
will override the version from cxPanel.
Parameters
pIndex The index of the window in the panel to remove
Returns
A pointer to the panel removed. If pIndex is not a valid index, the smart pointer returned will have a null value for its pointer.
Reimplemented from cx::cxPanel.
References cx::cxPanel::numWindows(), and cx::cxPanel::removeWindow().
Referenced by delWindow(), delWindow(), and removeWindow().
selectNextWin()
bool cx::cxNotebook::selectNextWin ()
Selects the next available (enabled) window (moving forward),.
if there is one. Returns whether or not there was an enabled
window.
Returns
true if there is an enabled window, or false if not.
References cx::cxPanel::getWindow(), cx::cxPanel::numWindows(), and setCurrentWindow().
selectPrevWin()
bool cx::cxNotebook::selectPrevWin ()
Selects the previous available (enabled) window (moving.
backward), if there is one. Returns whether or not there was
an enabled window.
Returns
true if there is an enabled window, or false if not.
References cx::cxPanel::getWindow(), cx::cxPanel::numWindows(), and setCurrentWindow().
setAllDisabledMsg()
void cx::cxNotebook::setAllDisabledMsg (const std::string & pAllDisabledMsg)
Sets the message to be displayed when all the panels in the.
notebook are disabled.
Parameters
pAllDisabledMsg A new message to display
setCurrentWindow() [1/3]
virtual bool cx::cxNotebook::setCurrentWindow (const std::string & pID, bool pIsLabel) override virtual
Sets which window will get focus in the next call to.
showModal() (by label or name).
This is separate from the previous setCurrentWindow() because
the previous setCurrentWindow() must be here to override
the one inherited from cxPanel. This method also sets by
label/name, whereas the other sets by the title.
Parameters
pTitle The label/name of the window that should get the focus
Returns
True if successful or false if not
Reimplemented from cx::cxPanel.
setCurrentWindow() [2/3]
virtual bool cx::cxNotebook::setCurrentWindow (const std::string & pTitle) virtual
Sets which panel will get focus in the next call to.
showModal() (by title).
Parameters
pTitle The title of the window that should get the focus
Returns
True if successful or false if not
setCurrentWindow() [3/3]
bool cx::cxNotebook::setCurrentWindow (unsigned int pIndex) override virtual
Sets which panel will get focus in the next call to.
showModal() (by index).
Parameters
pIndex The index of the window that should get the focus
Returns
True if successful or false if not
References cx::cxPanel::numWindows(), and cx::cxPanel::setCurrentWindow().
Referenced by selectNextWin(), selectPrevWin(), and setCurrentWindowByPtr().
setCurrentWindowByPtr() [1/2]
bool cx::cxNotebook::setCurrentWindowByPtr (const std::shared_ptr< cxWindow > & pWindow) override virtual
Sets which window will get focus in the next.
cycle through showModal() (by shared_ptr).
Overridden from cxPanel to prevent hiding.
Parameters
pWindow A shared_ptr to a cxWindow (if it exists in the panel, it will then be the current window).
Returns
True if successful or false if not
Reimplemented from cx::cxPanel.
References cx::cxPanel::setCurrentWindowByPtr().
setCurrentWindowByPtr() [2/2]
bool cx::cxNotebook::setCurrentWindowByPtr (cxWindow * pWindow) override virtual
Sets which window will get focus in the next.
cycle through showModal() (by pointer). This
has a different function name so as not to
be ambiguous to the compiler.
Parameters
pWindow A pointer to a cxWindow (if it exists in the panel, it will then be the current window).
Returns
True if successful or false if not
Reimplemented from cx::cxPanel.
References cx::cxPanel::mWindows, and setCurrentWindow().
setEnabled() [1/3]
void cx::cxNotebook::setEnabled (bool pEnabled) override virtual
Enables or disables the notebook.
Parameters
pEnabled Whether the notebook should be enabled or not (true/false)
Reimplemented from cx::cxPanel.
References cx::cxPanel::setEnabled().
setEnabled() [2/3]
virtual void cx::cxNotebook::setEnabled (const std::string & pID, bool pEnabled, bool pIsTitle = true) override virtual
Enables or disables a window in the panel (by title/name).
Enables or disables a window in the notebook (by title/name).
(This should be inherited from cxPanel, but the compiler
doesn't see it).
Parameters
pID The title/name of the window in the panel
pEnabled Boolean: If true, the window will be enabled, and if false, the window will be disabled.
pIsTitle If this is true (default), then pID will refer to the window's title. If this is false, then pID will refer to the window's name.
Reimplemented from cx::cxPanel.
setEnabled() [3/3]
void cx::cxNotebook::setEnabled (unsigned int pIndex, bool pEnabled) override virtual
Enables or disables a window in the notebook (by index). (This.
should be inherited from cxPanel, but the compiler doesn't see
it).
Parameters
pIndex The index of the window in the panel
pEnabled Boolean: If true, the window will be enabled, and if false, the window will be disabled.
References cx::cxPanel::setEnabled().
setLabel() [1/2]
virtual bool cx::cxNotebook::setLabel (const std::string & pID, const std::string & pLabel, bool pIsLabel = true, bool pRefresh = false) virtual
Sets the label for one of the panels (by label/name). If the.
new label would result in the label windows being too large to
fit on the screen, however, the label will not be updated.
Parameters
pID The label/name of the panel
pLabel The new label
pIsLabel Boolean: true if pID is a label, or false if it's a panel name.
pRefresh Whether or not to refresh the screen. Defaults to false.
Returns
true if the label was set, or false if not.
setLabel() [2/2]
virtual bool cx::cxNotebook::setLabel (unsigned int pIndex, const std::string & pLabel, bool pRefresh = false) virtual
Sets the label for one of the panels (by index). If the new.
label would result in the label windows being too large to
fit on the screen, however, the label will not be updated.
Parameters
pIndex The index of the panel
pLabel The new label
pRefresh Whether or not to refresh the screen. Defaults to false.
Returns
true if the label was set, or false if not.
Referenced by cxNotebookTest1(), and cxNotebookTest2().
setLabelsOnTop()
void cx::cxNotebook::setLabelsOnTop (bool pLabelsOnTop, bool pRefresh = false)
Toggles whether the labels should be on the top or bottom.
Parameters
pLabelsOnTop Boolean: If true, the labels should be on top. If false, the labels should be on the bottom.
pRefresh Whether or not to refresh the screen. Defaults to false.
References cx::cxPanel::bottom(), cx::left(), cx::cxPanel::mWindows, show(), and cx::cxPanel::top().
Referenced by cxNotebookSetTabSpacing(), and cxNotebookTest2().
setLeftLabelSpace()
void cx::cxNotebook::setLeftLabelSpace (bool pLeftLabelSpace)
Toggles the option to have a space to the left of label text.
Parameters
pLeftLabelSpace Boolean: If true, then new label text will have a space to the left. If false, new label text will not.
setNextTabKey()
void cx::cxNotebook::setNextTabKey (int pKey)
Sets the key to be used for navigation to the next tab.
Parameters
pKey A key to use to navigate to the next tab
References cx::cxPanel::mWindows.
setNoWindowsMsg()
void cx::cxNotebook::setNoWindowsMsg (const std::string & pNoWindowsMsg)
Sets the message to be displayed when there are no panels in.
the notebook.
Parameters
pNoWindowsMsg A new message to display
setPrevTabKey()
void cx::cxNotebook::setPrevTabKey (int pKey)
Sets the key to be used for navigation to the previous tab.
Parameters
pKey A key to use to navigate to the previous tab
References cx::cxPanel::mWindows.
setRightLabelSpace()
void cx::cxNotebook::setRightLabelSpace (bool pRightLabelSpace)
Toggles the option to have a space to the right of label text.
Parameters
pRightLabelSpace Boolean: If true, then new label text will have a space to the right. If false, new label text will not.
setShowPanelWindow() [1/2]
virtual void cx::cxNotebook::setShowPanelWindow (const std::string & pID, bool pShowPanelWindow, bool pIsLabel = true) virtual
Sets whether one of the panels in the notebook should show.
its window when it gets focus (by label/name). This is for a
screen refresh optimization.
Parameters
pID The label/name of the panel in the notebook
pShowPanelWindow Whether or not the panel should show its window when it gets focus.
pIsLabel If true, this will treat pID as a label. If false, this will treat pID as a name for a panel. This defaults to true.
setShowPanelWindow() [2/2]
void cx::cxNotebook::setShowPanelWindow (unsigned int pIndex, bool pShowPanelWindow) virtual
Sets whether one of the panels in the notebook should show.
its window when it gets focus (by index). This is for a
screen refresh optimization.
Parameters
pIndex The index of the panel in the notebook
pShowPanelWindow Whether or not the panel should show its window when it gets focus.
References getPanel(), and cx::cxPanel::setShowPanelWindow().
Referenced by cxNotebook().
setTabNavKey()
void cx::cxNotebook::setTabNavKey (int pKey)
Sets the key that is used for bringing up a tab selection menu.
Parameters
pKey A key to use to bring up the tab selection menu
References cx::cxPanel::mWindows.
setTabNavWrap()
void cx::cxNotebook::setTabNavWrap (bool pTabNavWrap)
Sets whether or not the user will be able to wrap from the.
last enabled tab to the first, or from the first enabled tab
to the last, when using the tab navigation keys.
Parameters
pTabNavWrap Whether or not to allow tab "wrapping" using the tab navigation keys
setTabSpacing()
bool cx::cxNotebook::setTabSpacing (int pTabSpacing, bool pRefresh = false)
Sets the number of spaces to use for horizontal alignment of.
the tabs (label windows).
Parameters
pTabSpacing The number of spaces to use for horizontal tab alignment. 0 would be sharing left/right borders, 1 would be right next to each other, 2 means there is 1 space between the tabs, etc.
pRefresh Whether or not to refresh the screen. Defaults to false.
Returns
Boolean: true if the tab spacing was set, or false if not. For example, this may not set the tab spacing if the new spacing would make any of the label windows go past the right edge of the notebook window. If pTabSpacing is the same as what is already set, then this will return true.
References cx::left(), and cx::right().
Referenced by cxNotebookSetTabSpacing().
setWindowDisabledMsg()
void cx::cxNotebook::setWindowDisabledMsg (const std::string & pMsg)
Sets the message to be displayed when a window is disabled.
Parameters
pMsg A new message
show()
long cx::cxNotebook::show (bool pBringToTop = false, bool pShowSubwindows = true) override virtual
Shows the notebook.
Parameters
pBringToTop Whether or not to bring the window to the top. Defaults to false.
pShowSubwindows Whether or not to show sub-windows also. Defaults to true.
Returns
This method returns a long to support overriding in derived classes that might need to return a value. For cxWindow, cxID_EXIT is always returned.
Reimplemented from cx::cxPanel.
References cx::cxID_EXIT, cx::cxWindow::getShowSelfBeforeSubwins(), cx::cxPanel::getWindow(), hide(), cx::cxWindow::isEnabled(), and showSubwindows().
Referenced by cxNotebookSetTabSpacing(), setLabelsOnTop(), and showModal().
showModal()
long cx::cxNotebook::showModal (bool pShowSelf = true, bool pBringToTop = true, bool pShowSubwindows = true) override virtual
Shows the notebook and allows the user to interact with the.
pages. Shows the current page.
Parameters
pShowSelf Whether or not to show the window before running the input loop. Defaults to true.
pBringToTop Whether or not to bring the window to the top. Defaults to true.
pShowSubwindows
Returns
A return code based on user input. Returns cxID_QUIT if the user presses ESC; otherwise, returns cxID_EXIT.
Reimplemented from cx::cxPanel.
References cx::bringToTop(), cx::cxID_EXIT, cx::cxWindow::cxTypeStr(), cx::cxWindow::getLeaveNow(), cx::cxWindow::getParent(), cx::cxWindow::getReturnCode(), cx::cxWindow::isEnabled(), cx::cxWindow::mIsModal, cx::cxWindow::runOnFocusFunction(), cx::cxWindow::runOnLeaveFunction(), cx::cxWindow::setReturnCode(), and show().
Referenced by cxNotebookRemoveWindowTest(), cxNotebookSwapTest(), cxNotebookTest1(), cxNotebookTest2(), and cxNotebookWithEmptyPanelTest().
showSubwindows()
void cx::cxNotebook::showSubwindows (bool pBringToTop = true, bool pShowSubwindows = true) override virtual
Shows the subwindows for the notebook. This is overidden here.
for screen optimization, since this method is called from
show(). It doesn't show the panels inside the notebook, which
are considered subwindows. This method will only draw the
subwindows that are outside the notebook.
Parameters
pBringToTop Whether or not to bring the subwindow to the top. Defaults to true.
pShowSubwindows Whether or not to show the subwindows for the subwindows. Defaults to true.
Reimplemented from cx::cxWindow.
References cx::cxWindow::getShowSubwinsForward(), cx::cxWindow::subWindows_begin(), cx::cxWindow::subWindows_end(), cx::cxWindow::subWindows_rbegin(), cx::cxWindow::subWindows_rend(), and windowIsInPanel().
Referenced by show().
swap() [1/3]
bool cx::cxNotebook::swap (const std::shared_ptr< cxWindow > & pWindow1, const std::shared_ptr< cxWindow > & pWindow2) override virtual
Swaps the order of 2 panels (by pointer). If both pointers are.
the same, or one or both don't exist in the panel, nothing will
be changed. This overrides the swap() inherited from cxPanel.
This does not refresh the screen.
Parameters
pWindow1 A pointer to the first window
pWindow2 A pointer to the second window
Returns
Whether or not the windows got swapped
Reimplemented from cx::cxPanel.
References swap().
swap() [2/3]
bool cx::cxNotebook::swap (cxWindow * pWindow1, cxWindow * pWindow2) override virtual
Swaps the order of 2 subwindows (by pointer). If both pointers.
are the same, or one or both don't exist in the panel, nothing
will be changed. This does not refresh the screen.
Parameters
pWindow1 A pointer to the first window
pWindow2 A pointer to the second window
Returns
Whether or not the windows got swapped
Reimplemented from cx::cxPanel.
References cx::cxPanel::mWindows, cx::cxPanel::numWindows(), and swap().
swap() [3/3]
bool cx::cxNotebook::swap (int pWindow1Index, int pWindow2Index) override virtual
Swaps the order of 2 panels (by index). If both indexes are.
the same, or one or both is out of bounds, nothing will be
changed. This overrides the swap() inherited from cxPanel.
This does not refresh the screen.
Parameters
pWindow1Index The index of the first window
pWindow2Index The index of the second window
Returns
Whether or not the windows got swapped
Reimplemented from cx::cxPanel.
References cx::cxPanel::numWindows(), and cx::cxPanel::swap().
Referenced by cxNotebookSwapTest(), swap(), and swap().
unhide()
void cx::cxNotebook::unhide (bool pUnhideSubwindows = true) override virtual
Un-hides the notebook.
Parameters
pUnhideSubwindows Whether or not to also unhide the subwindows (defaults to true)
Reimplemented from cx::cxPanel.
References cx::cxPanel::unhide().
windowIsInNotebook()
bool cx::cxNotebook::windowIsInNotebook (cxWindow * pWindow) const virtual
Returns whether a window exists in the notebook.
Parameters
pWindow A pointer to a window to add to the notebook
Returns
true if the window is in the notebook, or false if not
References cx::cxPanel::windowIsInPanel().
windowIsInPanel()
bool cx::cxNotebook::windowIsInPanel (const std::shared_ptr< cxWindow > & pWindow) const override virtual
Returns whether a cxWindow object is contained in the notebook.
Overridden from cxPanel to prevent hiding.
Parameters
pWindow A shared_ptr to a cxWindow object
Returns
Whether or not the cxWindow is contained in the notebook
Reimplemented from cx::cxPanel.
References cx::cxPanel::windowIsInPanel().
Referenced by showSubwindows().
The documentation for this class was generated from the following files:
/home/erico/projects/cxWidgets/src/cxNotebook.h
/home/erico/projects/cxWidgets/src/cxNotebook.cpp