cxWidgets: /home/erico/projects/cxWidgets/src/cxUnitTest.cpp File Reference
cxUnitTest.cpp File Reference
#include "cxBase.h"
#include "cxWindow.h"
#include "cxMenu.h"
#include "cxInput.h"
#include "cxMultiLineInput.h"
#include "cxForm.h"
#include <assert.h>
#include <unistd.h>
#include <iostream>
#include <string>
#include <vector>
Macros
#define TESTS
Functions
void wInfo (const cxWindow &w)
bool compareWin (int pRow, int pCol, int pHeight, int pWidth, const string &pTitle, const string &pMessage, const string &pStatus)
string someFunction (void *p1, void *p2)
int main (int argc, char *argv[])
Macro Definition Documentation
TESTS
#define TESTS
Function Documentation
compareWin()
bool compareWin (int pRow, int pCol, int pHeight, int pWidth, const string & pTitle, const string & pMessage, const string & pStatus)
References cxBase::messageBox().
Referenced by main().
main()
int main (int argc, char * argv[])
References cxTextValidator::addImpliedChars(), cxForm::append(), cxBase::bottom(), cxWindow::bottom(), cxWindow::centerCol(), cxWindow::centerRow(), cxBase::cleanup(), compareWin(), DEFAULT_HEIGHT, DEFAULT_WIDTH, eBS_NOBORDER, eBS_SINGLE_LINE, eHP_CENTER, eHP_LEFT, eHP_RIGHT, cxWindow::getBorderStyle(), cxWindow::getMessage(), cxForm::getParent(), cxWindow::getStatus(), cxForm::getStatus(), cxWindow::getTitle(), cxMultiLineInput::getValidatorStr(), cxMultiLineInput::getValue(), cxInput::getValue(), cxForm::getValue(), cxWindow::height(), cxBase::init(), cxForm::inputHeight(), cxForm::inputLabel(), cxForm::inputLeftCol(), cxForm::inputTopRow(), cxForm::inputWidth(), cxWindow::left(), cxForm::move(), cxForm::numInputs(), cxForm::remove(), cxBase::right(), cxWindow::right(), cxTextValidator::setTextStr(), cxMultiLineInput::setValidatorStr(), cxTextValidator::setValidatorStr(), cxInput::setValue(), cxForm::setValue(), cxMultiLineInput::setValue(), cxWindow::show(), cxTextValidator::textIsValid(), cxBase::top(), cxWindow::top(), and cxWindow::width().
someFunction()
string someFunction (void * p1, void * p2)
wInfo()
void wInfo (const cxWindow & w)
References cxWindow::bottom(), cxWindow::centerCol(), cxWindow::centerRow(), cxWindow::height(), cxWindow::left(), cxWindow::right(), cxWindow::top(), and cxWindow::width().