cxWidgets: /home/erico/projects/cxWidgets/examples/flashcard/main.cpp File Reference
main.cpp File Reference
#include "../../src/cxBase.h"
#include "FlashcardApp.h"
Functions
int main ()
Function Documentation
main()
int main ()
References cxBase::cleanup(), cxBase::init(), FlashcardApp::run(), and cxWindow::show().