cxWidgets: /home/erico/projects/cxWidgets/examples/spreadsheet/helpers.cpp File Reference
helpers.cpp File Reference
#include "helpers.h"
#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <fstream>
#include <algorithm>
#include <cctype>
#include <regex>
#include <memory>
#include <set>
#include <ctime>
#include <cmath>
Functions
int colLetterToIndex (const string &pCol)
string colIndexToLetter (int pCol)
bool parseCellRef (const string &pRef, int &pRow, int &pCol)
bool tryParseDouble (const string &pStr, double &pVal)
bool getCellNumericValue (cxGrid &pGrid, int pRow, int pCol, double &pVal)
bool parseRange (const string &pRange, int &pStartRow, int &pStartCol, int &pEndRow, int &pEndCol)
bool collectValues (cxGrid &pGrid, const string &pArgs, vector< double > &pValues, string &pErrorMsg)
bool evaluateFormula (cxGrid &pGrid, const string &pFormula, string &pResult, string &pErrorMsg)
bool saveToFile (cxGrid &pGrid, const string &pFilePath, string &pErrorMsg)
bool loadFromFile (cxGrid &pGrid, const string &pFilePath, string &pErrorMsg)
Function Documentation
colIndexToLetter()
string colIndexToLetter (int pCol)
Referenced by collectValues().
collectValues()
bool collectValues (cxGrid & pGrid, const string & pArgs, vector< double > & pValues, string & pErrorMsg)
References colIndexToLetter(), cxGrid::getCellValue(), parseCellRef(), parseRange(), and tryParseDouble().
Referenced by evaluateFormula().
colLetterToIndex()
int colLetterToIndex (const string & pCol)
Referenced by parseCellRef().
evaluateFormula()
bool evaluateFormula (cxGrid & pGrid, const string & pFormula, string & pResult, string & pErrorMsg)
References collectValues(), getCellNumericValue(), cxGrid::getCellValue(), parseCellRef(), and tryParseDouble().
getCellNumericValue()
bool getCellNumericValue (cxGrid & pGrid, int pRow, int pCol, double & pVal)
References cxGrid::getCellValue(), cxGrid::getNumCols(), cxGrid::getNumRows(), and tryParseDouble().
Referenced by evaluateFormula().
loadFromFile()
bool loadFromFile (cxGrid & pGrid, const string & pFilePath, string & pErrorMsg)
References cxGrid::getNumCols(), cxGrid::getNumRows(), cxGrid::setCellValue(), cxGrid::setNumCols(), and cxGrid::setNumRows().
parseCellRef()
bool parseCellRef (const string & pRef, int & pRow, int & pCol)
References colLetterToIndex().
Referenced by collectValues(), evaluateFormula(), and parseRange().
parseRange()
bool parseRange (const string & pRange, int & pStartRow, int & pStartCol, int & pEndRow, int & pEndCol)
References parseCellRef().
Referenced by collectValues().
saveToFile()
bool saveToFile (cxGrid & pGrid, const string & pFilePath, string & pErrorMsg)
References cxGrid::getCellValue(), cxGrid::getNumCols(), and cxGrid::getNumRows().
tryParseDouble()
bool tryParseDouble (const string & pStr, double & pVal)
Referenced by collectValues(), evaluateFormula(), and getCellNumericValue().