cxWidgets: /home/erico/projects/cxWidgets/examples/spreadsheet/helpers.h File Reference
helpers.h File Reference
#include <cxGrid.h>
#include <string>
#include <vector>
Functions
int colLetterToIndex (const std::string &pCol)
std::string colIndexToLetter (int pCol)
bool parseCellRef (const std::string &pRef, int &pRow, int &pCol)
bool tryParseDouble (const std::string &pStr, double &pVal)
bool getCellNumericValue (cxGrid &pGrid, int pRow, int pCol, double &pVal)
bool parseRange (const std::string &pRange, int &pStartRow, int &pStartCol, int &pEndRow, int &pEndCol)
bool collectValues (cxGrid &pGrid, const std::string &pArgs, std::vector< double > &pValues, std::string &pErrorMsg)
bool evaluateFormula (cxGrid &pGrid, const std::string &pFormula, std::string &pResult, std::string &pErrorMsg)
bool saveToFile (cxGrid &pGrid, const std::string &pFilePath, std::string &pErrorMsg)
bool loadFromFile (cxGrid &pGrid, const std::string &pFilePath, std::string &pErrorMsg)
Function Documentation
colIndexToLetter()
std::string colIndexToLetter (int pCol)
Referenced by collectValues().
collectValues()
bool collectValues (cxGrid & pGrid, const std::string & pArgs, std::vector< double > & pValues, std::string & pErrorMsg)
colLetterToIndex()
int colLetterToIndex (const std::string & pCol)
evaluateFormula()
bool evaluateFormula (cxGrid & pGrid, const std::string & pFormula, std::string & pResult, std::string & pErrorMsg)
getCellNumericValue()
bool getCellNumericValue (cxGrid & pGrid, int pRow, int pCol, double & pVal)
References cxGrid::getCellValue(), cxGrid::getNumCols(), cxGrid::getNumRows(), and tryParseDouble().
Referenced by evaluateFormula().
loadFromFile()
bool loadFromFile (cxGrid & pGrid, const std::string & pFilePath, std::string & pErrorMsg)
parseCellRef()
bool parseCellRef (const std::string & pRef, int & pRow, int & pCol)
parseRange()
bool parseRange (const std::string & pRange, int & pStartRow, int & pStartCol, int & pEndRow, int & pEndCol)
saveToFile()
bool saveToFile (cxGrid & pGrid, const std::string & pFilePath, std::string & pErrorMsg)
tryParseDouble()
bool tryParseDouble (const std::string & pStr, double & pVal)