cxWidgets: /home/erico/projects/cxWidgets/src/keys.cpp File Reference
keys.cpp File Reference
#include "cxBase.h"
#include "cxWindow.h"
#include "cxStringUtils.h"
#include <stdlib.h>
#include <iostream>
#include <string>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References cxBase::cleanup(), cxBase::getKeyStr(), cxBase::init(), and cxObject::UseColors().