cxWidgets: cxValidators Namespace Reference
cxValidators Namespace Reference
Functions
std::string intOnKeyValidator (void *theInput, void *clearOnSpace)
Validator for inputs that should only accept integers. This is.
std::string floatingPtOnKeyValidator (void *theInput, void *clearOnSpace)
Validator for inputs that should only accept floating-point.
bool isValidFloatingPtNumStr (const std::string &pNumStr)
Returns whether or not a string contains a valid floating-point.
bool isValidWholeNumStr (const std::string &pNumStr)
Returns whether or not a string contains a valid whole number. A.
Function Documentation
floatingPtOnKeyValidator()
string cxValidators::floatingPtOnKeyValidator (void * theInput, void * clearOnSpace)
Validator for inputs that should only accept floating-point.
numbers. This is meant to be used as an 'onKey' validator (to
validate on each keypress).
Parameters
theInput A pointer to the cxMultiLineInput to validate
clearOnSpace A pointer to a boolean (if non-null and true, will clear the input when the spacebar is pressed).
Returns
Blank string for valid data or a warning for invalid data.
References cxWindow::getLastKey(), cxMultiLineInput::getValue(), cxMultiLineInput::refreshValue(), and cxMultiLineInput::setValue().
Referenced by floatingPtValidateOnForm(), and cxMultiLineInput::onKeypress().
intOnKeyValidator()
string cxValidators::intOnKeyValidator (void * theInput, void * clearOnSpace)
Validator for inputs that should only accept integers. This is.
meant to be used as an 'onKey' validator (to validate on each
keypress).
Parameters
theInput A pointer to a cxMultiLineInput whose input to validate
clearOnSpace A pointer to a boolean (if non-null and true, will clear the input when the spacebar is pressed).
Returns
Blank string for valid data or a warning for invalid data.
References cxWindow::getLastKey(), cxMultiLineInput::getValue(), cxMultiLineInput::refreshValue(), and cxMultiLineInput::setValue().
Referenced by integerValidateOnForm(), and cxMultiLineInput::onKeypress().
isValidFloatingPtNumStr()
bool cxValidators::isValidFloatingPtNumStr (const std::string & pNumStr)
Returns whether or not a string contains a valid floating-point.
number. A blank string is considered valid.
Parameters
pNumStr A string to test
Returns
true if the string contains a valid floating-point number, or false if not.
References isValidFloatingPtNumStr().
Referenced by isValidFloatingPtNumStr().
isValidWholeNumStr()
bool cxValidators::isValidWholeNumStr (const std::string & pNumStr)
Returns whether or not a string contains a valid whole number. A.
blank string is considered valid.
Parameters
pNumStr A string to test
Returns
true if the string contains a valid whole number, or false if not.
References isValidWholeNumStr().
Referenced by isValidWholeNumStr().