cxWidgets: cxBase Namespace Reference
cxBase Namespace Reference
Contains some miscellaneous cxWidgets helper functions.
Functions
void init (bool pEnableMouse=true)
Initializes the cxWidgets library. This must be called before.
void cleanup ()
Cleans up the cxWidgets library. Must be called after all.
int top ()
Returns the top row # of the main screen.
int centerRow ()
Returns the center row # of the main screen.
int bottom ()
Returns the bottom row # of the main screen.
int left ()
Returns the leftmost column # of the main screen.
int centerCol ()
Returns the center column # of the main screen.
int right ()
Returns the rightmost column # of the main screen.
int width ()
Returns the width of the main screen.
int height ()
Returns the height of the main screen.
void getTermDimentions (int &pHeight, int &pWidth)
Returns the terminal's current height & width.
bool resizeTerm (int pNewHeight, int pNewWidth)
Resizes the terminal screen.
e_cxColors getDefaultMessageColor ()
Returns the default message color.
void setDefaultMessageColor (e_cxColors pColor)
Sets the default message color.
e_cxColors getDefaultTitleColor ()
Returns the default title color.
void setDefaultTitleColor (e_cxColors pColor)
Sets the default title color.
e_cxColors getDefaultStatusColor ()
Returns the default status color.
void setDefaultStatusColor (e_cxColors pColor)
Sets the default status color.
e_cxColors getDefaultBorderColor ()
Returns the default border color.
void setDefaultBorderColor (e_cxColors pColor)
Sets the default border color.
void messageBox (int pRow, int pCol, int pHeight, int pWidth, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus="", eBorderStyle pBorderStyle=eBS_SINGLE_LINE)
Shows a message box.
void messageBox (int pRow, int pCol, const std::string &pTitle, const std::string &pMessage, const std::string &pStatus)
Shows a message box automatically setting its height & width.
void messageBox (int pRow, int pCol, const std::string &pMessage)
Shows a message box, automatically setting its height & width.
void messageBox (const std::string &pTitle, const std::string &pMessage, const std::string &pStatus)
Shows a message box.
void messageBox (const std::string &pMessage, const std::string &pStatus)
Shows a message box.
void messageBox (const std::string &pMessage, e_cxColors pMessageColor=getDefaultMessageColor(), attr_t pMessageAttr=A_NORMAL, e_cxColors pTitleColor=getDefaultTitleColor(), e_cxColors pStatusColor=getDefaultStatusColor(), e_cxColors pBorderColor=getDefaultBorderColor())
Shows a message box.
void messageDialog (const std::string &pMessage)
Shows a message dialog (a message box with an OK button)
void messageDialog (const std::list< std::string > &pMessages)
Shows a message dialog (a message box with an OK button)
void splash (const std::string &pTitle, const std::string &pMessage, int pSleep)
Shows a splash message.
void splash (const std::string &pMessage, int pSleep)
Shows a splash message.
void eraseScreen ()
Erases the screen.
void updateWindows ()
Updates (refreshes) all windows on the screen.
bool isFunctionKey (int pKey)
Returns whether a key is a function key, pageDown, or pageUp (these keys are tested by cxInput and cxMultiLineInput in their input loops).
bool toggleCursor (bool pToggleCursor)
Enables or disables the display of the cursor.
std::string getTermType ()
Returns a string representing the terminal type. This is the.
bool colorIsBright (e_cxColors pColor)
Returns whether a color has the brightness bit set.
int countHotkeys (const std::string &pStr)
Counts the number of hotkeys in a string. This is useful when working with cxMenu, which can contain items with hotkeys.
std::string stringWithoutHotkeyChars (const std::string &pStr)
Takes a string and returns a version without the & characters.
unsigned visualStrLen (const std::string &pStr)
Returns the length of a string without its hotkey characters -.
std::string bringToTop (void *theWindow, void *unused)
Brings a cxWindow to the top of the stack. Doesn't refresh.
std::string cxFormShowModal (void *theForm, void *unused)
Runs showModal() on a cxForm and returns the result. This.
std::string cxMenuShowModal (void *theMenu, void *unused)
Runs showModal() on a cxMenu and returns the result. This.
std::string noOp (void *p1, void *p2)
Does nothing. Can be used, for example, as an event function.
std::string noOp (void *p1, void *p2, void *p3, void *p4)
Does nothing. Can be used, for example, as an event function.
int runSystemCmd (const std::string &pCmd)
Runs a command on the system, calling the system() function.
void writeText (int pRow, int pCol, const std::string &pText, attr_t pAttr=A_NORMAL, e_cxColors pColor=eGRAY_BLACK)
Writes text on the screen.
void getHotkeyChars (const std::string &pStr, std::set< char > &pHotkeys, bool pConvertCase=false, bool pToUpper=false)
Scans a string for hotkeys (characters preceeded by an ampersand)
void showAllWindows (bool pBringToTop=false)
Shows all windows currently in use everywhere, from the.
cxWindow * getTopWindow ()
Gets a pointer to the topmost cxWindow on the stack. This could.
cxWindow * getBottomWindow ()
Gets a pointer to the bottom-most cxWindow on the stack. This could.
std::string getKeyStr (int pKey)
Returns a string version of a key.
std::string getMouseStateStr (int pMouseState)
Returns a string version of a mouse state.
std::string getReturnCodeStr (long pReturnCode)
Returns a string version of a return code.
std::string getInputOptionStr (eInputOptions pInputOption)
Returns a string version of a value from the eInputOptions.
std::string getBorderStyleStr (eBorderStyle pBorderStyle)
Returns a string version of an eBorderStyle value.
std::string getInputTypeStr (eInputTypes pInputType)
Returns a string version of an eInputType value.
void signalHandler (int pSignal)
Handler for system signals.
bool promptYesNo (const std::string &pMessage, const std::string &pTitle="", long pButtons=cxYES_NO)
Prompts the user with a cxMessageDialog for a yes/no choice.
bool cxInitialized ()
Returns whether or not cxWidgets has been initialized.
void addAttr (e_WidgetItems pItem, attr_t pAttr)
Adds an ncurses attribute to use for one of the items in the.
void setAttr (e_WidgetItems pItem, attr_t pAttr)
Sets the ncurses attribute to use for one of the items in the.
void removeAttr (e_WidgetItems pItem, attr_t pAttr)
Removes an ncurses attribute from one of the item lists.
void removeAttrs (e_WidgetItems pItem)
Removes all attributes for a given window item.
void getAttrs (e_WidgetItems pItem, std::set< attr_t > &pAttrs)
Returns the set of ncurses attributes for a given item.
bool hasAttr (e_WidgetItems pItem, attr_t pAttr)
Determine if the widget has an attribute "set".
void enableAttrs (WINDOW *pWindow, e_WidgetItems pItem)
Enables all of a set of attributes for a given item type on an.
void disableAttrs (WINDOW *pWindow, e_WidgetItems pItem)
Disables all of a set of attributes for a given item type on an.
attr_t getAttr (const std::string &pAttr)
Figure out the appropriate ncurses attr_t from a "string".
std::string getAttrStr (attr_t pAttr)
Returns a string version of an ncurses attribute.
std::string getWidgetItemStr (e_WidgetItems pItem)
Returns a string version of an e_WidgetItems value.
void setMenuClearKeywordKey (int pKey)
Sets the key that should be used to clear the "Keyword" input.
int getMenuClearKeywordKey ()
Returns the key that is set to clear the "Keyword" input for.
std::string dump (bool pFancy=false, const std::string &pFilename="")
dump the contents to the screen to a file
bool isNavKey (int pKey)
Returns whether a key is a navigational key, according to.
void addNavKey (int pKey)
Add a key to be considered a "navigational" key. The key will.
void removeNavKey (int pKey)
Removes a key from cxBase's list of "navigational" keys.
std::string getString (int pRow, int pCol, int pNumber, WINDOW *pWin=nullptr)
Get the contents of the screen (for debugging/testing)
bool findString (const std::string &pSearch, int &pRow, int &pCol, WINDOW *pWin=nullptr)
Look for a string on the screen (for debugging/testing)
Variables
bool mInitialized = false
set< attr_t > mMessageAttrs
set< attr_t > mTitleAttrs
set< attr_t > mStatusAttrs
set< attr_t > mBorderAttrs
set< attr_t > mHotkeyAttrs
set< attr_t > mMenuSelectionAttrs
set< attr_t > mLabelAttrs
set< attr_t > mDataReadonlyAttrs
set< attr_t > mDataEditableAttrs
attr_t mLabelAttr =A_DIM
attr_t mDataEditableAttr =A_REVERSE
attr_t mDataReadonlyAttr =A_BOLD
int mMenuClearKeywordKey = KEY_F(10)
attr_t mMenuSelectionAttr =A_REVERSE
set< int > mNavKeys
e_cxColors mDefaultMessageColor = eGRAY_BLUE
e_cxColors mDefaultTitleColor = eWHITE_BLUE
e_cxColors mDefaultStatusColor = eYELLOW_BLUE
e_cxColors mDefaultBorderColor = eGRAY_BLUE
static const std::string termType = getTermType()
Contains the terminal type string.
Detailed Description
Contains some miscellaneous cxWidgets helper functions.
Function Documentation
addAttr()
void cxBase::addAttr (e_WidgetItems pItem, attr_t pAttr)
Adds an ncurses attribute to use for one of the items in the.
window (see the e_WidgetItems enumeration).
Parameters
pItem The item type to add the attribute for (see the e_WidgetItems enumeration).
pAttr The ncurses atribute to add.
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, eTITLE, mBorderAttrs, mDataEditableAttrs, mDataReadonlyAttrs, mHotkeyAttrs, mLabelAttrs, mMenuSelectionAttrs, mMessageAttrs, mStatusAttrs, and mTitleAttrs.
Referenced by cxWindow::setStatusColor().
addNavKey()
void cxBase::addNavKey (int pKey)
Add a key to be considered a "navigational" key. The key will.
be added to cxBase's set of navigational keys.
Parameters
pKey The key to be added
References mNavKeys.
bottom()
int cxBase::bottom ()
Returns the bottom row # of the main screen.
Returns
The bottom row # of the main screen
Referenced by cxWindow::alignVert(), cxWindow::info(), cxWindow::init(), and main().
bringToTop()
string cxBase::bringToTop (void * theWindow, void * unused)
Brings a cxWindow to the top of the stack. Doesn't refresh.
its subwindows. This is designed to be used as an event
function in cxWidgets (i.e., for when the user presses a certain
key, etc.).
Parameters
theWindow A pointer to a cxWindow
unused Not used
Returns
A blank string
References cxWindow::show().
centerCol()
int cxBase::centerCol ()
Returns the center column # of the main screen.
Returns
The center column # of the main screen
Referenced by cxWindow::alignHoriz().
centerRow()
int cxBase::centerRow ()
Returns the center row # of the main screen.
Returns
The center row # of the main screen
Referenced by cxWindow::alignVert(), and cxWindow::getRowColBasedOn().
cleanup()
void cxBase::cleanup ()
Cleans up the cxWidgets library. Must be called after all.
screen-related cxWidgets objects & functions are done being used.
References cxInitialized(), and mInitialized.
Referenced by cxWindowSizeTest(), and main().
colorIsBright()
bool cxBase::colorIsBright (e_cxColors pColor)
Returns whether a color has the brightness bit set.
Parameters
pColor The color to test
Returns
Whether or not the color has the brightness bit set.
References cxCOLOR_BRIGHT.
Referenced by cxWindow::setElementColor().
countHotkeys()
int cxBase::countHotkeys (const std::string & pStr)
Counts the number of hotkeys in a string. This is useful when working with cxMenu, which can contain items with hotkeys.
Parameters
pStr The string for which to count hotkeys
Returns
The number of hotkeys in pStr
cxFormShowModal()
string cxBase::cxFormShowModal (void * theForm, void * unused)
Runs showModal() on a cxForm and returns the result. This.
function was designed to be used as an event function in
cxWidgets, which is why it returns the value as a string and
takes 2 void pointers.
Parameters
theForm The cxForm to show modally
unused Not used
Returns
The return value of the form's showModal(), as a string, or the string value of cxID_QUIT on error.
References cxID_QUIT, and cxForm::showModal().
cxInitialized()
bool cxBase::cxInitialized ()
Returns whether or not cxWidgets has been initialized.
Returns
Whether or not cxWidgets has been initialized.
References mInitialized.
Referenced by cleanup(), cxWindowSizeTest(), eraseScreen(), showAllWindows(), updateWindows(), cxForm::~cxForm(), and cxWindow::~cxWindow().
cxMenuShowModal()
string cxBase::cxMenuShowModal (void * theMenu, void * unused)
Runs showModal() on a cxMenu and returns the result. This.
function was designed to be used as an event function in
cxWidgets, which is why it returns the value as a string and
takes 2 void pointers.
Parameters
theMenu The cxMenu to show modally
unused Not used
Returns
The return value of the form's showModal(), as a string, or the string value of cxID_QUIT on error.
References cxID_QUIT, and cxMenu::showModal().
disableAttrs()
void cxBase::disableAttrs (WINDOW * pWindow, e_WidgetItems pItem)
Disables all of a set of attributes for a given item type on an.
ncurses window.
Parameters
pWindow A pointer to the ncurses window for which to disable the attributes.
pItem The item type to retrieve attributes for (see the e_cxWidgetItems enumeration).
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, eTITLE, mBorderAttrs, mDataEditableAttrs, mDataReadonlyAttrs, mHotkeyAttrs, mLabelAttrs, mMenuSelectionAttrs, mMessageAttrs, mStatusAttrs, and mTitleAttrs.
Referenced by cxWindow::disableAttrs(), cxInput::disableAttrs(), and cxMenu::disableAttrs().
dump()
std::string cxBase::dump (bool pFancy = false, const std::string & pFilename = "")
dump the contents to the screen to a file
Parameters
pFancy - print fields that have underlines as underscores '_'.
pFilename to write to
Returns
string "" on success otherwise message
Referenced by borderlessForm(), and testFormReadOnly().
enableAttrs()
void cxBase::enableAttrs (WINDOW * pWindow, e_WidgetItems pItem)
Enables all of a set of attributes for a given item type on an.
ncurses window.
Parameters
pWindow A pointer to the ncurses window for which to enable the attributes.
pItem The item type to retrieve attributes for (see the e_cxWidgetItems enumeration).
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, eTITLE, mBorderAttrs, mDataEditableAttrs, mDataReadonlyAttrs, mHotkeyAttrs, mLabelAttrs, mMenuSelectionAttrs, mMessageAttrs, mStatusAttrs, and mTitleAttrs.
Referenced by cxWindow::enableAttrs(), cxInput::enableAttrs(), and cxMenu::enableAttrs().
eraseScreen()
void cxBase::eraseScreen ()
Erases the screen.
References cxInitialized().
findString()
bool cxBase::findString (const std::string & pSearch, int & pRow, int & pCol, WINDOW * pWin = nullptr)
Look for a string on the screen (for debugging/testing)
Parameters
pSearch string to search for
pRow the row it was found on
pCol the column it was found on
pWin A pointer to an ncurses window structure to get contents from. If this is nullptr, curscr will be used.
Returns
bool true if we were able to find the string, false otherwise
getAttr()
attr_t cxBase::getAttr (const std::string & pAttr)
Figure out the appropriate ncurses attr_t from a "string".
see "man curs_attr"
Parameters
pAttr "NORMAL", "BOLD", etc..
Returns
attr_t that corresponds with that string
Referenced by main().
getAttrs()
void cxBase::getAttrs (e_WidgetItems pItem, std::set< attr_t > & pAttrs)
Returns the set of ncurses attributes for a given item.
Parameters
pItem The item type to retrieve attributes for (see the e_WidgetItems enumeration).
pAttrs This will contain the attributes for the item.
Referenced by hasAttr().
getAttrStr()
string cxBase::getAttrStr (attr_t pAttr)
Returns a string version of an ncurses attribute.
Parameters
pAttr An ncurses attribute
Returns
A descriptive string version of the attribute
getBorderStyleStr()
string cxBase::getBorderStyleStr (eBorderStyle pBorderStyle)
Returns a string version of an eBorderStyle value.
Parameters
pBorderStyle A member of the eBorderStyle enumeration
Returns
A string representation of the eBorderStyle value
References eBS_NOBORDER, eBS_SINGLE_LINE, eBS_SPACE, and cxStringUtils::toString().
getBottomWindow()
cxWindow * cxBase::getBottomWindow ()
Gets a pointer to the bottom-most cxWindow on the stack. This could.
return nullptr, if it can't get to the topmost window.
Returns
A pointer to the bottom-most cxWindow on the stack, or nullptr if there is none.
getDefaultBorderColor()
e_cxColors cxBase::getDefaultBorderColor ()
Returns the default border color.
Returns
The default border color
References mDefaultBorderColor.
Referenced by cxWindow::init().
getDefaultMessageColor()
e_cxColors cxBase::getDefaultMessageColor ()
Returns the default message color.
Returns
The default message color
References mDefaultMessageColor.
Referenced by cxWindow::init().
getDefaultStatusColor()
e_cxColors cxBase::getDefaultStatusColor ()
Returns the default status color.
Returns
The default status color
References mDefaultStatusColor.
Referenced by cxWindow::init().
getDefaultTitleColor()
e_cxColors cxBase::getDefaultTitleColor ()
Returns the default title color.
Returns
The default title color
References mDefaultTitleColor.
Referenced by cxWindow::init().
getHotkeyChars()
void cxBase::getHotkeyChars (const std::string & pStr, std::set< char > & pHotkeys, bool pConvertCase = false, bool pToUpper = false)
Scans a string for hotkeys (characters preceeded by an ampersand)
and adds the hotkey characters to a collection.
Parameters
pStr The string to scan
pHotkeys The collection to which to add hotkey characters
pConvertCase Whether or not to convert the case of the hotkeys (defaults to false)
ptoUpper If pConvertCase is true, this parameter specifies whether or not to convert the characters to upper case. If true, the characters will be converted to upper-case; if false, they will be converted to lowercase (if pConvertCase is true).
getInputOptionStr()
string cxBase::getInputOptionStr (eInputOptions pInputOption)
Returns a string version of a value from the eInputOptions.
enumeration.
Parameters
pInputOption A member of the eInputOptions enumeration
Returns
A string representation of pInputOption
References eINPUT_EDITABLE, eINPUT_READONLY, and cxStringUtils::toString().
getInputTypeStr()
string cxBase::getInputTypeStr (eInputTypes pInputType)
Returns a string version of an eInputType value.
Parameters
pInputType A member of the eInputType enumeration
Returns
A string representation of the value
References eINPUT_TYPE_NUMERIC_FLOATING_PT, eINPUT_TYPE_NUMERIC_WHOLE, eINPUT_TYPE_TEXT, and cxStringUtils::toString().
getKeyStr()
string cxBase::getKeyStr (int pKey)
Returns a string version of a key.
Parameters
pKey The key to convert to a string
Returns
A string representation of the key
References BACKSPACE, CTRL_F1, CTRL_F10, CTRL_F11, CTRL_F12, CTRL_F2, CTRL_F3, CTRL_F4, CTRL_F5, CTRL_F6, CTRL_F7, CTRL_F8, CTRL_F9, CTRL_G, CTRL_SHIFT_F1, CTRL_SHIFT_F10, CTRL_SHIFT_F11, CTRL_SHIFT_F12, CTRL_SHIFT_F2, CTRL_SHIFT_F3, CTRL_SHIFT_F4, CTRL_SHIFT_F5, CTRL_SHIFT_F6, CTRL_SHIFT_F7, CTRL_SHIFT_F8, CTRL_SHIFT_F9, ENTER, ESC, KEY_END2, KEY_END3, NOKEY, PAGE_DOWN, PAGE_UP, SHIFT_F1, SHIFT_F10, SHIFT_F11, SHIFT_F12, SHIFT_F2, SHIFT_F3, SHIFT_F4, SHIFT_F5, SHIFT_F52, SHIFT_F6, SHIFT_F62, SHIFT_F7, SHIFT_F8, SHIFT_F9, SHIFT_TAB, TAB, and cxStringUtils::toString().
Referenced by cxFormNavKeys(), cxWindow::getExitKeyListString(), cxWindow::getExitKeyStrings(), cxForm::getExtendedHelpKeyStrings(), cxMultiLineInput::getExtendedHelpKeyStrings(), cxWindow::getFunctionKeyStrings(), cxForm::getNavKeyStrings(), cxWindow::getQuitKeyListString(), cxWindow::getQuitKeyStrings(), and main().
getMenuClearKeywordKey()
int cxBase::getMenuClearKeywordKey ()
Returns the key that is set to clear the "Keyword" input for.
cxMenu item searching.
Returns
The key that is set to clear the "Keyword" input for cxMenu item searching.
References mMenuClearKeywordKey.
getMouseStateStr()
string cxBase::getMouseStateStr (int pMouseState)
Returns a string version of a mouse state.
Parameters
pMouseState The mouse state to convert to a string
Returns
A string representation of the mouse state
References BUTTON1_CLICKED, BUTTON1_DOUBLE_CLICKED, BUTTON1_PRESSED, BUTTON1_RELEASED, BUTTON1_TRIPLE_CLICKED, BUTTON2_CLICKED, BUTTON2_DOUBLE_CLICKED, BUTTON2_PRESSED, BUTTON2_RELEASED, BUTTON2_TRIPLE_CLICKED, BUTTON3_CLICKED, BUTTON3_DOUBLE_CLICKED, BUTTON3_PRESSED, BUTTON3_RELEASED, BUTTON3_TRIPLE_CLICKED, BUTTON4_CLICKED, BUTTON4_DOUBLE_CLICKED, BUTTON4_PRESSED, BUTTON4_RELEASED, BUTTON4_TRIPLE_CLICKED, and cxStringUtils::toString().
Referenced by cxWindow::getMouseStateStr().
getReturnCodeStr()
string cxBase::getReturnCodeStr (long pReturnCode)
Returns a string version of a return code.
Parameters
pReturnCode The return code to convert to a string
Returns
A string representation of the return code
References cxFIRST_AVAIL_RETURN_CODE, cxID_CANCEL, cxID_EXIT, cxID_OK, cxID_QUIT, and cxStringUtils::toString().
Referenced by cxPanelTest(), cxWindowWithFunctionKeys(), enableDisableForm(), getMenuItemIDStr(), and inputQuitKeysOnForm().
getString()
string cxBase::getString (int pRow, int pCol, int pNumber, WINDOW * pWin = nullptr)
Get the contents of the screen (for debugging/testing)
Parameters
pRow the starting row
pCol the starting column
pNumber number of characters to get
pWin A pointer to an ncurses window structure to get contents from. If this is nullptr, curscr will be used.
Returns
the "string" value of the screen
Referenced by cxWindow::getString().
getTermDimentions()
void cxBase::getTermDimentions (int & pHeight, int & pWidth)
Returns the terminal's current height & width.
Parameters
pHeight (OUT) This will store the terminal's current height.
pWidth (OUT) This will store the terminal's current width.
References height(), and width().
getTermType()
string cxBase::getTermType ()
Returns a string representing the terminal type. This is the.
value of the environment variable TERM.
Returns
A string representing the terminal type, i.e. "xterm", "wy50", etc.
getTopWindow()
cxWindow * cxBase::getTopWindow ()
Gets a pointer to the topmost cxWindow on the stack. This could.
return nullptr, if it can't get to the topmost window.
Returns
A pointer to the topmost cxWindow on the stack, or nullptr if there is none.
getWidgetItemStr()
string cxBase::getWidgetItemStr (e_WidgetItems pItem)
Returns a string version of an e_WidgetItems value.
Parameters
pItem A member of the e_WidgetItems enumeration (see cxWidgetItems.h)
Returns
The string version of the item
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, and eTITLE.
hasAttr()
bool cxBase::hasAttr (e_WidgetItems pItem, attr_t pAttr)
Determine if the widget has an attribute "set".
Parameters
pItem The item type to check (see e_WidgetItems)
pAttr The attribute. (i.e., A_NORMAL, etc.)
Returns
true if the widget has that attribute
References getAttrs().
Referenced by cxMessageDialog::setFocus().
height()
int cxBase::height ()
Returns the height of the main screen.
Returns
The height of the main screen
Referenced by cxPanel_cxMenuUpArrowLeave(), cxPanelTest2(), cxWindowBorderTest(), getTermDimentions(), cxWindow::info(), cxWindow::init(), main(), cxMenu::resize(), cxWindow::resize(), cxMultiLineInput::resize(), and setValFunc().
init()
void cxBase::init (bool pEnableMouse = true)
Initializes the cxWidgets library. This must be called before.
any screen-related cxWidgets library objects & functions are used.
Parameters
pEnableMouse Whether or not to enable mouse input. Defaults to true. Note that if the version of ncurses on the system doesn't support the mouse at the time when cxWidgets is compiled, the mouse will not be enabled, even if this parameter is true.
References eBLACK_BLACK, eBLACK_BLUE, eBLACK_CYAN, eBLACK_GREEN, eBLACK_RED, eBLACK_WHITE, eBLUE_BLACK, eBLUE_BLUE, eBLUE_CYAN, eBLUE_GREEN, eBLUE_RED, eBLUE_WHITE, eBROWN_BLACK, eBROWN_BLUE, eBROWN_CYAN, eBROWN_GREEN, eBROWN_RED, eBROWN_WHITE, eBRTBLUE_BLACK, eBRTBLUE_BLUE, eBRTBLUE_CYAN, eBRTBLUE_GREEN, eBRTBLUE_RED, eBRTBLUE_WHITE, eBRTCYAN_BLACK, eBRTCYAN_BLUE, eBRTCYAN_CYAN, eBRTCYAN_GREEN, eBRTCYAN_RED, eBRTCYAN_WHITE, eBRTGREEN_BLACK, eBRTGREEN_BLUE, eBRTGREEN_CYAN, eBRTGREEN_GREEN, eBRTGREEN_RED, eBRTGREEN_WHITE, eBRTMAGENTA_BLACK, eBRTMAGENTA_BLUE, eBRTMAGENTA_CYAN, eBRTMAGENTA_GREEN, eBRTMAGENTA_RED, eBRTMAGENTA_WHITE, eBRTRED_BLACK, eBRTRED_BLUE, eBRTRED_CYAN, eBRTRED_GREEN, eBRTRED_RED, eBRTRED_WHITE, eCYAN_BLACK, eCYAN_BLUE, eCYAN_CYAN, eCYAN_GREEN, eCYAN_RED, eCYAN_WHITE, eGRAY_BLACK, eGRAY_BLUE, eGRAY_CYAN, eGRAY_GREEN, eGRAY_RED, eGRAY_WHITE, eGREEN_BLACK, eGREEN_BLUE, eGREEN_CYAN, eGREEN_GREEN, eGREEN_RED, eGREEN_WHITE, eMAGENTA_BLACK, eMAGENTA_BLUE, eMAGENTA_CYAN, eMAGENTA_GREEN, eMAGENTA_RED, eMAGENTA_WHITE, eRED_BLACK, eRED_BLUE, eRED_CYAN, eRED_GREEN, eRED_RED, eRED_WHITE, eWHITE_BLACK, eWHITE_BLUE, eWHITE_CYAN, eWHITE_GREEN, eWHITE_RED, eWHITE_WHITE, eYELLOW_BLACK, eYELLOW_BLUE, eYELLOW_CYAN, eYELLOW_GREEN, eYELLOW_RED, eYELLOW_WHITE, mHotkeyAttrs, mInitialized, mMenuSelectionAttrs, mNavKeys, PAGE_DOWN, PAGE_UP, SHIFT_TAB, signalHandler(), and TAB.
Referenced by cxWindowSizeTest(), and main().
isFunctionKey()
bool cxBase::isFunctionKey (int pKey)
Returns whether a key is a function key, pageDown, or pageUp (these keys are tested by cxInput and cxMultiLineInput in their input loops).
Parameters
pKey The key to be checked
Returns
Whether or not the key is a function key, pageDown, or pageUp
isNavKey()
bool cxBase::isNavKey (int pKey)
Returns whether a key is a navigational key, according to.
cxBase's list of navigational keys. The defaults are the arrow
keys, pageUp, pageDown, tab, and shift-tab. cxMultiLineInput
has its own list of navigational keys, but this may be useful
for other things.
Parameters
pKey The key to test
Returns
Whether or not the key is a navigational key
References mNavKeys.
left()
int cxBase::left ()
Returns the leftmost column # of the main screen.
Returns
The leftmost column # of the main screen
Referenced by cxWindow::alignHoriz(), and cxWindow::info().
messageBox() [1/6]
void cxBase::messageBox (const std::string & pMessage, const std::string & pStatus)
Shows a message box.
Parameters
pMessage Message of message box
pStatus Status of message box. Defaults to blank.
References messageBox().
messageBox() [2/6]
void cxBase::messageBox (const std::string & pMessage, e_cxColors pMessageColor = getDefaultMessageColor(), attr_t pMessageAttr = A_NORMAL, e_cxColors pTitleColor = getDefaultTitleColor(), e_cxColors pStatusColor = getDefaultStatusColor(), e_cxColors pBorderColor = getDefaultBorderColor())
Shows a message box.
Parameters
pMessage The message for the message box
pMessageColor The color for the message portion
pMessageAttr The attribute for the message portion
pTitleColor The color for the title
pStatusColor The color for the status
pBorderColor The color for the border
References messageBox().
messageBox() [3/6]
void cxBase::messageBox (const std::string & pTitle, const std::string & pMessage, const std::string & pStatus)
Shows a message box.
Parameters
pTitle title of message box
pMessage message of message box
pStatus status of message box
References messageBox().
messageBox() [4/6]
void cxBase::messageBox (int pRow, int pCol, const std::string & pMessage)
Shows a message box, automatically setting its height & width.
Parameters
pRow Row of upper-left corner
pCol Column of upper-left corner
pMessage The message to appear in the box
References messageBox().
messageBox() [5/6]
void cxBase::messageBox (int pRow, int pCol, const std::string & pTitle, const std::string & pMessage, const std::string & pStatus)
Shows a message box automatically setting its height & width.
Parameters
pRow row of upper-left corner
pCol column of upper-left corner
pTitle title of message box
pMessage message of message box
pStatus status of message box
References messageBox().
messageBox() [6/6]
void cxBase::messageBox (int pRow, int pCol, int pHeight, int pWidth, const std::string & pTitle, const std::string & pMessage, const std::string & pStatus = "", eBorderStyle pBorderStyle = eBS_SINGLE_LINE)
Shows a message box.
Parameters
pRow row of upper-left corner
pCol column of upper-left corner
pHeight height of message box
pWidth width of message box
pTitle title of message box
pMessage message of message box
pStatus status of message box
pBorderStyle The type of border to use for the message box - Defaults to eBS_SINGLE_LINE
References messageBox().
Referenced by allFormInputsGoReadOnly(), buttonClickFunction(), comboBox(), comboBoxMenuDisable(), compareWin(), cxButtonOnClick(), cxComboBoxNotEditableMenuEnabled(), cxFormAppendComboBoxPair(), cxFormAppendPair(), cxFormExtendedHelpKey(), cxFormMultiLineInputFunctionKeyNoValidator(), cxFormNavKeys(), cxFormNoQuit(), cxFormStartAtFirstInput(), cxInputBorderChange(), cxInputMasking(), cxMenuAltItemText(), cxMenuMiscTests(), cxMenuNoMoreSelectableItemsWhileModal(), cxMenuNoQuit(), cxMenuResize(), cxMenuScrolling(), cxMenuWithMultipleItemHotkeys(), cxMultiLineInputBorderChange(), cxMultiLineInputExtendedHelpColorsAndAttrs(), cxMultiLineInputExtendedHelpKey(), cxMultiLineInputForceUpper(), cxMultiLineInputFunctionKeyNoValidator(), cxMultiLineInputMasking(), cxMultiLineInputMaxInputLength(), cxMultiLineInputNonBlank(), cxMultiLineInputNumericFloatingPt(), cxMultiLineInputNumericFloatingPtWithRange(), cxMultiLineInputNumericWhole(), cxMultiLineInputNumericWholeWithRange(), cxMultiLineInputSetValue(), cxMultiLineInputTextValidation(), cxMultiLineInputTextValidationAutoCompletion(), cxMultiLineInputTextValidationNonBlankForceUpper(), cxPanel_cxMenuUpArrowLeave(), cxPanelGetLastWindow(), cxPanelTest(), cxSearchPanelResize(), cxSearchPanelTest(), cxWindowAlignTest(), cxWindowSizeTest(), cxWindowWithFunctionKeys(), demoPanels(), cxForm::doInputLoop(), cxMultiLineInput::doInputLoop(), cxMultiForm::doInputLoop(), doMenu(), enableDisableForm(), floatingPtValidate(), form(), formChangeInputFocusWhileModal(), formDataChanged(), formFunctionKeyNoOnLeave(), formFunctionKeys(), formUpArrowFunction(), formWithFKeys(), formWithInputValueValidator(), genericMessageFunction(), genericMessageFunction_1str(), getFormKeys(), hello(), inputQuitKeysOnForm(), inputsWithFKeys(), cxMultiLineInput::inputValidator(), integerValidate(), keyFunctionAutoExitOnLastFormInput(), menuItemWithMultipleHotkeys(), menuOnEnter(), messageBox(), messageBox(), messageBox(), messageBox(), messageBox(), messageBox(), mouseFunction(), msgBox1(), msgBox2(), msgBox3(), msgBox4(), msgCancel(), msgNo(), msgNoYes(), msgOK(), msgOKCancel(), msgYes(), msgYesNo(), multiFormWithDisabledSubform(), multiLineInputResize(), onFocus(), onFocusWinForCxPanelGetLastPage(), onLeave(), sayHello(), sayHello2(), setInputLabel(), showAMessageBox(), someFunction(), someFunction3(), someWeirdFunc(), testBoxSuccess(), testInput1(), testInputValidator(), testKeyFunction(), testMenu1(), testOnFocusFunction(), testOnLeaveFunction(), unselectableMenuItem(), and windowFunctionKeyNoOnLeave().
messageDialog() [1/2]
void cxBase::messageDialog (const std::list< std::string > & pMessages)
Shows a message dialog (a message box with an OK button)
Parameters
pMessages message of message dialog
messageDialog() [2/2]
void cxBase::messageDialog (const std::string & pMessage)
Shows a message dialog (a message box with an OK button)
Parameters
pMessage message of message dialog
Referenced by cxMenuAssignment(), cxWindowAssignment(), cxWindowCopyConstructor(), and demoPanels().
noOp() [1/2]
string cxBase::noOp (void * p1, void * p2)
Does nothing. Can be used, for example, as an event function.
on a cxForm when you want to have a keypress exit the form.
Parameters
p1 Not used
p2 Not used
Returns
A blank string
Referenced by formUpArrowFunction().
noOp() [2/2]
string cxBase::noOp (void * p1, void * p2, void * p3, void * p4)
Does nothing. Can be used, for example, as an event function.
on a cxForm when you want to have a keypress exit the form.
Parameters
p1 Not used
p2 Not used
p3 Not used
p4 Not used
Returns
An empty string
promptYesNo()
bool cxBase::promptYesNo (const std::string & pMessage, const std::string & pTitle = "", long pButtons = cxYES_NO)
Prompts the user with a cxMessageDialog for a yes/no choice.
Returns their choice as a boolean.
Parameters
pMessage The message to put in the message dialog
pTitle The title for the message dialog. Defaults to a blank string.
pButtons Specifies the buttons to appear on the dialog. Defaults to cxYES_NO (to display yes & no buttons). Note that you can use multiple values listed in cxMessageDialogStyles.h ORed together. For example, cxYES_NO | cxNO_DEFAULT would display Yes and No buttons and default to No.
Returns
True if the user chose yes, or false otherwise.
removeAttr()
void cxBase::removeAttr (e_WidgetItems pItem, attr_t pAttr)
Removes an ncurses attribute from one of the item lists.
Parameters
pItem The item type to remove the attribute for (see the e_WidgetItems enumeration).
pAttr The ncurses attribute to remove
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, eTITLE, mBorderAttrs, mDataEditableAttrs, mDataReadonlyAttrs, mHotkeyAttrs, mLabelAttrs, mMenuSelectionAttrs, mMessageAttrs, mStatusAttrs, and mTitleAttrs.
removeAttrs()
void cxBase::removeAttrs (e_WidgetItems pItem)
Removes all attributes for a given window item.
Parameters
pItem The item type to remove attributes for (see the e_WidgetItems enumeration).
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, eTITLE, mBorderAttrs, mDataEditableAttrs, mDataReadonlyAttrs, mHotkeyAttrs, mLabelAttrs, mMenuSelectionAttrs, mMessageAttrs, mStatusAttrs, and mTitleAttrs.
removeNavKey()
void cxBase::removeNavKey (int pKey)
Removes a key from cxBase's list of "navigational" keys.
Parameters
pKey The key to be removed
References mNavKeys.
resizeTerm()
bool cxBase::resizeTerm (int pNewHeight, int pNewWidth)
Resizes the terminal screen.
Parameters
pNewHeight The new height (# of rows)
pNewWidth The new width (# of columns)
Returns
true if successful or false if not
right()
int cxBase::right ()
Returns the rightmost column # of the main screen.
Returns
The rightmost column # of the main screen
Referenced by cxWindow::alignHoriz(), cxWindow::getRowColBasedOn(), cxWindow::info(), cxWindow::init(), and main().
runSystemCmd()
int cxBase::runSystemCmd (const std::string & pCmd)
Runs a command on the system, calling the system() function.
If your application has called cxBase::init(), this
function should be called to run a system command.
After running cxBase::init(), cxBase::cleanup() must be
called before running system commands to get the
terminal back to the state it was in before; then,
cxBase::init() must be called again after the call to
system() to restore cxWidgets graphical functions.
This function does the wrapping for you.
Parameters
pCmd The command to run
Returns
The return value of system()
setAttr()
void cxBase::setAttr (e_WidgetItems pItem, attr_t pAttr)
Sets the ncurses attribute to use for one of the items in the.
window (see the e_WidgetItems enumeration). Clears the current
set of attributes for the item and inserts the given attribute
into the set.
Parameters
pItem The item type to apply the attribute for (see the e_WidgetItems enumeration).
pAttr The ncurses atribute to apply.
References eBORDER, eDATA, eDATA_EDITABLE, eDATA_READONLY, eHOTKEY, eLABEL, eMENU_SELECTION, eMESSAGE, eSTATUS, eTITLE, mBorderAttrs, mDataEditableAttrs, mDataReadonlyAttrs, mHotkeyAttrs, mLabelAttrs, mMenuSelectionAttrs, mMessageAttrs, mStatusAttrs, and mTitleAttrs.
Referenced by attributesSetter(), and main().
setDefaultBorderColor()
void cxBase::setDefaultBorderColor (e_cxColors pColor)
Sets the default border color.
Parameters
pColor A member of the e_cxColors enumeration (see cxColors.h)
References mDefaultBorderColor.
setDefaultMessageColor()
void cxBase::setDefaultMessageColor (e_cxColors pColor)
Sets the default message color.
Parameters
pColor A member of the e_cxColors enumeration (see cxColors.h)
References mDefaultMessageColor.
setDefaultStatusColor()
void cxBase::setDefaultStatusColor (e_cxColors pColor)
Sets the default status color.
Parameters
pColor A member of the e_cxColors enumeration (see cxColors.h)
References mDefaultStatusColor.
setDefaultTitleColor()
void cxBase::setDefaultTitleColor (e_cxColors pColor)
Sets the default title color.
Parameters
pColor A member of the e_cxColors enumeration (see cxColors.h)
References mDefaultTitleColor.
setMenuClearKeywordKey()
void cxBase::setMenuClearKeywordKey (int pKey)
Sets the key that should be used to clear the "Keyword" input.
for cxMenu item searching.
Parameters
pKey The key that should be used to clear the "Keyword" input for cxMenu item searching.
References mMenuClearKeywordKey.
showAllWindows()
void cxBase::showAllWindows (bool pBringToTop = false)
Shows all windows currently in use everywhere, from the.
bottom of the stack to the top.
Parameters
pBringToTop Whether or not to bring each window to the top as it's shown.
References cxInitialized(), and cxWindow::show().
signalHandler()
void cxBase::signalHandler (int pSignal)
Handler for system signals.
Parameters
pSignal The signal to handle
Referenced by init().
splash() [1/2]
void cxBase::splash (const std::string & pMessage, int pSleep)
Shows a splash message.
Parameters
pMessage Message of splash message
pSleep Duration in seconds of splash message
splash() [2/2]
void cxBase::splash (const std::string & pTitle, const std::string & pMessage, int pSleep)
Shows a splash message.
Parameters
pTitle Title of splash message
pMessage Message of splash message
pSleep Duration in seconds of splash message
Referenced by splash1(), and splash2().
stringWithoutHotkeyChars()
std::string cxBase::stringWithoutHotkeyChars (const std::string & pStr)
Takes a string and returns a version without the & characters.
that are used for highlighting the next character.
Parameters
pStr The string to process
Returns
A version of pStr without the highlighting characters.
References stringWithoutHotkeyChars().
Referenced by stringWithoutHotkeyChars().
toggleCursor()
bool cxBase::toggleCursor (bool pToggleCursor)
Enables or disables the display of the cursor.
Parameters
pToggleCursor If true, the cursor will be enabled. If false, the cursor will be disabled.
Returns
The previous state of the cursor - true if it was enabled, or false if not.
Referenced by cxForm::doInputLoop().
top()
int cxBase::top ()
Returns the top row # of the main screen.
Returns
The top row # of the main screen
Referenced by cxWindow::alignVert(), cxWindow::info(), and main().
updateWindows()
void cxBase::updateWindows ()
Updates (refreshes) all windows on the screen.
References cxInitialized().
Referenced by cxWindow::bringToBottom(), cxForm::bringToTop(), cxWindow::bringToTop(), cxMultiLineInput::bringToTop(), cxWindow::erase(), cxWindow::hide(), cxInput::refreshValue(), cxInput::show(), cxWindow::show(), and cxWindow::unhide().
visualStrLen()
unsigned cxBase::visualStrLen (const std::string & pStr)
Returns the length of a string without its hotkey characters -.
This is useful for counting the number of characters that
will actually appear on the screen (not counting the
characters that specify underlined characters).
Parameters
pStr The string to process
Returns
The length of the string as it would appear on the screen
References visualStrLen().
Referenced by cxWindow::drawMessage(), cxWindow::init(), cxInput::setLabel(), and visualStrLen().
width()
int cxBase::width ()
Returns the width of the main screen.
Returns
The width of the main screen
Referenced by cxPanel_cxMenuUpArrowLeave(), cxPanelTest2(), cxWindow::getRowColBasedOn(), getTermDimentions(), cxWindow::info(), cxWindow::init(), main(), cxMenu::resize(), cxWindow::resize(), cxMultiLineInput::resize(), and setValFunc().
writeText()
void cxBase::writeText (int pRow, int pCol, const std::string & pText, attr_t pAttr = A_NORMAL, e_cxColors pColor = eGRAY_BLACK)
Writes text on the screen.
Parameters
pRow The row at which to write the text
pCol The column at which to write the text
pText The text to be written
pAttr The text attribute (see the man page for wattron). Defaults to normal.
pColor The text color (see e_cxColors enumeration in cxColors.h). Defaults to gray on black.
Variable Documentation
mBorderAttrs
set<attr_t> cxBase::mBorderAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
mDataEditableAttr
attr_t cxBase::mDataEditableAttr =A_REVERSE
mDataEditableAttrs
set<attr_t> cxBase::mDataEditableAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
mDataReadonlyAttr
attr_t cxBase::mDataReadonlyAttr =A_BOLD
mDataReadonlyAttrs
set<attr_t> cxBase::mDataReadonlyAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
mDefaultBorderColor
e_cxColors cxBase::mDefaultBorderColor = eGRAY_BLUE
Referenced by getDefaultBorderColor(), and setDefaultBorderColor().
mDefaultMessageColor
e_cxColors cxBase::mDefaultMessageColor = eGRAY_BLUE
Referenced by getDefaultMessageColor(), and setDefaultMessageColor().
mDefaultStatusColor
e_cxColors cxBase::mDefaultStatusColor = eYELLOW_BLUE
Referenced by getDefaultStatusColor(), and setDefaultStatusColor().
mDefaultTitleColor
e_cxColors cxBase::mDefaultTitleColor = eWHITE_BLUE
Referenced by getDefaultTitleColor(), and setDefaultTitleColor().
mHotkeyAttrs
set<attr_t> cxBase::mHotkeyAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), init(), removeAttr(), removeAttrs(), and setAttr().
mInitialized
bool cxBase::mInitialized = false
Referenced by cleanup(), cxInitialized(), and init().
mLabelAttr
attr_t cxBase::mLabelAttr =A_DIM
mLabelAttrs
set<attr_t> cxBase::mLabelAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
mMenuClearKeywordKey
int cxBase::mMenuClearKeywordKey = KEY_F(10)
Referenced by getMenuClearKeywordKey(), and setMenuClearKeywordKey().
mMenuSelectionAttr
attr_t cxBase::mMenuSelectionAttr =A_REVERSE
mMenuSelectionAttrs
set<attr_t> cxBase::mMenuSelectionAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), init(), removeAttr(), removeAttrs(), and setAttr().
mMessageAttrs
set<attr_t> cxBase::mMessageAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
mNavKeys
set<int> cxBase::mNavKeys
Referenced by addNavKey(), init(), isNavKey(), and removeNavKey().
mStatusAttrs
set<attr_t> cxBase::mStatusAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
mTitleAttrs
set<attr_t> cxBase::mTitleAttrs
Referenced by addAttr(), disableAttrs(), enableAttrs(), removeAttr(), removeAttrs(), and setAttr().
termType
const std::string cxBase::termType = getTermType() static
Contains the terminal type string.