cxWidgets: /home/erico/projects/cxWidgets/examples/snake/main.cpp File Reference
main.cpp File Reference
#include "../../src/cxBase.h"
#include "SnakeGame.h"
Functions
int main ()
Function Documentation
main()
int main ()
References cxBase::cleanup(), cxBase::init(), SnakeGame::run(), and cxWindow::show().