cxWidgets: /home/erico/projects/cxWidgets/tests/test_wordwrap.cpp File Reference
test_wordwrap.cpp File Reference
#include <iostream>
#include <vector>
#include <string>
#include <cassert>
#include "../src/cxStringUtils.h"
Functions
std::vector< std::string > wrapText (const std::string &message, int innerWidth)
void test_wrapping ()
int main ()
Function Documentation
main()
int main ()
References test_wrapping().
test_wrapping()
void test_wrapping ()
References wrapText().
Referenced by main().
wrapText()
std::vector< std::string > wrapText (const std::string & message, int innerWidth)
References cxStringUtils::SplitStringRegex().
Referenced by test_wrapping().