cxWidgets: /home/erico/projects/cxWidgets/src/test1.cpp File Reference
test1.cpp File Reference
#include "cxBase.h"
#include "cxDialog.h"
#include "cxMessageDialog.h"
#include "cxForm.h"
#include "cxWindow.h"
#include "cxButton.h"
#include "cxFileViewer.h"
#include "cxMenu.h"
#include "cxInput.h"
#include "cxMultiLineInput.h"
#include "cxStringUtils.h"
#include <unistd.h>
#include <stdlib.h>
#include <iostream>
Functions
string updateMenu (void *theComboBox, void *unused, void *unused2, void *unused3)
string onFocus (void *theComboBox, void *unused2, void *unused3, void *unused4)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References cxForm::addAttr(), cxForm::append(), cxForm::appendComboBox(), cxBase::cleanup(), eDATA_EDITABLE, cxForm::getInput(), cxBase::init(), onFocus(), cxForm::setOnFocusFunction(), and cxForm::showModal().
onFocus()
string onFocus (void * theComboBox, void * unused2, void * unused3, void * unused4)
Referenced by main().
updateMenu()
string updateMenu (void * theComboBox, void * unused, void * unused2, void * unused3)
References cxMultiLineInput::getValue().