cxWidgets: /home/erico/projects/cxWidgets/src/test_cxStringUtils.cpp File Reference
test_cxStringUtils.cpp File Reference
#include "cxStringUtils.h"
#include <iostream>
#include <vector>
#include <string>
#include <cassert>
Functions
void test_TrimSpaces ()
void test_strToUpper ()
void test_strToLower ()
void test_Replace ()
int main ()
Function Documentation
main()
int main ()
References test_Replace(), test_strToLower(), test_strToUpper(), and test_TrimSpaces().
test_Replace()
void test_Replace ()
References cxStringUtils::Replace().
Referenced by main().
test_strToLower()
void test_strToLower ()
References cxStringUtils::strToLower().
Referenced by main().
test_strToUpper()
void test_strToUpper ()
References cxStringUtils::strToUpper().
Referenced by main().
test_TrimSpaces()
void test_TrimSpaces ()
References cxStringUtils::TrimSpaces().
Referenced by main().