cxWidgets: /home/erico/projects/cxWidgets/src/test_cxDate.cpp File Reference
test_cxDate.cpp File Reference
#include "cxDate.h"
#include <iostream>
#include <cassert>
#include <string>
Functions
void test_Constructors ()
void test_Arithmetic ()
void test_Comparison ()
void test_Formatting ()
int main ()
Function Documentation
main()
int main ()
References test_Arithmetic(), test_Comparison(), and test_Constructors().
test_Arithmetic()
void test_Arithmetic ()
References cx::cxDate::addDays(), cx::cxDate::addMonths(), cx::cxDate::getDay(), cx::cxDate::getMonth(), cx::cxDate::getYear(), and cx::cxDate::subtractDays().
Referenced by main().
test_Comparison()
void test_Comparison ()
Referenced by main().
test_Constructors()
void test_Constructors ()
References cx::cxDate::getDay(), cx::cxDate::getMonth(), cx::cxDate::getYear(), and cx::YYYY_MM_DD.
Referenced by main().
test_Formatting()
void test_Formatting ()
References cx::YYYY_MM_DD.