cxWidgets: /home/erico/projects/cxWidgets/src/testApp.cpp File Reference
testApp.cpp File Reference
#include "cxUtils.h"
#include "cxDialog.h"
#include "cxMessageDialog.h"
#include "cxForm.h"
#include "cxWindow.h"
#include "cxButton.h"
#include "cxFileViewer.h"
#include "cxMenu.h"
#include "cxInput.h"
#include "cxNotebook.h"
#include "cxMultiLineInput.h"
#include "cxStringUtils.h"
#include "cxScrolledWindow.h"
#include "cxMultiForm.h"
#include "cxComboBox.h"
#include "cxDatePicker.h"
#include "cxOpenFileDialog.h"
#include "cxDate.h"
#include "cxPanel.h"
#include "cxSearchPanel.h"
#include "cxValidators.h"
#include "cxGrid.h"
#include "cxLabel.h"
#include "floatingPtInputWithRightLabel.h"
#include <unistd.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <algorithm>
#include <memory>
#include <cassert>
Enumerations
enum menuItemIDs {
menuCode = cxFIRST_AVAIL_RETURN_CODE , menuItemWithMultipleHotkeyCode , menuScrollingCode , inputWithFKeysCode ,
formWithFKeysCode , inputCode , inputMaskingCode , multiInputMaskingCode ,
multiLineInputLabelChangeCode , inputLabelChangeCode , msgOKCode , msgOKCancelCode ,
msgCancelCode , msgYesCode , msgYesNoCode , msgNoYesCode ,
msgNoCode , windowCode , extTitleWinCode , extStatusWinCode ,
msgBox1Code , msgBox2Code , msgBox3Code , msgBox4Code ,
splash1Code , splash2Code , fileViewerCode , attributesSetterCode ,
singleLineInputCode , multiLineInputCode , exitCode , someItem ,
formCode , stackedFormScrollingCode , stackedFormScrollingCode2 , titleAlignmentCode ,
statusAlignmentCode , cxWindowCopyConstructorCode , panelDemoCode , inputsWithDifferentColorsCode ,
formInputColorsCode , borderlessFormCode , testFormReadOnlyCode , formWithInputValueValidatorCode ,
testFormPosCode , formWithMenuCode , cxWindowAssignmentCode , cxMenuAssignmentCode ,
cxFormAssignmentCode , multiLineInputResizeCode , setValFuncCode , changeMenuItemTextCode ,
windowWriteTextCode , formChangeInputFocusWhileModalCode , allFormInputsGoReadOnlyCode , formNoQuitCode ,
menuNoQuitCode , scrolledWindowCode , cxInputBorderChangeCode , cxMultiLineInputBorderChangeCode ,
comboBoxCode , comboBoxOnFormCode , inputWithoutBorderCode , formDataChangedCode ,
integerValidateCode , floatingPtValidateCode , enableDisableFormCode , multiFormWithDisabledSubformCode ,
comboBoxMenuDisableCode , multiForm2Code , inputQuitKeysOnFormCode , cxMenuFocusFunctionsCode ,
loneInputWithLoopDisabledOnFormCode , cxMenuWithMultipleItemHotkeysCode , cxMenuItemHotkeysOffMenuCode , cxPanelCode ,
cxPanelCode2 , cxPanelDelAllWindowsCode , cxWindowWithFunctionKeysCode , cxWindowWithMultipleTitleStringsCode ,
cxWindowWithMultipleStatusStringsCode , cxMenuNoMoreSelectableItemsWhileModalCode , cxPanelWithNonEditableSubwindowsCode , cxMenuWithDuplicateHotkeysCode ,
cxPanelWindowSwapCode , cxPanel_cxMenuUpArrowLeaveCode , windowFunctionKeyNoOnLeaveCode , formFunctionKeyNoOnLeaveCode ,
cxMultiLineInputFunctionKeyNoValidatorCode , cxFormMultiLineInputFunctionKeyNoValidatorCode , keyFunctionAutoExitOnLastFormInputCode , cxFormNavKeysCode ,
addMessageLineCode , cxFormStartAtFirstInputCode , cxPanelGetLastWindowCode , cxFormClearOnlyEditableCode ,
cxButtonOnClickCode , cxMenuMiscTestsCode , cxSearchPanelTestCode , cxSearchPanelResizeCode ,
cxSearchPanelCopyConstructorCode , cxMenuResizeCode , cxWindowAlignCode , cxNotebookTest1Code ,
cxNotebookTest2Code , cxNotebookRemoveWindowTestCode , cxNotebookWithEmptyPanelTestCode , cxNotebookSetTabSpacingCode ,
cxNotebookSwapTestCode , cxWindowBorderCode , cxWindowSizeCode , cxWindowAttributesCode ,
cxWindowMouseFunctionTestCode , cxFormMouseFunctionTestCode , cxMenuMouseFunctionTestCode , cxPanelWithButtonTestCode ,
cxMultiLineInputNumericFloatingPtCode , cxMultiLineInputNumericFloatingPtWithRangeCode , cxMultiLineInputNumericWholeCode , cxMultiLineInputNumericWholeWithRangeCode ,
cxMultiLineInputTextValidationCode , cxMultiLineInputForceUpperCode , cxMultiLineInputNonBlankCode , cxMultiLineInputTextValidationNonBlankForceUpperCode ,
cxMultiLineInputTextValidationAutoCompletionCode , cxMultiLineInputExtendedHelpKeyCode , cxFormExtendedHelpKeyCode , cxMultiLineInputWithRightLabelCode ,
cxMultiLineInputWithRightLabelOnFormCode , cxMultiLineInputAutoGenerateHelpStringCode , itemSalesCode , cxFormAppendPairCode ,
cxFormAppendComboBoxPairCode , cxMultiLineInputSetValueCode , cxMultiLineInputMaxInputLengthCode , cxMultiLineInputExtendedHelpColorsAndAttrsCode ,
cxMenuAltItemTextCode , cxComboBoxNotEditableMenuEnabledCode , cxMultiLineInputOverrideOnKeypressCode , cxWindowAddMessageLinesAboveCode ,
cxWindowBorderStyles , cxDatePickerTestCode , cxOpenFileDialogTestCode , cxGridTestCode
}
Functions
void doMenu ()
void msgOK ()
void msgOKCancel ()
void msgCancel ()
void msgYes ()
void msgYesNo ()
void msgNoYes ()
void msgNo ()
void testInput1 ()
void testMenu1 ()
void testInput2 ()
void window1 ()
void msgBox1 ()
void msgBox2 ()
void msgBox3 ()
void msgBox4 ()
void splash1 ()
void splash2 ()
void fileViewer ()
void attributesSetter ()
void singleLineInput ()
void multiLineInput ()
void form ()
void cxMenuScrolling ()
void inputsWithFKeys ()
void formWithFKeys ()
void cxInputMasking ()
void cxMultiLineInputMasking ()
void cxWindowMoveRelative ()
void stackedFormScrolling ()
void externalTitleWindow ()
void externalStatusWindow ()
void setInputLabel ()
void setMultiLineInputLabel ()
void titleAlignment ()
void statusAlignment ()
void cxWindowCopyConstructor ()
void demoPanels ()
void menuItemWithMultipleHotkeys ()
void inputsWithDifferentColors ()
void formInputColors ()
void borderlessForm ()
void unselectableMenuItem ()
void testFormReadOnly ()
void stackedFormScrolling2 ()
void formWithInputValueValidator ()
void testFormPos ()
void formWithMenu ()
void cxWindowAssignment ()
void cxMenuAssignment ()
void cxFormAssignment ()
void multiLineInputResize ()
void setValFunc ()
void formUpArrowFunction ()
void changeMenuItemText ()
void windowWriteText ()
void formChangeInputFocusWhileModal ()
void allFormInputsGoReadOnly ()
void cxFormNoQuit ()
void cxMenuNoQuit ()
void scrolledWindow ()
void cxInputBorderChange ()
void cxMultiLineInputBorderChange ()
void getFormKeys ()
void multiForm ()
void multiForm2 ()
void simpleForm1 ()
void comboBox ()
void comboBoxOnForm ()
void inputWithoutBorder ()
void formDataChanged ()
void integerValidate ()
void floatingPtValidate ()
void integerValidateOnForm ()
void floatingPtValidateOnForm ()
void formFunctionKeys ()
void enableDisableForm ()
void multiFormWithDisabledSubform ()
void comboBoxMenuDisable ()
void inputQuitKeysOnForm ()
void cxMenuFocusFunctions ()
void cxInputOnFormLoopDisabled ()
void loneInputWithLoopDisabledOnForm ()
void cxMenuWithMultipleItemHotkeys ()
void cxMenuItemHotkeysOffMenu ()
void cxPanelTest ()
void cxPanelTest2 ()
void cxPanelDelAllWindowsTest ()
void cxWindowWithFunctionKeys ()
void cxWindowWithMultipleTitleStrings ()
void cxWindowWithMultipleStatusStrings ()
void cxMenuNoMoreSelectableItemsWhileModal ()
void cxPanelWithNonEditableSubwindows ()
void cxMenuWithDuplicateHotkeys ()
void cxPanelWindowSwap ()
void cxPanel_cxMenuUpArrowLeave ()
void windowFunctionKeyNoOnLeave ()
void formFunctionKeyNoOnLeave ()
void cxMultiLineInputFunctionKeyNoValidator ()
void cxFormMultiLineInputFunctionKeyNoValidator ()
void keyFunctionAutoExitOnLastFormInput ()
void cxFormNavKeys ()
void addMessageLine ()
void cxFormStartAtFirstInput ()
void cxPanelGetLastWindow ()
void cxFormClearOnlyEditable ()
void cxButtonOnClick ()
void cxMenuMiscTests ()
void cxSearchPanelTest ()
void cxSearchPanelResize ()
void cxSearchPanelCopyConstructor ()
void cxMenuResize ()
void cxWindowAlignTest ()
void cxNotebookTest1 ()
void cxNotebookTest2 ()
void cxNotebookRemoveWindowTest ()
void cxNotebookWithEmptyPanelTest ()
void cxNotebookSetTabSpacing ()
void cxNotebookSwapTest ()
void cxWindowBorderTest ()
void cxWindowSizeTest ()
void cxWindowAttributesTest ()
void cxWindowMouseFunctionTest ()
void cxMenuMouseFunctionTest ()
void cxFormMouseFunctionTest ()
void cxPanelWithButton ()
void cxMultiLineInputNumericFloatingPt ()
void cxMultiLineInputNumericFloatingPtWithRange ()
void cxMultiLineInputNumericWhole ()
void cxMultiLineInputNumericWholeWithRange ()
void cxMultiLineInputTextValidation ()
void cxMultiLineInputForceUpper ()
void cxMultiLineInputNonBlank ()
void cxMultiLineInputExtendedHelpKey ()
void cxFormExtendedHelpKey ()
void cxMultiLineInputTextValidationNonBlankForceUpper ()
void cxMultiLineInputTextValidationAutoCompletion ()
void cxMultiLineInputWithRightLabel ()
void cxMultiLineInputWithRightLabelOnForm ()
void cxMultiLineInputAutoGenerateHelpString ()
void itemSales ()
void cxFormAppendPair ()
void cxFormAppendComboBoxPair ()
void cxMultiLineInputSetValue ()
void cxMultiLineInputMaxInputLength ()
void cxMultiLineInputExtendedHelpColorsAndAttrs ()
void cxWindowMessageNewlines ()
void cxMenuAltItemText ()
void cxComboBoxNotEditableMenuEnabled ()
void cxMultiLineInputOverrideOnKeypress ()
void cxWindowAddMessageLinesAbove ()
void cxWindowVariousBorderStyles ()
void cxDatePickerTest ()
void cxOpenFileDialogTest ()
void cxGridTest ()
string someFunction (int &int1, int &int2)
string returnBBye ()
string someFunction2 (cxMultiLineInput &input)
string someFunction3 (cxMultiLineInput &input)
string hello ()
string genericMessageFunction ()
string genericMessageFunction_1str (string &pMessage)
string testBoxSuccess (void *Foo1, void *Foo2, void *Foo3, void *Foo4)
string inputYesNo (void *theInput, void *, void *, void *)
string testKeyFunction (void *unused, void *unused2)
string testOnFocusFunction (void *unused, void *unused2, void *unused3, void *unused4)
string testOnLeaveFunction (void *unused, void *unused2, void *unused3, void *unused4)
string testInputValidator (void *theMultiLineInput, void *unused2, void *unused3, void *unused4)
string getMenuItemIDStr (long pMenuItemID)
string someWeirdFunc (void *theForm, void *unused)
int main (int argc, char *argv[])
string sayHello (void *p1, void *p2)
string sayHello2 (void *p1, void *p2)
string setAllInputsReadOnly (void *theForm, void *unused, void *unused2, void *unused3)
bool fKeySort (const string &pStr1, const string &pStr2)
string multiForm2_goToForm1_Input1 (void *theMultiForm, void *unused, void *unused2, void *unused3)
string multiForm2_goToForm3_Input1 (void *theMultiForm, void *unused, void *unused2, void *unused3)
string multiForm2_quit (void *theMultiForm, void *unused, void *unused2, void *unused3)
string updateMenu (void *theComboBox, void *unused, void *unused2, void *unused3)
string onFocus (void *unused, void *unused2, void *unused3, void *unused4)
string onLeave (void *unused, void *unused2, void *unused3, void *unused4)
string showAMessageBox (void *classTypeStr, void *unused)
string changeWindowFocus (void *thePanel, void *unused, void *unused2, void *unused3)
string allMenuItemsUnselectable (void *menu, void *unused)
string clearAllMenuItems (void *menu, void *unused)
string onFocusWinForCxPanelGetLastPage (void *thePanel, void *theCurrentWindow, void *unused2, void *unused3)
string buttonClickFunction (void *theButton, void *unused, void *unused2, void *unused3)
string onFocusForm (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string onLeaveForm (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string onFocusMenu (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string onLeaveMenu (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string formOnEnter (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string menuOnEnter (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string searchPanelOnFocus (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string mouseFunction (void *theWindow, void *unused)
string storeSearchFormOnEnter (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string storeSearchMenuOnEnter (void *theSearchPanel, void *unused, void *unused2, void *unused3)
string storeOnLeave (void *theInput, void *unused)
string storeSearch (void *theInput, void *unused)
string gridButtonClicked ()
Variables
shared_ptr< cxWindow > gTitleLine
shared_ptr< cxWindow > gStatusLine
Enumeration Type Documentation
menuItemIDs
enum menuItemIDs
Enumerator
menuCode
menuItemWithMultipleHotkeyCode
menuScrollingCode
inputWithFKeysCode
formWithFKeysCode
inputCode
inputMaskingCode
multiInputMaskingCode
multiLineInputLabelChangeCode
inputLabelChangeCode
msgOKCode
msgOKCancelCode
msgCancelCode
msgYesCode
msgYesNoCode
msgNoYesCode
msgNoCode
windowCode
extTitleWinCode
extStatusWinCode
msgBox1Code
msgBox2Code
msgBox3Code
msgBox4Code
splash1Code
splash2Code
fileViewerCode
attributesSetterCode
singleLineInputCode
multiLineInputCode
exitCode
someItem
formCode
stackedFormScrollingCode
stackedFormScrollingCode2
titleAlignmentCode
statusAlignmentCode
cxWindowCopyConstructorCode
panelDemoCode
inputsWithDifferentColorsCode
formInputColorsCode
borderlessFormCode
testFormReadOnlyCode
formWithInputValueValidatorCode
testFormPosCode
formWithMenuCode
cxWindowAssignmentCode
cxMenuAssignmentCode
cxFormAssignmentCode
multiLineInputResizeCode
setValFuncCode
changeMenuItemTextCode
windowWriteTextCode
formChangeInputFocusWhileModalCode
allFormInputsGoReadOnlyCode
formNoQuitCode
menuNoQuitCode
scrolledWindowCode
cxInputBorderChangeCode
cxMultiLineInputBorderChangeCode
comboBoxCode
comboBoxOnFormCode
inputWithoutBorderCode
formDataChangedCode
integerValidateCode
floatingPtValidateCode
enableDisableFormCode
multiFormWithDisabledSubformCode
comboBoxMenuDisableCode
multiForm2Code
inputQuitKeysOnFormCode
cxMenuFocusFunctionsCode
loneInputWithLoopDisabledOnFormCode
cxMenuWithMultipleItemHotkeysCode
cxMenuItemHotkeysOffMenuCode
cxPanelCode
cxPanelCode2
cxPanelDelAllWindowsCode
cxWindowWithFunctionKeysCode
cxWindowWithMultipleTitleStringsCode
cxWindowWithMultipleStatusStringsCode
cxMenuNoMoreSelectableItemsWhileModalCode
cxPanelWithNonEditableSubwindowsCode
cxMenuWithDuplicateHotkeysCode
cxPanelWindowSwapCode
cxPanel_cxMenuUpArrowLeaveCode
windowFunctionKeyNoOnLeaveCode
formFunctionKeyNoOnLeaveCode
cxMultiLineInputFunctionKeyNoValidatorCode
cxFormMultiLineInputFunctionKeyNoValidatorCode
keyFunctionAutoExitOnLastFormInputCode
cxFormNavKeysCode
addMessageLineCode
cxFormStartAtFirstInputCode
cxPanelGetLastWindowCode
cxFormClearOnlyEditableCode
cxButtonOnClickCode
cxMenuMiscTestsCode
cxSearchPanelTestCode
cxSearchPanelResizeCode
cxSearchPanelCopyConstructorCode
cxMenuResizeCode
cxWindowAlignCode
cxNotebookTest1Code
cxNotebookTest2Code
cxNotebookRemoveWindowTestCode
cxNotebookWithEmptyPanelTestCode
cxNotebookSetTabSpacingCode
cxNotebookSwapTestCode
cxWindowBorderCode
cxWindowSizeCode
cxWindowAttributesCode
cxWindowMouseFunctionTestCode
cxFormMouseFunctionTestCode
cxMenuMouseFunctionTestCode
cxPanelWithButtonTestCode
cxMultiLineInputNumericFloatingPtCode
cxMultiLineInputNumericFloatingPtWithRangeCode
cxMultiLineInputNumericWholeCode
cxMultiLineInputNumericWholeWithRangeCode
cxMultiLineInputTextValidationCode
cxMultiLineInputForceUpperCode
cxMultiLineInputNonBlankCode
cxMultiLineInputTextValidationNonBlankForceUpperCode
cxMultiLineInputTextValidationAutoCompletionCode
cxMultiLineInputExtendedHelpKeyCode
cxFormExtendedHelpKeyCode
cxMultiLineInputWithRightLabelCode
cxMultiLineInputWithRightLabelOnFormCode
cxMultiLineInputAutoGenerateHelpStringCode
itemSalesCode
cxFormAppendPairCode
cxFormAppendComboBoxPairCode
cxMultiLineInputSetValueCode
cxMultiLineInputMaxInputLengthCode
cxMultiLineInputExtendedHelpColorsAndAttrsCode
cxMenuAltItemTextCode
cxComboBoxNotEditableMenuEnabledCode
cxMultiLineInputOverrideOnKeypressCode
cxWindowAddMessageLinesAboveCode
cxWindowBorderStyles
cxDatePickerTestCode
cxOpenFileDialogTestCode
cxGridTestCode
Function Documentation
addMessageLine()
void addMessageLine ()
References cx::cxWindow::addMessageLineBelow(), cx::cxWindow::removeMessageLine(), and cx::cxWindow::showModal().
Referenced by doMenu().
allFormInputsGoReadOnly()
void allFormInputsGoReadOnly ()
References cx::cxForm::append(), cx::cxID_EXIT, cx::cxID_QUIT, cx::eINPUT_EDITABLE, cx::eINPUT_READONLY, cx::cxForm::getInput(), cx::messageBox(), setAllInputsReadOnly(), cx::cxForm::setFieldKeyFunction(), and cx::cxForm::showModal().
Referenced by doMenu().
allMenuItemsUnselectable()
string allMenuItemsUnselectable (void * menu, void * unused)
References cx::cxMenu::numMenuItems(), and cx::cxMenu::toggleSelectability().
Referenced by cxMenuNoMoreSelectableItemsWhileModal().
attributesSetter()
void attributesSetter ()
References cx::cxMenu::append(), cx::cxForm::append(), cx::cxID_QUIT, cx::eBORDER, cx::eDATA_EDITABLE, cx::eDATA_READONLY, cx::eHOTKEY, cx::eINPUT_READONLY, cx::eLABEL, cx::eMENU_SELECTION, cx::eMESSAGE, cx::eSTATUS, cx::eTITLE, cx::cxWindow::hide(), cx::cxMenu::numMenuItems(), cx::setAttr(), cx::cxWindow::setAttr(), cx::cxForm::setAttr(), cx::cxWindow::setMessage(), cx::cxWindow::setStatus(), cx::cxForm::setStatus(), cx::cxForm::setValue(), cx::cxWindow::show(), cx::cxForm::show(), and cx::cxMenu::showModal().
Referenced by doMenu().
borderlessForm()
void borderlessForm ()
References cx::cxForm::append(), cx::dump(), cx::eBS_NOBORDER, cx::eRED_WHITE, cx::cxForm::setAllValueColor(), cx::cxForm::setAutoExit(), and cx::cxForm::showModal().
Referenced by doMenu().
buttonClickFunction()
string buttonClickFunction (void * theButton, void * unused, void * unused2, void * unused3)
References cx::messageBox().
Referenced by cxButtonOnClick(), and cxPanelWithButton().
changeMenuItemText()
void changeMenuItemText ()
References cx::cxMenu::append(), cx::cxMenu::setItemTextByIndex(), cx::cxMenu::setItemTextByReturnCode(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
changeWindowFocus()
string changeWindowFocus (void * thePanel, void * unused, void * unused2, void * unused3)
References cx::cxPanel::setCurrentWindow().
Referenced by cxPanelDelAllWindowsTest(), and cxPanelTest().
clearAllMenuItems()
string clearAllMenuItems (void * menu, void * unused)
References cx::cxMenu::removeAllItems().
Referenced by cxMenuNoMoreSelectableItemsWhileModal().
comboBox()
void comboBox ()
References cx::cxComboBox::height(), cx::cxComboBox::inputHeight(), cx::cxComboBox::menuHeight(), cx::messageBox(), cx::cxComboBox::resize(), cx::cxComboBox::setMenuHeight(), cx::cxMultiLineInput::setOnKeyFunction(), cx::cxComboBox::showModal(), cxStringUtils::toString(), updateMenu(), and cx::cxComboBox::width().
Referenced by doMenu().
comboBoxMenuDisable()
void comboBoxMenuDisable ()
References cx::cxComboBox::height(), cx::messageBox(), cx::cxComboBox::resize(), cx::cxMultiLineInput::setOnKeyFunction(), cx::cxComboBox::showModal(), cx::cxComboBox::toggleMenu(), cxStringUtils::toString(), updateMenu(), and cx::cxComboBox::width().
Referenced by doMenu().
comboBoxOnForm()
void comboBoxOnForm ()
References cx::cxForm::append(), cx::cxForm::appendComboBox(), cx::cxForm::getInput(), cx::cxForm::setOnKeyFunction(), cx::cxForm::showModal(), and updateMenu().
Referenced by doMenu().
cxButtonOnClick()
void cxButtonOnClick ()
References buttonClickFunction(), cx::messageBox(), cx::cxButton::setOnClickFunction(), and cx::cxButton::showModal().
Referenced by doMenu().
cxComboBoxNotEditableMenuEnabled()
void cxComboBoxNotEditableMenuEnabled ()
References cx::cxComboBox::appendToMenu(), cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setEditable(), and cx::cxComboBox::showModal().
Referenced by doMenu().
cxDatePickerTest()
void cxDatePickerTest ()
References cx::cxID_OK, cx::cxDatePicker::getSelectedDate(), cx::messageBox(), cx::cxDatePicker::showModal(), and cx::cxDate::toString().
Referenced by doMenu().
cxFormAppendComboBoxPair()
void cxFormAppendComboBoxPair ()
References cx::cxForm::appendComboBoxPair(), cx::eINPUT_EDITABLE, cx::cxWidgetsException::getErrorMsg(), cx::messageBox(), and cx::cxForm::showModal().
Referenced by doMenu().
cxFormAppendPair()
void cxFormAppendPair ()
References cx::cxMenu::append(), cx::cxForm::appendPair(), cx::cxWindow::center(), cx::eBS_NOBORDER, cx::eINPUT_EDITABLE, cx::eINPUT_TYPE_NUMERIC_WHOLE, cx::eINPUT_TYPE_TEXT, cx::cxWidgetsException::getErrorMsg(), cx::cxForm::getValues(), cx::cxWindow::hide(), cx::messageBox(), cx::cxForm::setAutoExit(), cx::cxForm::showModal(), and cx::cxMenu::showModal().
Referenced by doMenu().
cxFormAssignment()
void cxFormAssignment ()
References cx::cxForm::append(), cx::eDATA_EDITABLE, cx::eINPUT_READONLY, cx::cxForm::getInput(), inputYesNo(), cx::cxForm::setAutoExit(), cx::cxForm::setOnKeyFunction(), cx::cxForm::setValue(), and cx::cxForm::showModal().
Referenced by doMenu().
cxFormClearOnlyEditable()
void cxFormClearOnlyEditable ()
References cx::cxForm::append(), cx::cxForm::clearInputs(), cx::eINPUT_READONLY, cx::cxForm::setAutoExit(), cx::cxForm::setInputOption(), cx::cxForm::setValue(), and cx::cxForm::showModal().
Referenced by doMenu().
cxFormExtendedHelpKey()
void cxFormExtendedHelpKey ()
References cx::cxForm::append(), cx::cxForm::getExtendedHelpKeyStrings(), cx::messageBox(), cx::cxForm::setExtendedHelpKey(), cx::cxForm::setUseExtendedHelpKeys(), and cx::cxForm::showModal().
Referenced by doMenu().
cxFormMouseFunctionTest()
void cxFormMouseFunctionTest ()
References cx::cxForm::append(), BUTTON1_CLICKED, BUTTON2_CLICKED, BUTTON3_CLICKED, mouseFunction(), cx::cxWindow::setMouseFunction(), and cx::cxForm::showModal().
Referenced by doMenu().
cxFormMultiLineInputFunctionKeyNoValidator()
void cxFormMultiLineInputFunctionKeyNoValidator ()
References cx::cxForm::append(), cx::messageBox(), cx::cxForm::setAutoExit(), cx::cxForm::setKeyFunction(), cx::cxForm::setOnLeaveFunction(), cx::cxForm::showModal(), testInputValidator(), testKeyFunction(), and testOnLeaveFunction().
Referenced by doMenu().
cxFormNavKeys()
void cxFormNavKeys ()
References cx::cxForm::append(), cx::getKeyStr(), cx::cxForm::getNavKeys(), cx::cxForm::getNavKeyStrings(), cx::cxForm::hasNavKey(), cx::messageBox(), and PAGE_DOWN.
Referenced by doMenu().
cxFormNoQuit()
void cxFormNoQuit ()
References cx::cxForm::append(), cx::messageBox(), cx::cxForm::setAllowQuit(), cx::cxForm::setAutoExit(), and cx::cxForm::showModal().
Referenced by doMenu().
cxFormStartAtFirstInput()
void cxFormStartAtFirstInput ()
References cx::cxForm::append(), cx::messageBox(), cx::cxForm::setAutoExit(), cx::cxForm::setStartAtFirstInput(), and cx::cxForm::showModal().
Referenced by doMenu().
cxGridTest()
void cxGridTest ()
References cx::cxWindow::center(), cx::cxGrid::getColWidth(), cx::getTermDimensions(), cx::cxGrid::setCell(), and cx::cxGrid::showModal().
Referenced by doMenu().
cxInputBorderChange()
void cxInputBorderChange ()
References cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::cxInput::getValue(), cx::messageBox(), cx::cxInput::setBorderStyle(), and cx::cxInput::showModal().
Referenced by doMenu().
cxInputMasking()
void cxInputMasking ()
References cx::cxInput::getValue(), cx::messageBox(), cx::cxInput::showModal(), and cx::cxInput::toggleMasking().
Referenced by doMenu().
cxInputOnFormLoopDisabled()
void cxInputOnFormLoopDisabled ()
References cx::cxForm::append(), cx::cxFunction1RefTemplated< T1 >::create(), cx::cxForm::enableInputLoop(), genericMessageFunction_1str(), cx::cxForm::setOnFocusFunction(), cx::cxForm::setOnLeaveFunction(), and cx::cxForm::showModal().
cxMenuAltItemText()
void cxMenuAltItemText ()
References cx::cxMenu::append(), cx::cxITEM_NORMAL, cx::cxMenu::getCurrentItemText(), cx::cxMenu::getItemText(), cx::cxMenu::getItemTextByReturnCode(), cx::cxMenu::getReturnCode(), cx::cxMenu::itemExists(), cx::messageBox(), cx::cxMenu::remove(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuAssignment()
void cxMenuAssignment ()
References cx::cxMenu::append(), cx::eHP_CENTER, cx::messageDialog(), cx::cxWindow::setHorizTitleAlignment(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuFocusFunctions()
void cxMenuFocusFunctions ()
References cx::cxMenu::append(), cx::cxFunction1RefTemplated< T1 >::create(), genericMessageFunction_1str(), cx::cxMenu::setLoopEndFunction(), cx::cxMenu::setLoopStartFunction(), cx::cxWindow::setOnFocusFunction(), cx::cxWindow::setOnLeaveFunction(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuItemHotkeysOffMenu()
void cxMenuItemHotkeysOffMenu ()
References cx::cxMenu::append(), cx::cxMenu::appendWithPullRight(), cx::cxITEM_NORMAL, and cx::cxMenu::showModal().
Referenced by doMenu().
cxMenuMiscTests()
void cxMenuMiscTests ()
References cx::cxMenu::append(), cx::cxMenu::getItemTextByReturnCode(), cx::messageBox(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuMouseFunctionTest()
void cxMenuMouseFunctionTest ()
References cx::cxMenu::append(), BUTTON1_CLICKED, BUTTON2_CLICKED, BUTTON3_CLICKED, mouseFunction(), cx::cxWindow::setMouseFunction(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuNoMoreSelectableItemsWhileModal()
void cxMenuNoMoreSelectableItemsWhileModal ()
References allMenuItemsUnselectable(), cx::cxMenu::append(), clearAllMenuItems(), cx::messageBox(), cx::cxWindow::setKeyFunction(), SHIFT_F11, cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuNoQuit()
void cxMenuNoQuit ()
References cx::cxMenu::append(), cx::messageBox(), cx::cxMenu::setAllowQuit(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuResize()
void cxMenuResize ()
References cx::cxMenu::append(), cx::messageBox(), cx::cxMenu::resize(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuScrolling()
void cxMenuScrolling ()
References cx::cxMenu::append(), cx::cxMenu::appendWithPullRight(), cx::cxITEM_NORMAL, cx::messageBox(), cx::cxMenu::setTopItem(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMenuWithDuplicateHotkeys()
void cxMenuWithDuplicateHotkeys ()
References cx::cxMenu::append(), and cx::cxMenu::showModal().
Referenced by doMenu().
cxMenuWithMultipleItemHotkeys()
void cxMenuWithMultipleItemHotkeys ()
References cx::cxMenu::append(), cx::cxID_QUIT, cx::messageBox(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMultiLineInputAutoGenerateHelpString()
void cxMultiLineInputAutoGenerateHelpString ()
References cx::cxMultiLineInput::addValidOption(), cx::cxMultiLineInput::autoGenerateExtendedHelp(), cx::cxMultiLineInput::setForceUpper(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputBorderChange()
void cxMultiLineInputBorderChange ()
References cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setBorderStyle(), cx::cxMultiLineInput::setExitOnFull(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputExtendedHelpColorsAndAttrs()
void cxMultiLineInputExtendedHelpColorsAndAttrs ()
References cx::eBS_NOBORDER, cx::eGREEN_BLACK, cx::messageBox(), cx::cxMultiLineInput::setExtendedHelp(), cx::cxMultiLineInput::setExtendedHelpAttribute(), cx::cxMultiLineInput::setExtendedHelpColor(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputExtendedHelpKey()
void cxMultiLineInputExtendedHelpKey ()
References cx::cxMultiLineInput::getExtendedHelpKeyStrings(), cx::messageBox(), cx::cxMultiLineInput::setExtendedHelp(), cx::cxMultiLineInput::setExtendedHelpKey(), cx::cxMultiLineInput::setUseExtendedHelpKeys(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputForceUpper()
void cxMultiLineInputForceUpper ()
References cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setForceUpper(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputFunctionKeyNoValidator()
void cxMultiLineInputFunctionKeyNoValidator ()
References cx::messageBox(), cx::cxMultiLineInput::setKeyFunction(), cx::cxMultiLineInput::setValidatorFunction(), cx::cxMultiLineInput::showModal(), testInputValidator(), and testKeyFunction().
Referenced by doMenu().
cxMultiLineInputMasking()
void cxMultiLineInputMasking ()
References cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::toggleMasking().
Referenced by doMenu().
cxMultiLineInputMaxInputLength()
void cxMultiLineInputMaxInputLength ()
References cx::eBS_NOBORDER, cx::cxMultiLineInput::getMaxInputLength(), cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setMaxInputLength(), cx::cxMultiLineInput::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxMultiLineInputNonBlank()
void cxMultiLineInputNonBlank ()
References cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setAllowBlank(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputNumericFloatingPt()
void cxMultiLineInputNumericFloatingPt ()
References cx::eINPUT_TYPE_NUMERIC_FLOATING_PT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputNumericFloatingPtWithRange()
void cxMultiLineInputNumericFloatingPtWithRange ()
References cx::eINPUT_TYPE_NUMERIC_FLOATING_PT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), cx::cxMultiLineInput::setRangeDouble(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputNumericWhole()
void cxMultiLineInputNumericWhole ()
References cx::eINPUT_TYPE_NUMERIC_WHOLE, cx::cxMultiLineInput::getValue(), hello(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), cx::cxMultiLineInput::setKeyFunction(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputNumericWholeWithRange()
void cxMultiLineInputNumericWholeWithRange ()
References cx::eINPUT_TYPE_NUMERIC_WHOLE, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), cx::cxMultiLineInput::setRangeInt(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputOverrideOnKeypress()
void cxMultiLineInputOverrideOnKeypress ()
References cx::cxMultiLineInput::showModal().
Referenced by doMenu().
cxMultiLineInputSetValue()
void cxMultiLineInputSetValue ()
References cx::eINPUT_TYPE_NUMERIC_FLOATING_PT, cx::eINPUT_TYPE_NUMERIC_WHOLE, cx::eINPUT_TYPE_TEXT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setAllowBlank(), cx::cxMultiLineInput::setInputType(), cx::cxMultiLineInput::setValidOptions(), cx::cxMultiLineInput::setValue(), and cx::cxMultiLineInput::useBuiltInValidator().
Referenced by doMenu().
cxMultiLineInputTextValidation()
void cxMultiLineInputTextValidation ()
References cx::cxMultiLineInput::addValidOption(), cx::eINPUT_TYPE_TEXT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), cx::cxMultiLineInput::setValidOptions(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputTextValidationAutoCompletion()
void cxMultiLineInputTextValidationAutoCompletion ()
References cx::cxMultiLineInput::addValidOption(), cx::eBS_NOBORDER, cx::eINPUT_EDITABLE, cx::eINPUT_TYPE_TEXT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setForceUpper(), cx::cxMultiLineInput::setRightLabelOffset(), cx::cxMultiLineInput::setRightLabelWidth(), cx::cxMultiLineInput::setShowRightLabel(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputTextValidationNonBlankForceUpper()
void cxMultiLineInputTextValidationNonBlankForceUpper ()
References cx::cxMultiLineInput::addValidOption(), cx::eINPUT_TYPE_TEXT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setAllowBlank(), cx::cxMultiLineInput::setForceUpper(), cx::cxMultiLineInput::setInputType(), cx::cxMultiLineInput::setValidOptions(), cx::cxMultiLineInput::showModal(), and cx::cxMultiLineInput::validatorFuncMessageBox().
Referenced by doMenu().
cxMultiLineInputWithRightLabel()
void cxMultiLineInputWithRightLabel ()
References cx::cxMultiLineInput::resizeRightLabel(), cx::cxMultiLineInput::setRightLabel(), cx::cxMultiLineInput::setRightLabelOffset(), cx::cxMultiLineInput::setShowRightLabel(), and cx::cxMultiLineInput::show().
Referenced by doMenu().
cxMultiLineInputWithRightLabelOnForm()
void cxMultiLineInputWithRightLabelOnForm ()
References cx::cxForm::append(), cx::eINPUT_EDITABLE, cx::eMLIF_COMMA_SEP_WITH_DESC, and cx::cxForm::showModal().
Referenced by doMenu().
cxNotebookRemoveWindowTest()
void cxNotebookRemoveWindowTest ()
References cx::cxNotebook::append(), cx::cxNotebook::delWindow(), cx::cxNotebook::showModal(), cxStringUtils::toString(), and cx::cxWindow::width().
Referenced by doMenu().
cxNotebookSetTabSpacing()
void cxNotebookSetTabSpacing ()
References cx::cxNotebook::append(), cx::cxNotebook::setLabelsOnTop(), cx::cxNotebook::setTabSpacing(), and cx::cxNotebook::show().
Referenced by doMenu().
cxNotebookSwapTest()
void cxNotebookSwapTest ()
References cx::cxNotebook::append(), cx::cxPanel::getWindow(), cx::cxNotebook::showModal(), cx::cxNotebook::swap(), cxStringUtils::toString(), and cx::cxWindow::width().
Referenced by doMenu().
cxNotebookTest1()
void cxNotebookTest1 ()
References cx::cxNotebook::append(), cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::cxNotebook::setLabel(), cx::cxNotebook::showModal(), cxStringUtils::toString(), and cx::cxWindow::width().
Referenced by doMenu().
cxNotebookTest2()
void cxNotebookTest2 ()
References cx::cxNotebook::append(), cx::cxWindow::center(), cx::cxID_OK, cx::cxNO, cx::cxYES, cx::cxNotebook::setLabel(), cx::cxNotebook::setLabelsOnTop(), cx::cxWindow::setStatus(), cx::cxWindow::setTitle(), cx::cxMessageDialog::showModal(), cx::cxNotebook::showModal(), and cx::cxWindow::width().
Referenced by doMenu().
cxNotebookWithEmptyPanelTest()
void cxNotebookWithEmptyPanelTest ()
References cx::cxNotebook::append(), cx::cxNotebook::showModal(), cxStringUtils::toString(), and cx::cxWindow::width().
Referenced by doMenu().
cxOpenFileDialogTest()
void cxOpenFileDialogTest ()
References cx::cxOpenFileDialog::addFilter(), cx::cxID_OK, cx::cxOpenFileDialog::getSelectedFilePath(), cx::messageBox(), cx::cxOpenFileDialog::setAllowNewFile(), and cx::cxOpenFileDialog::showModal().
Referenced by doMenu().
cxPanel_cxMenuUpArrowLeave()
void cxPanel_cxMenuUpArrowLeave ()
References cx::cxPanel::append(), cx::eBS_SINGLE_LINE, cx::height(), cx::messageBox(), cx::cxPanel::showModal(), cxStringUtils::toString(), and cx::width().
Referenced by doMenu().
cxPanelDelAllWindowsTest()
void cxPanelDelAllWindowsTest ()
References cx::cxPanel::append(), changeWindowFocus(), cx::cxPanel::delAllWindows(), cx::cxWindow::setTitle(), cx::cxPanel::showModal(), testOnFocusFunction(), testOnLeaveFunction(), and cxStringUtils::toString().
Referenced by doMenu().
cxPanelGetLastWindow()
void cxPanelGetLastWindow ()
References cx::cxPanel::append(), cx::eBS_SINGLE_LINE, cx::messageBox(), onFocusWinForCxPanelGetLastPage(), cx::cxPanel::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
cxPanelTest()
void cxPanelTest ()
References cx::cxPanel::append(), changeWindowFocus(), cx::cxPanel::delWindow(), form(), cx::getReturnCodeStr(), cx::cxMultiLineInput::getValue(), cx::cxPanel::getWindow(), cx::cxPanel::hide(), cx::messageBox(), cx::cxPanel::move(), cx::cxPanel::setCurrentWindow(), cx::cxPanel::setExitOnLeaveFirst(), cx::cxWindow::setTitle(), cx::cxPanel::showModal(), cx::cxPanel::swap(), testOnFocusFunction(), testOnLeaveFunction(), cxStringUtils::toString(), and cx::cxPanel::windowIsEnabled().
Referenced by doMenu().
cxPanelTest2()
void cxPanelTest2 ()
References cx::cxPanel::append(), cx::cxITEM_NORMAL, cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::eINPUT_READONLY, cx::height(), cx::cxWindow::height(), cx::cxPanel::showModal(), cxStringUtils::toString(), cx::width(), and cx::cxWindow::width().
Referenced by doMenu().
cxPanelWindowSwap()
void cxPanelWindowSwap ()
References cx::cxPanel::append(), cx::cxPanel::showModal(), cx::cxPanel::swap(), and cxStringUtils::toString().
Referenced by doMenu().
cxPanelWithButton()
void cxPanelWithButton ()
References cx::cxPanel::append(), buttonClickFunction(), cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, and cx::cxPanel::showModal().
Referenced by doMenu().
cxPanelWithNonEditableSubwindows()
void cxPanelWithNonEditableSubwindows ()
References cx::cxPanel::append(), cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::eINPUT_READONLY, cx::cxPanel::setExitOnLeaveLast(), and cx::cxPanel::showModal().
Referenced by doMenu().
cxSearchPanelCopyConstructor()
void cxSearchPanelCopyConstructor ()
References cx::eINPUT_EDITABLE, formOnEnter(), onFocusForm(), onFocusMenu(), onLeaveForm(), onLeaveMenu(), searchPanelOnFocus(), and cx::cxPanel::showModal().
Referenced by doMenu().
cxSearchPanelResize()
void cxSearchPanelResize ()
References cx::cxSearchPanel::appendToForm(), cx::eINPUT_EDITABLE, cx::cxSearchPanel::getForm(), cx::cxSearchPanel::getMenu(), cx::messageBox(), onFocusForm(), onFocusMenu(), onLeaveForm(), onLeaveMenu(), cx::cxSearchPanel::resize(), cx::cxSearchPanel::setFormHeight(), cx::cxSearchPanel::setFormOnFocusFunction(), cx::cxSearchPanel::setFormOnLeaveFunction(), cx::cxSearchPanel::setMenuHeight(), cx::cxSearchPanel::setMenuOnFocusFunction(), cx::cxSearchPanel::setMenuOnLeaveFunction(), and cx::cxPanel::showModal().
Referenced by doMenu().
cxSearchPanelTest()
void cxSearchPanelTest ()
References cx::cxSearchPanel::appendToForm(), cx::eINPUT_EDITABLE, formOnEnter(), cx::cxSearchPanel::getSelectedItem(), cx::cxSearchPanel::itemWasSelected(), cx::messageBox(), onFocusForm(), onFocusMenu(), onLeaveForm(), onLeaveMenu(), searchPanelOnFocus(), cx::cxSearchPanel::setFormOnEnterFunction(), cx::cxSearchPanel::setFormOnFocusFunction(), cx::cxSearchPanel::setFormOnLeaveFunction(), cx::cxSearchPanel::setMenuOnFocusFunction(), cx::cxSearchPanel::setMenuOnLeaveFunction(), cx::cxWindow::setOnFocusFunction(), and cx::cxPanel::showModal().
Referenced by doMenu().
cxWindowAddMessageLinesAbove()
void cxWindowAddMessageLinesAbove ()
References cx::cxWindow::addMessageLineAbove(), cx::cxWindow::addMessageLinesAbove(), and cx::cxWindow::show().
Referenced by doMenu().
cxWindowAlignTest()
void cxWindowAlignTest ()
References cx::cxWindow::alignHoriz(), cx::cxWindow::alignVert(), cx::cxWindow::center(), cx::eHP_CENTER, cx::eHP_LEFT, cx::eHP_RIGHT, cx::eVP_BOTTOM, cx::eVP_CENTER, cx::eVP_TOP, cx::cxWindow::info(), cx::messageBox(), cx::cxWindow::setMessage(), cx::cxWindow::show(), and cxStringUtils::toString().
Referenced by doMenu().
cxWindowAssignment()
void cxWindowAssignment ()
References cx::messageDialog(), cx::cxWindow::show(), and window1().
Referenced by doMenu().
cxWindowAttributesTest()
void cxWindowAttributesTest ()
References cx::eMESSAGE, cx::eSTATUS, cx::eTITLE, cx::cxWindow::setAttr(), cx::cxWindow::setMessage(), cx::cxWindow::setStatus(), cx::cxWindow::setTitle(), and cx::cxWindow::show().
Referenced by doMenu().
cxWindowBorderTest()
void cxWindowBorderTest ()
References cx::cxWindow::center(), cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::eBS_SPACE, cx::height(), cx::cxWindow::setMessage(), cx::cxWindow::show(), cx::cxWindow::toggleBorderBottom(), cx::cxWindow::toggleBorderLeft(), cx::cxWindow::toggleBorderRight(), and cx::cxWindow::toggleBorderTop().
Referenced by doMenu().
cxWindowCopyConstructor()
void cxWindowCopyConstructor ()
References cx::messageDialog(), sayHello(), sayHello2(), cx::cxWindow::showModal(), and window1().
Referenced by doMenu().
cxWindowMessageNewlines()
void cxWindowMessageNewlines ()
References cx::cxWindow::showModal().
cxWindowMouseFunctionTest()
void cxWindowMouseFunctionTest ()
References BUTTON1_CLICKED, BUTTON2_CLICKED, BUTTON3_CLICKED, mouseFunction(), cx::cxWindow::setMouseFunction(), and cx::cxWindow::showModal().
Referenced by doMenu().
cxWindowMoveRelative()
void cxWindowMoveRelative ()
References cx::cxWindow::moveRelative(), and cx::cxWindow::show().
cxWindowSizeTest()
void cxWindowSizeTest ()
References cx::cleanup(), cx::cxInitialized(), cx::cxWidgetsException::getErrorMsg(), cx::cxWindow::hide(), cx::init(), cx::messageBox(), and cx::cxWindow::show().
Referenced by doMenu().
cxWindowVariousBorderStyles()
void cxWindowVariousBorderStyles ()
References cx::eBorderStyleToStr(), cx::eBS_DOUBLE_LINE, cx::eBS_DOUBLE_TOP_SINGLE_SIDES, cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::eBS_SINGLE_TOP_DOUBLE_SIDES, and cx::eBS_SPACE.
Referenced by doMenu().
cxWindowWithFunctionKeys()
void cxWindowWithFunctionKeys ()
References cx::getReturnCodeStr(), cx::messageBox(), sayHello(), sayHello2(), cx::cxWindow::setKeyFunction(), and cx::cxWindow::showModal().
Referenced by doMenu().
cxWindowWithMultipleStatusStrings()
void cxWindowWithMultipleStatusStrings ()
References cx::cxWindow::addStatusString(), and cx::cxWindow::showModal().
Referenced by doMenu().
cxWindowWithMultipleTitleStrings()
void cxWindowWithMultipleTitleStrings ()
References cx::cxWindow::addTitleString(), cx::eBS_SINGLE_LINE, and cx::cxWindow::showModal().
Referenced by doMenu().
demoPanels()
void demoPanels ()
References cx::cxMenu::append(), cx::cxWindow::bringToBottom(), cx::cxWindow::bringToTop(), cx::cxWindow::hide(), cx::cxWindow::isAbove(), cx::cxWindow::isBelow(), cx::cxWindow::isOnBottom(), cx::cxWindow::isOnTop(), cx::messageBox(), cx::messageDialog(), cx::cxWindow::move(), cx::cxMenu::move(), cx::cxWindow::show(), cx::cxMenu::show(), cx::cxMenu::showModal(), and cx::cxWindow::unhide().
Referenced by doMenu().
doMenu()
void doMenu ()
References addMessageLine(), addMessageLineCode, allFormInputsGoReadOnly(), allFormInputsGoReadOnlyCode, cx::cxMenu::append(), cx::cxMenu::appendWithPullRight(), attributesSetter(), attributesSetterCode, borderlessForm(), borderlessFormCode, changeMenuItemText(), changeMenuItemTextCode, comboBox(), comboBoxCode, comboBoxMenuDisable(), comboBoxMenuDisableCode, comboBoxOnForm(), comboBoxOnFormCode, cxButtonOnClick(), cxButtonOnClickCode, cxComboBoxNotEditableMenuEnabled(), cxComboBoxNotEditableMenuEnabledCode, cxDatePickerTest(), cxDatePickerTestCode, cxFormAppendComboBoxPair(), cxFormAppendComboBoxPairCode, cxFormAppendPair(), cxFormAppendPairCode, cxFormAssignment(), cxFormAssignmentCode, cxFormClearOnlyEditable(), cxFormClearOnlyEditableCode, cxFormExtendedHelpKey(), cxFormExtendedHelpKeyCode, cxFormMouseFunctionTest(), cxFormMouseFunctionTestCode, cxFormMultiLineInputFunctionKeyNoValidator(), cxFormMultiLineInputFunctionKeyNoValidatorCode, cxFormNavKeys(), cxFormNavKeysCode, cxFormNoQuit(), cxFormStartAtFirstInput(), cxFormStartAtFirstInputCode, cxGridTest(), cxGridTestCode, cx::cxID_QUIT, cxInputBorderChange(), cxInputBorderChangeCode, cxInputMasking(), cx::cxITEM_NORMAL, cxMenuAltItemText(), cxMenuAltItemTextCode, cxMenuAssignment(), cxMenuAssignmentCode, cxMenuFocusFunctions(), cxMenuFocusFunctionsCode, cxMenuItemHotkeysOffMenu(), cxMenuItemHotkeysOffMenuCode, cxMenuMiscTests(), cxMenuMiscTestsCode, cxMenuMouseFunctionTest(), cxMenuMouseFunctionTestCode, cxMenuNoMoreSelectableItemsWhileModal(), cxMenuNoMoreSelectableItemsWhileModalCode, cxMenuNoQuit(), cxMenuResize(), cxMenuResizeCode, cxMenuScrolling(), cxMenuWithDuplicateHotkeys(), cxMenuWithDuplicateHotkeysCode, cxMenuWithMultipleItemHotkeys(), cxMenuWithMultipleItemHotkeysCode, cxMultiLineInputAutoGenerateHelpString(), cxMultiLineInputAutoGenerateHelpStringCode, cxMultiLineInputBorderChange(), cxMultiLineInputBorderChangeCode, cxMultiLineInputExtendedHelpColorsAndAttrs(), cxMultiLineInputExtendedHelpColorsAndAttrsCode, cxMultiLineInputExtendedHelpKey(), cxMultiLineInputExtendedHelpKeyCode, cxMultiLineInputForceUpper(), cxMultiLineInputForceUpperCode, cxMultiLineInputFunctionKeyNoValidator(), cxMultiLineInputFunctionKeyNoValidatorCode, cxMultiLineInputMasking(), cxMultiLineInputMaxInputLength(), cxMultiLineInputMaxInputLengthCode, cxMultiLineInputNonBlank(), cxMultiLineInputNonBlankCode, cxMultiLineInputNumericFloatingPt(), cxMultiLineInputNumericFloatingPtCode, cxMultiLineInputNumericFloatingPtWithRange(), cxMultiLineInputNumericFloatingPtWithRangeCode, cxMultiLineInputNumericWhole(), cxMultiLineInputNumericWholeCode, cxMultiLineInputNumericWholeWithRange(), cxMultiLineInputNumericWholeWithRangeCode, cxMultiLineInputOverrideOnKeypress(), cxMultiLineInputOverrideOnKeypressCode, cxMultiLineInputSetValue(), cxMultiLineInputSetValueCode, cxMultiLineInputTextValidation(), cxMultiLineInputTextValidationAutoCompletion(), cxMultiLineInputTextValidationAutoCompletionCode, cxMultiLineInputTextValidationCode, cxMultiLineInputTextValidationNonBlankForceUpper(), cxMultiLineInputTextValidationNonBlankForceUpperCode, cxMultiLineInputWithRightLabel(), cxMultiLineInputWithRightLabelCode, cxMultiLineInputWithRightLabelOnForm(), cxMultiLineInputWithRightLabelOnFormCode, cxNotebookRemoveWindowTest(), cxNotebookRemoveWindowTestCode, cxNotebookSetTabSpacing(), cxNotebookSetTabSpacingCode, cxNotebookSwapTest(), cxNotebookSwapTestCode, cxNotebookTest1(), cxNotebookTest1Code, cxNotebookTest2(), cxNotebookTest2Code, cxNotebookWithEmptyPanelTest(), cxNotebookWithEmptyPanelTestCode, cxOpenFileDialogTest(), cxOpenFileDialogTestCode, cxPanel_cxMenuUpArrowLeave(), cxPanel_cxMenuUpArrowLeaveCode, cxPanelCode, cxPanelCode2, cxPanelDelAllWindowsCode, cxPanelDelAllWindowsTest(), cxPanelGetLastWindow(), cxPanelGetLastWindowCode, cxPanelTest(), cxPanelTest2(), cxPanelWindowSwap(), cxPanelWindowSwapCode, cxPanelWithButton(), cxPanelWithButtonTestCode, cxPanelWithNonEditableSubwindows(), cxPanelWithNonEditableSubwindowsCode, cxSearchPanelCopyConstructor(), cxSearchPanelCopyConstructorCode, cxSearchPanelResize(), cxSearchPanelResizeCode, cxSearchPanelTest(), cxSearchPanelTestCode, cxWindowAddMessageLinesAbove(), cxWindowAddMessageLinesAboveCode, cxWindowAlignCode, cxWindowAlignTest(), cxWindowAssignment(), cxWindowAssignmentCode, cxWindowAttributesCode, cxWindowAttributesTest(), cxWindowBorderCode, cxWindowBorderStyles, cxWindowBorderTest(), cxWindowCopyConstructor(), cxWindowCopyConstructorCode, cxWindowMouseFunctionTest(), cxWindowMouseFunctionTestCode, cxWindowSizeCode, cxWindowSizeTest(), cxWindowVariousBorderStyles(), cxWindowWithFunctionKeys(), cxWindowWithFunctionKeysCode, cxWindowWithMultipleStatusStrings(), cxWindowWithMultipleStatusStringsCode, cxWindowWithMultipleTitleStrings(), cxWindowWithMultipleTitleStringsCode, demoPanels(), enableDisableForm(), enableDisableFormCode, exitCode, externalStatusWindow(), externalTitleWindow(), extStatusWinCode, extTitleWinCode, fileViewer(), fileViewerCode, floatingPtValidate(), floatingPtValidateCode, form(), formChangeInputFocusWhileModal(), formChangeInputFocusWhileModalCode, formCode, formDataChanged(), formDataChangedCode, formFunctionKeyNoOnLeave(), formFunctionKeyNoOnLeaveCode, formInputColors(), formInputColorsCode, formNoQuitCode, formWithFKeys(), formWithFKeysCode, formWithInputValueValidator(), formWithInputValueValidatorCode, formWithMenu(), formWithMenuCode, gStatusLine, gTitleLine, cx::cxWindow::hide(), inputCode, inputLabelChangeCode, inputMaskingCode, inputQuitKeysOnForm(), inputQuitKeysOnFormCode, inputsWithDifferentColors(), inputsWithDifferentColorsCode, inputsWithFKeys(), inputWithFKeysCode, inputWithoutBorder(), inputWithoutBorderCode, integerValidate(), integerValidateCode, itemSales(), itemSalesCode, keyFunctionAutoExitOnLastFormInput(), keyFunctionAutoExitOnLastFormInputCode, loneInputWithLoopDisabledOnForm(), loneInputWithLoopDisabledOnFormCode, menuCode, menuItemWithMultipleHotkeyCode, menuItemWithMultipleHotkeys(), menuNoQuitCode, menuScrollingCode, cx::messageBox(), msgBox1(), msgBox1Code, msgBox2(), msgBox2Code, msgBox3(), msgBox3Code, msgBox4(), msgBox4Code, msgCancel(), msgCancelCode, msgNo(), msgNoCode, msgNoYes(), msgNoYesCode, msgOK(), msgOKCancel(), msgOKCancelCode, msgOKCode, msgYes(), msgYesCode, msgYesNo(), msgYesNoCode, multiForm2(), multiForm2Code, multiFormWithDisabledSubform(), multiFormWithDisabledSubformCode, multiInputMaskingCode, multiLineInput(), multiLineInputCode, multiLineInputLabelChangeCode, multiLineInputResize(), multiLineInputResizeCode, panelDemoCode, scrolledWindow(), scrolledWindowCode, setInputLabel(), setMultiLineInputLabel(), setValFunc(), setValFuncCode, cx::cxMenu::setWrapping(), cx::cxMenu::showModal(), singleLineInput(), singleLineInputCode, someItem, splash1(), splash1Code, splash2(), splash2Code, stackedFormScrolling(), stackedFormScrolling2(), stackedFormScrollingCode, stackedFormScrollingCode2, statusAlignment(), statusAlignmentCode, testFormPos(), testFormPosCode, testFormReadOnly(), testFormReadOnlyCode, testInput1(), testMenu1(), titleAlignment(), titleAlignmentCode, window1(), windowCode, windowFunctionKeyNoOnLeave(), and windowFunctionKeyNoOnLeaveCode.
Referenced by main().
enableDisableForm()
void enableDisableForm ()
References cx::cxForm::append(), cx::getReturnCodeStr(), cx::cxWindow::isEnabled(), cx::messageBox(), cx::cxForm::setAutoExit(), cx::cxForm::setEnabled(), and cx::cxForm::showModal().
Referenced by doMenu().
externalStatusWindow()
void externalStatusWindow ()
References cx::cxMenu::append(), cx::cxITEM_NORMAL, cx::eBS_NOBORDER, cx::cxWindow::setExtStatusWindow(), cx::cxMenu::setStatus(), and cx::cxMenu::showModal().
Referenced by doMenu().
externalTitleWindow()
void externalTitleWindow ()
References cx::cxMenu::append(), cx::cxITEM_NORMAL, gTitleLine, cx::cxWindow::setExtTitleWindow(), cx::cxMenu::setStatus(), and cx::cxMenu::showModal().
Referenced by doMenu().
fileViewer()
void fileViewer ()
References cx::cxScrolledWindow::showModal().
Referenced by doMenu().
fKeySort()
bool fKeySort (const string & pStr1, const string & pStr2)
References cxStringUtils::stringToUnsigned().
Referenced by getFormKeys().
floatingPtValidate()
void floatingPtValidate ()
References cx::eINPUT_TYPE_NUMERIC_FLOATING_PT, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
floatingPtValidateOnForm()
void floatingPtValidateOnForm ()
References cx::cxForm::append(), cxValidators::floatingPtOnKeyValidator(), cx::cxForm::setOnKeyFunction(), and cx::cxForm::showModal().
form()
void form ()
References cx::cxForm::append(), cx::cxID_EXIT, cx::cxID_QUIT, cx::eDATA_EDITABLE, cx::eINPUT_READONLY, ENTER, ESC, cx::cxForm::firstEditableInput(), cx::cxForm::getInput(), cx::cxForm::getValue(), inputYesNo(), cx::cxForm::lastEditableInput(), cx::messageBox(), cx::cxForm::setAutoExit(), cx::cxForm::setCanBeEditable(), cx::cxForm::setOnKeyFunction(), cx::cxForm::setValue(), cx::cxForm::showModal(), and cxStringUtils::toString().
Referenced by cxPanelTest(), doMenu(), cx::cxMultiForm::getForm(), and multiFormWithDisabledSubform().
formChangeInputFocusWhileModal()
void formChangeInputFocusWhileModal ()
References cx::cxForm::addInputJumpKey(), cx::cxForm::append(), cx::messageBox(), cx::cxForm::setAutoExit(), and cx::cxForm::showModal().
Referenced by doMenu().
formDataChanged()
void formDataChanged ()
References cx::cxForm::append(), cx::cxForm::hasChanged(), cx::messageBox(), cx::cxForm::setAutoExit(), and cx::cxForm::showModal().
Referenced by doMenu().
formFunctionKeyNoOnLeave()
void formFunctionKeyNoOnLeave ()
References cx::cxForm::append(), cx::messageBox(), cx::cxForm::setAutoExit(), cx::cxForm::setKeyFunction(), cx::cxForm::setOnLeaveFunction(), cx::cxForm::showModal(), testKeyFunction(), and testOnLeaveFunction().
Referenced by doMenu().
formFunctionKeys()
void formFunctionKeys ()
References cx::cxForm::append(), cx::eBS_SINGLE_LINE, genericMessageFunction(), cx::messageBox(), cx::cxForm::setKeyFunction(), showAMessageBox(), and cx::cxForm::showModal().
formInputColors()
void formInputColors ()
References cx::cxForm::addAttr(), cx::cxForm::append(), cx::cxForm::clearInputs(), cx::eBRTBLUE_WHITE, cx::eBRTGREEN_BLACK, cx::eBRTRED_BLACK, cx::eDATA_EDITABLE, cx::eINPUT_READONLY, cx::eLABEL, cx::eYELLOW_BLACK, cx::eYELLOW_GREEN, cx::eYELLOW_WHITE, cx::cxForm::removeAttr(), cx::cxForm::removeAttrs(), cx::cxForm::setAllColors(), cx::cxForm::setLabelColor(), cx::cxForm::setValue(), cx::cxForm::setValueColor(), cx::cxForm::showModal(), and cx::cxForm::toggleMasking().
Referenced by doMenu().
formOnEnter()
string formOnEnter (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::getMenu().
Referenced by cxSearchPanelCopyConstructor(), and cxSearchPanelTest().
formUpArrowFunction()
void formUpArrowFunction ()
References cx::cxForm::append(), genericMessageFunction(), cx::cxWindow::getLastKey(), cx::messageBox(), cx::noOp(), cx::cxForm::setKeyFunction(), cx::cxForm::setOnLeaveFunction(), cx::cxForm::showModal(), and cxStringUtils::toString().
formWithFKeys()
void formWithFKeys ()
References cx::cxForm::append(), cx::cxFunction2RefTemplated< T1, T2 >::create(), genericMessageFunction(), cx::cxForm::getValue(), cx::messageBox(), returnBBye(), cx::cxForm::setFieldKeyFunction(), cx::cxForm::setKeyFunction(), cx::cxForm::setOnLeaveFunction(), cx::cxForm::showModal(), and someFunction().
Referenced by doMenu().
formWithInputValueValidator()
void formWithInputValueValidator ()
References cx::cxForm::append(), cx::cxFunction1RefTemplated< T1 >::create(), cx::messageBox(), cx::cxForm::setValidatorFunction(), cx::cxForm::showModal(), and someFunction3().
Referenced by doMenu().
formWithMenu()
void formWithMenu ()
References cx::cxMenu::append(), cx::cxForm::append(), cx::cxID_QUIT, cx::cxForm::setAutoExit(), cx::cxForm::showModal(), cx::cxMenu::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
genericMessageFunction()
string genericMessageFunction ()
References cx::messageBox().
Referenced by formFunctionKeys(), formUpArrowFunction(), and formWithFKeys().
genericMessageFunction_1str()
string genericMessageFunction_1str (string & pMessage)
References cx::messageBox().
Referenced by cxInputOnFormLoopDisabled(), cxMenuFocusFunctions(), inputQuitKeysOnForm(), and loneInputWithLoopDisabledOnForm().
getFormKeys()
void getFormKeys ()
References cx::cxForm::append(), cx::cxFunction2RefTemplated< T1, T2 >::create(), fKeySort(), cx::cxWindow::getFunctionKeyStrings(), cx::messageBox(), cx::cxForm::setKeyFunction(), and someFunction().
getMenuItemIDStr()
string getMenuItemIDStr (long pMenuItemID)
References allFormInputsGoReadOnlyCode, attributesSetterCode, borderlessFormCode, changeMenuItemTextCode, comboBoxCode, comboBoxMenuDisableCode, comboBoxOnFormCode, cxComboBoxNotEditableMenuEnabledCode, cxDatePickerTestCode, cxFormAppendComboBoxPairCode, cxFormAppendPairCode, cxFormAssignmentCode, cxFormClearOnlyEditableCode, cxFormExtendedHelpKeyCode, cxFormMouseFunctionTestCode, cxFormMultiLineInputFunctionKeyNoValidatorCode, cxFormNavKeysCode, cxFormStartAtFirstInputCode, cxGridTestCode, cxInputBorderChangeCode, cxMenuAltItemTextCode, cxMenuAssignmentCode, cxMenuFocusFunctionsCode, cxMenuItemHotkeysOffMenuCode, cxMenuMiscTestsCode, cxMenuMouseFunctionTestCode, cxMenuNoMoreSelectableItemsWhileModalCode, cxMenuResizeCode, cxMenuWithDuplicateHotkeysCode, cxMenuWithMultipleItemHotkeysCode, cxMultiLineInputAutoGenerateHelpStringCode, cxMultiLineInputBorderChangeCode, cxMultiLineInputExtendedHelpColorsAndAttrsCode, cxMultiLineInputExtendedHelpKeyCode, cxMultiLineInputForceUpperCode, cxMultiLineInputFunctionKeyNoValidatorCode, cxMultiLineInputMaxInputLengthCode, cxMultiLineInputNonBlankCode, cxMultiLineInputNumericFloatingPtCode, cxMultiLineInputNumericFloatingPtWithRangeCode, cxMultiLineInputNumericWholeCode, cxMultiLineInputNumericWholeWithRangeCode, cxMultiLineInputOverrideOnKeypressCode, cxMultiLineInputSetValueCode, cxMultiLineInputTextValidationAutoCompletionCode, cxMultiLineInputTextValidationCode, cxMultiLineInputTextValidationNonBlankForceUpperCode, cxMultiLineInputWithRightLabelCode, cxMultiLineInputWithRightLabelOnFormCode, cxNotebookRemoveWindowTestCode, cxNotebookSetTabSpacingCode, cxNotebookSwapTestCode, cxNotebookTest1Code, cxNotebookTest2Code, cxNotebookWithEmptyPanelTestCode, cxOpenFileDialogTestCode, cxPanel_cxMenuUpArrowLeaveCode, cxPanelCode, cxPanelCode2, cxPanelDelAllWindowsCode, cxPanelGetLastWindowCode, cxPanelWindowSwapCode, cxPanelWithButtonTestCode, cxPanelWithNonEditableSubwindowsCode, cxSearchPanelCopyConstructorCode, cxSearchPanelResizeCode, cxSearchPanelTestCode, cxWindowAddMessageLinesAboveCode, cxWindowAlignCode, cxWindowAssignmentCode, cxWindowAttributesCode, cxWindowBorderCode, cxWindowBorderStyles, cxWindowCopyConstructorCode, cxWindowMouseFunctionTestCode, cxWindowSizeCode, cxWindowWithFunctionKeysCode, cxWindowWithMultipleStatusStringsCode, cxWindowWithMultipleTitleStringsCode, enableDisableFormCode, exitCode, extStatusWinCode, extTitleWinCode, fileViewerCode, floatingPtValidateCode, formChangeInputFocusWhileModalCode, formCode, formDataChangedCode, formFunctionKeyNoOnLeaveCode, formInputColorsCode, formNoQuitCode, formWithFKeysCode, formWithInputValueValidatorCode, formWithMenuCode, cx::getReturnCodeStr(), inputCode, inputLabelChangeCode, inputMaskingCode, inputQuitKeysOnFormCode, inputsWithDifferentColorsCode, inputWithFKeysCode, inputWithoutBorderCode, integerValidateCode, itemSalesCode, keyFunctionAutoExitOnLastFormInputCode, loneInputWithLoopDisabledOnFormCode, menuCode, menuItemWithMultipleHotkeyCode, menuNoQuitCode, menuScrollingCode, msgBox1Code, msgBox2Code, msgBox3Code, msgBox4Code, msgCancelCode, msgNoCode, msgNoYesCode, msgOKCancelCode, msgOKCode, msgYesCode, msgYesNoCode, multiForm2Code, multiFormWithDisabledSubformCode, multiInputMaskingCode, multiLineInputCode, multiLineInputLabelChangeCode, multiLineInputResizeCode, panelDemoCode, scrolledWindowCode, setValFuncCode, singleLineInputCode, someItem, splash1Code, splash2Code, stackedFormScrollingCode, stackedFormScrollingCode2, statusAlignmentCode, testFormPosCode, testFormReadOnlyCode, titleAlignmentCode, windowCode, windowFunctionKeyNoOnLeaveCode, and windowWriteTextCode.
gridButtonClicked()
string gridButtonClicked ()
References cx::messageBox().
hello()
string hello ()
References cx::messageBox().
Referenced by cxMultiLineInputNumericWhole().
inputQuitKeysOnForm()
void inputQuitKeysOnForm ()
References cx::cxForm::addQuitKey(), cx::cxForm::append(), cx::cxFunction1RefTemplated< T1 >::create(), genericMessageFunction_1str(), cx::getReturnCodeStr(), cx::messageBox(), cx::cxForm::removeQuitKey(), cx::cxForm::setAutoExit(), cx::cxForm::setOnLeaveFunction(), cx::cxForm::setValidatorFunction(), SHIFT_F2, SHIFT_F3, cx::cxForm::showModal(), and testBoxSuccess().
Referenced by doMenu().
inputsWithDifferentColors()
void inputsWithDifferentColors ()
References cx::eBLUE_WHITE, cx::eBRTCYAN_BLUE, cx::eYELLOW_BLUE, cx::eYELLOW_WHITE, cx::cxInput::setLabelColor(), cx::cxMultiLineInput::setLabelColor(), cx::cxInput::setValue(), cx::cxMultiLineInput::setValue(), cx::cxInput::setValueColor(), cx::cxMultiLineInput::setValueColor(), cx::cxInput::show(), and cx::cxMultiLineInput::show().
Referenced by doMenu().
inputsWithFKeys()
void inputsWithFKeys ()
References cx::cxFunction1RefTemplated< T1 >::create(), cx::cxFunction2RefTemplated< T1, T2 >::create(), cx::messageBox(), returnBBye(), and someFunction2().
Referenced by doMenu().
inputWithoutBorder()
void inputWithoutBorder ()
References cx::cxForm::append(), cx::eBS_NOBORDER, and cx::cxForm::showModal().
Referenced by doMenu().
inputYesNo()
string inputYesNo (void * theInput, void * unused, void * unused2, void * unused3)
References cx::cxMultiLineInput::getValue(), and cx::cxMultiLineInput::setValue().
Referenced by cxFormAssignment(), and form().
integerValidate()
void integerValidate ()
References cx::eINPUT_TYPE_NUMERIC_WHOLE, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::setInputType(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
integerValidateOnForm()
void integerValidateOnForm ()
References cx::cxForm::append(), cxValidators::intOnKeyValidator(), cx::cxForm::setOnKeyFunction(), and cx::cxForm::showModal().
itemSales()
void itemSales ()
References cx::cxWindow::addMessageLineBelow(), cx::cxForm::allValidateOnJumpKey(), cx::cxForm::append(), cx::cxForm::appendPair(), cx::cxID_QUIT, cx::eINPUT_EDITABLE, cx::eINPUT_READONLY, cx::eINPUT_TYPE_NUMERIC_WHOLE, cx::cxWindow::hide(), cx::cxForm::setAutoExit(), cx::cxForm::showModal(), cx::cxScrolledWindow::showModal(), storeOnLeave(), storeSearch(), and cxStringUtils::toString().
Referenced by doMenu().
keyFunctionAutoExitOnLastFormInput()
void keyFunctionAutoExitOnLastFormInput ()
References cx::cxForm::append(), cx::eBS_SINGLE_LINE, cx::messageBox(), cx::cxForm::setAutoExit(), showAMessageBox(), and cx::cxForm::showModal().
Referenced by doMenu().
loneInputWithLoopDisabledOnForm()
void loneInputWithLoopDisabledOnForm ()
References cx::cxForm::append(), cx::cxFunction1RefTemplated< T1 >::create(), genericMessageFunction_1str(), cx::cxForm::setAutoExit(), and cx::cxForm::showModal().
Referenced by doMenu().
main()
int main (int argc, char * argv[])
References cx::cleanup(), doMenu(), cx::eBS_NOBORDER, cx::eDATA_EDITABLE, cx::eHP_CENTER, cx::getAttr(), gStatusLine, gTitleLine, cx::height(), cx::init(), cx::setAttr(), cx::cxObject::UseColors(), and cx::width().
menuItemWithMultipleHotkeys()
void menuItemWithMultipleHotkeys ()
References cx::cxMenu::append(), cx::messageBox(), and cx::cxMenu::showModal().
Referenced by doMenu().
menuOnEnter()
string menuOnEnter (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::getMenu(), and cx::messageBox().
mouseFunction()
string mouseFunction (void * theWindow, void * unused)
References cx::cxWindow::getMouseStateStr(), cx::cxWindow::getTitle(), and cx::messageBox().
Referenced by cxFormMouseFunctionTest(), cxMenuMouseFunctionTest(), and cxWindowMouseFunctionTest().
msgBox1()
void msgBox1 ()
References cx::eBS_NOBORDER, and cx::messageBox().
Referenced by doMenu().
msgBox2()
void msgBox2 ()
References cx::messageBox().
Referenced by doMenu().
msgBox3()
void msgBox3 ()
References cx::messageBox().
Referenced by doMenu().
msgBox4()
void msgBox4 ()
References cx::messageBox().
Referenced by doMenu().
msgCancel()
void msgCancel ()
References cx::cxCANCEL, cx::cxID_OK, cx::messageBox(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
msgNo()
void msgNo ()
References cx::cxID_OK, cx::cxNO, cx::messageBox(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
msgNoYes()
void msgNoYes ()
References cx::cxID_OK, cx::cxNO, cx::cxYES, cx::cxMessageDialog::getCancelButton(), cx::messageBox(), cx::cxMessageDialog::setFocus(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
msgOK()
void msgOK ()
References cx::cxID_OK, cx::cxOK, cx::messageBox(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
msgOKCancel()
void msgOKCancel ()
References cx::cxCANCEL, cx::cxID_OK, cx::cxOK, cx::messageBox(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
msgYes()
void msgYes ()
References cx::cxID_OK, cx::cxYES, cx::messageBox(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
msgYesNo()
void msgYesNo ()
References cx::cxID_OK, cx::cxNO, cx::cxYES, cx::messageBox(), and cx::cxMessageDialog::showModal().
Referenced by doMenu().
multiForm()
void multiForm ()
References cx::cxForm::append(), cx::cxMultiForm::appendForm(), cx::eBS_NOBORDER, cx::eBS_SINGLE_LINE, cx::cxMultiForm::move(), cx::cxForm::setAutoExit(), and cx::cxMultiForm::showModal().
Referenced by cx::cxPanel::exitNow(), and cx::cxPanel::quitNow().
multiForm2()
void multiForm2 ()
References cx::cxMultiForm::appendForm(), cx::eBS_SINGLE_LINE, multiForm2_goToForm1_Input1(), multiForm2_goToForm3_Input1(), multiForm2_quit(), cx::cxForm::setAutoExit(), cx::cxMultiForm::setKeyFunction(), and cx::cxMultiForm::showModal().
Referenced by doMenu().
multiForm2_goToForm1_Input1()
string multiForm2_goToForm1_Input1 (void * theMultiForm, void * unused, void * unused2, void * unused3)
References cx::cxMultiForm::getForm(), and cx::cxMultiForm::setCurrentSubform().
Referenced by multiForm2().
multiForm2_goToForm3_Input1()
string multiForm2_goToForm3_Input1 (void * theMultiForm, void * unused, void * unused2, void * unused3)
References cx::cxMultiForm::getForm(), and cx::cxMultiForm::setCurrentSubform().
Referenced by multiForm2().
multiForm2_quit()
string multiForm2_quit (void * theMultiForm, void * unused, void * unused2, void * unused3)
References cx::cxForm::quitNow().
Referenced by multiForm2().
multiFormWithDisabledSubform()
void multiFormWithDisabledSubform ()
References cx::cxForm::append(), cx::cxMultiForm::appendForm(), cx::eBS_SINGLE_LINE, form(), cx::messageBox(), cx::cxMultiForm::setSubformEnabled(), and cx::cxMultiForm::showModal().
Referenced by doMenu().
multiLineInput()
void multiLineInput ()
References cx::cxMultiLineInput::getValue(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
multiLineInputResize()
void multiLineInputResize ()
References cx::eBS_SINGLE_LINE, cx::cxMultiLineInput::getValue(), cx::messageBox(), cx::cxMultiLineInput::resize(), and cx::cxMultiLineInput::showModal().
Referenced by doMenu().
onFocus()
string onFocus (void * unused, void * unused2, void * unused3, void * unused4)
References cx::messageBox().
onFocusForm()
string onFocusForm (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::getMenu().
Referenced by cxSearchPanelCopyConstructor(), cxSearchPanelResize(), and cxSearchPanelTest().
onFocusMenu()
string onFocusMenu (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::appendToMenu(), cx::cxSearchPanel::clearMenu(), cx::cxSearchPanel::getForm(), cx::cxSearchPanel::getMenu(), and cx::cxWindow::show().
Referenced by cxSearchPanelCopyConstructor(), cxSearchPanelResize(), and cxSearchPanelTest().
onFocusWinForCxPanelGetLastPage()
string onFocusWinForCxPanelGetLastPage (void * thePanel, void * theCurrentWindow, void * unused2, void * unused3)
References cx::cxPanel::getLastWindow(), cx::cxWindow::getTitle(), and cx::messageBox().
Referenced by cxPanelGetLastWindow().
onLeave()
string onLeave (void * unused, void * unused2, void * unused3, void * unused4)
References cx::messageBox().
onLeaveForm()
string onLeaveForm (void * theSearchPanel, void * unused, void * unused2, void * unused3)
Referenced by cxSearchPanelCopyConstructor(), cxSearchPanelResize(), and cxSearchPanelTest().
onLeaveMenu()
string onLeaveMenu (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::getMenu().
Referenced by cxSearchPanelCopyConstructor(), cxSearchPanelResize(), and cxSearchPanelTest().
returnBBye()
string returnBBye ()
Referenced by formWithFKeys(), and inputsWithFKeys().
sayHello()
string sayHello (void * p1, void * p2)
References cx::cxWindow::getName(), and cx::messageBox().
Referenced by cxWindowCopyConstructor(), and cxWindowWithFunctionKeys().
sayHello2()
string sayHello2 (void * p1, void * p2)
References cx::cxWindow::getName(), and cx::messageBox().
Referenced by cxWindowCopyConstructor(), and cxWindowWithFunctionKeys().
scrolledWindow()
void scrolledWindow ()
References cx::cxScrolledWindow::showModal().
Referenced by doMenu().
searchPanelOnFocus()
string searchPanelOnFocus (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::getForm(), and cx::cxPanel::setCurrentWindow().
Referenced by cxSearchPanelCopyConstructor(), and cxSearchPanelTest().
setAllInputsReadOnly()
string setAllInputsReadOnly (void * theForm, void * unused, void * unused2, void * unused3)
References cx::eINPUT_READONLY, and cx::cxForm::setAllInputOption().
Referenced by allFormInputsGoReadOnly().
setInputLabel()
void setInputLabel ()
References cx::cxInput::getValue(), cx::messageBox(), cx::cxInput::setLabel(), and cx::cxInput::showModal().
Referenced by doMenu().
setMultiLineInputLabel()
void setMultiLineInputLabel ()
References cx::cxMultiLineInput::setLabel(), and cx::cxMultiLineInput::show().
Referenced by doMenu().
setValFunc()
void setValFunc ()
References cx::cxForm::append(), cx::cxID_QUIT, cx::height(), cx::cxForm::setOnLeaveFunction(), cx::cxForm::setValue(), cx::cxForm::showModal(), testBoxSuccess(), and cx::width().
Referenced by doMenu().
showAMessageBox()
string showAMessageBox (void * classTypeStr, void * unused)
References cx::messageBox().
Referenced by formFunctionKeys(), and keyFunctionAutoExitOnLastFormInput().
simpleForm1()
void simpleForm1 ()
References cx::cxForm::append(), cx::cxWindow::center(), cx::eINPUT_READONLY, and cx::cxForm::showModal().
singleLineInput()
void singleLineInput ()
References cx::eBS_NOBORDER, cx::eINPUT_EDITABLE, cx::cxInput::getValidatorStr(), cx::cxInput::getValue(), cx::cxInput::setValidator(), and cx::cxInput::showModal().
Referenced by doMenu().
someFunction()
string someFunction (int & int1, int & int2)
References cx::messageBox().
Referenced by formWithFKeys(), and getFormKeys().
someFunction2()
string someFunction2 (cxMultiLineInput & input)
References cx::cxMultiLineInput::setValue().
Referenced by inputsWithFKeys().
someFunction3()
string someFunction3 (cxMultiLineInput & input)
References cx::cxMultiLineInput::getValue(), and cx::messageBox().
Referenced by formWithInputValueValidator().
someWeirdFunc()
string someWeirdFunc (void * theForm, void * unused)
References cx::messageBox().
splash1()
void splash1 ()
References cx::splash().
Referenced by doMenu().
splash2()
void splash2 ()
References cx::splash().
Referenced by doMenu().
stackedFormScrolling()
void stackedFormScrolling ()
References cx::cxForm::append(), cx::eBS_SINGLE_LINE, and cx::cxForm::showModal().
Referenced by doMenu().
stackedFormScrolling2()
void stackedFormScrolling2 ()
References cx::cxForm::append(), cx::eBS_SINGLE_LINE, cx::cxForm::showModal(), and cxStringUtils::toString().
Referenced by doMenu().
statusAlignment()
void statusAlignment ()
References cx::eHP_CENTER, cx::eHP_LEFT, cx::eHP_RIGHT, cx::cxWindow::setHorizStatusAlignment(), cx::cxWindow::setStatus(), and cx::cxWindow::show().
Referenced by doMenu().
storeOnLeave()
string storeOnLeave (void * theInput, void * unused)
References cx::cxMultiLineInput::getValue(), and cx::cxMultiLineInput::setRightLabel().
Referenced by itemSales().
storeSearch()
string storeSearch (void * theInput, void * unused)
References cx::cxSearchPanel::appendToForm(), cx::cxID_QUIT, cx::eINPUT_EDITABLE, cx::cxSearchPanel::getMenu(), cx::cxSearchPanel::getSelectedItem(), cx::cxMultiLineInput::getValue(), cx::cxSearchPanel::setFormHeight(), cx::cxSearchPanel::setFormOnEnterFunction(), cx::cxMultiLineInput::setValue(), cx::cxPanel::showModal(), and storeSearchFormOnEnter().
Referenced by itemSales().
storeSearchFormOnEnter()
string storeSearchFormOnEnter (void * theSearchPanel, void * unused, void * unused2, void * unused3)
References cx::cxSearchPanel::getMenu().
Referenced by storeSearch().
storeSearchMenuOnEnter()
string storeSearchMenuOnEnter (void * theSearchPanel, void * unused, void * unused2, void * unused3)
testBoxSuccess()
string testBoxSuccess (void * Foo1, void * Foo2, void * Foo3, void * Foo4)
References cx::messageBox().
Referenced by inputQuitKeysOnForm(), and setValFunc().
testFormPos()
void testFormPos ()
References cx::cxForm::append(), cx::cxWindow::bottom(), cx::eINPUT_EDITABLE, cx::cxWindow::right(), and cx::cxForm::showModal().
Referenced by doMenu().
testFormReadOnly()
void testFormReadOnly ()
References cx::cxForm::append(), cx::cxID_QUIT, cx::dump(), cx::eINPUT_EDITABLE, cx::eINPUT_READONLY, cx::cxForm::setAutoExit(), cx::cxForm::setInputOption(), cx::cxForm::setStatus(), cx::cxForm::show(), and cx::cxForm::showModal().
Referenced by doMenu().
testInput1()
void testInput1 ()
References cx::cxInput::addAttr(), cx::eBS_SINGLE_LINE, cx::eDATA_EDITABLE, cx::eLABEL, cx::cxInput::getValue(), cx::messageBox(), cx::cxInput::move(), cx::cxInput::removeAttrs(), cx::cxInput::setExitOnFull(), and cx::cxInput::showModal().
Referenced by doMenu().
testInput2()
void testInput2 ()
References cx::cxInput::getValue(), cx::cxInput::show(), cx::cxWindow::show(), and cx::cxInput::showModal().
testInputValidator()
string testInputValidator (void * theMultiLineInput, void * unused2, void * unused3, void * unused4)
References cx::cxMultiLineInput::getValue(), and cx::messageBox().
Referenced by cxFormMultiLineInputFunctionKeyNoValidator(), and cxMultiLineInputFunctionKeyNoValidator().
testKeyFunction()
string testKeyFunction (void * unused, void * unused2)
References cx::messageBox().
Referenced by cxFormMultiLineInputFunctionKeyNoValidator(), cxMultiLineInputFunctionKeyNoValidator(), formFunctionKeyNoOnLeave(), and windowFunctionKeyNoOnLeave().
testMenu1()
void testMenu1 ()
References cx::cxMenu::append(), cx::cxMenu::appendWithPullRight(), cx::cxWindow::bottom(), cx::cxFIRST_AVAIL_RETURN_CODE, cx::cxID_EXIT, cx::cxID_QUIT, cx::cxMenu::itemWasSelected(), cx::messageBox(), cx::cxWindow::numSubWindows(), and cx::cxMenu::showModal().
Referenced by doMenu().
testOnFocusFunction()
string testOnFocusFunction (void * unused, void * unused2, void * unused3, void * unused4)
References cx::messageBox().
Referenced by cxPanelDelAllWindowsTest(), and cxPanelTest().
testOnLeaveFunction()
string testOnLeaveFunction (void * unused, void * unused2, void * unused3, void * unused4)
References cx::messageBox().
Referenced by cxFormMultiLineInputFunctionKeyNoValidator(), cxPanelDelAllWindowsTest(), cxPanelTest(), formFunctionKeyNoOnLeave(), and windowFunctionKeyNoOnLeave().
titleAlignment()
void titleAlignment ()
References cx::eHP_CENTER, cx::eHP_LEFT, cx::eHP_RIGHT, cx::cxWindow::setHorizTitleAlignment(), cx::cxWindow::setTitle(), and cx::cxWindow::show().
Referenced by doMenu().
unselectableMenuItem()
void unselectableMenuItem ()
References cx::cxMenu::append(), cx::messageBox(), cx::cxMenu::showModal(), cx::cxMenu::toggleSelectability(), and cxStringUtils::toString().
updateMenu()
string updateMenu (void * theComboBox, void * unused, void * unused2, void * unused3)
References cx::cxComboBox::appendToMenu(), and cx::cxMultiLineInput::getValue().
Referenced by comboBox(), comboBoxMenuDisable(), and comboBoxOnForm().
window1()
void window1 ()
References cx::cxWindow::show().
Referenced by cxWindowAssignment(), cxWindowCopyConstructor(), and doMenu().
windowFunctionKeyNoOnLeave()
void windowFunctionKeyNoOnLeave ()
References cx::messageBox(), cx::cxWindow::setKeyFunction(), cx::cxWindow::setOnLeaveFunction(), cx::cxWindow::showModal(), testKeyFunction(), and testOnLeaveFunction().
Referenced by doMenu().
windowWriteText()
void windowWriteText ()
References cx::cxWindow::show(), and cx::cxWindow::writeText().
Variable Documentation
gStatusLine
shared_ptr<cxWindow> gStatusLine
Referenced by doMenu(), and main().
gTitleLine
shared_ptr<cxWindow> gTitleLine
Referenced by doMenu(), externalTitleWindow(), and main().