cxWidgets: /home/erico/projects/cxWidgets/tests/test_sizing.cpp File Reference
test_sizing.cpp File Reference
#include "cxMessageDialog.h"
#include "cxUtils.h"
#include <iostream>
#include <vector>
#include <string>
#include <cassert>
#include <deque>
Classes
class TestMessageDialog
Functions
int main ()
Function Documentation
main()
int main ()
References cx::cleanup(), TestMessageDialog::getActualHeight(), TestMessageDialog::getActualWidth(), TestMessageDialog::getMessageLines(), and cx::init().