cxWidgets: /home/erico/projects/cxWidgets/src/test_cxValidators.cpp File Reference
test_cxValidators.cpp File Reference
#include "cxValidators.h"
#include <iostream>
#include <cassert>
Functions
void test_isValidWholeNumStr ()
void test_isValidFloatingPtNumStr ()
int main ()
Function Documentation
main()
int main ()
References test_isValidFloatingPtNumStr(), and test_isValidWholeNumStr().
test_isValidFloatingPtNumStr()
void test_isValidFloatingPtNumStr ()
References cxValidators::isValidFloatingPtNumStr().
Referenced by main().
test_isValidWholeNumStr()
void test_isValidWholeNumStr ()
References cxValidators::isValidWholeNumStr().
Referenced by main().