cxWidgets: /home/erico/projects/cxWidgets/src/test_cxInput/test_cxInput.cpp File Reference
test_cxInput.cpp File Reference
#include <cxBase.h>
#include <cxInput.h>
#include <string>
#include <fstream>
#include <iostream>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References cxBase::cleanup(), cxInput::getValue(), cxBase::init(), and cxInput::showModal().